### ISSUE TITLE
Raytracing API

### ISSUE THREAD

**Issue by Kliaxe** [turanszkij/WickedEngine#102]
Hi again!

Nvidia in partnership with KhronosGroup and Microsoft released some time ago an extension that enables real-time ray-tracing. That means high performance ray-tracing for both Vulkan and Directx12, with Nvidia's RTX (soon AMD and Intel) cards lineup.
I've seen some truly amazing things you can do with it, especially with Unity and Unreal, and it could be so awesome to see WickedEngine with RTX Raytracing support anytime in the future!
I'd be more than happy to help with it, if it's a reality :)

**Comment by turanszkij** [comment]
Hi! Indeed, this would be nice to have, but I can't work on it as I don't have a raytracing GPU. Right now there is custom raytracing code written in compute shaders. You are welcome to try adding DXR style ray tracing to the engine.

**Comment by Kliaxe** [comment]
Yeah, embarrassing to say I don't have a fully RTX supported card either. I'm purposely waiting for their 3000 series cards, so I'm skipping the first generation.
If I'm not mistaken it requires as a minimum a GTX 1060 to use the extensions, which don't have those ray-tracing cores which is recommended. However, it should work for low quality prototyping. I'll see if i can get something out of it in the future though

**Comment by turanszkij** [comment]
Update: I got myself a 2060, so I'll try adding this in the near future :)

**Comment by turanszkij** [comment]
Added base implementation for ray tracing API, implemented in DX12. Added simple ray traced ambient occlusion.

TODO:
- Vulkan implementation
- denoising
- ray traced shadows
- ray traced reflections

**Comment by turanszkij** [comment]
- added VK_HR_ray_tracing
- added ray traced shadows (requires D3D12_RAYTRACING_TIER_1_1 for now)

**Comment by turanszkij** [comment]
#146 WIP new resource binding model will make it feasible to implement reflections with bindless descriptors or local root signatures.

**Comment by turanszkij** [comment]
The base ray tracing effects are now all implemented, they will be improved and optimized down the road.
