### ISSUE TITLE
Possible Memory Leak in wiJobSystem?

### ISSUE THREAD

**Issue by antonyjones67** [turanszkij/WickedEngine#103]
Intel i7, Windows 10, 64 bit, NVIDIA 1060 GPU

I don't understand why there is a memory leak here. Maybe you know?

---------- Block 1258 at 0x000000001AF197E0: 1 bytes ----------
  Leak Hash: 0xFCB922AD, Count: 1, Total 1 bytes
  Call Stack (TID 12424):
    ucrtbased.dll!malloc()
    d:\agent\_work\5\s\src\vctools\crt\vcstartup\src\heap\new_scalar.cpp (35): WickedEditor.exe!operator new() + 0xA bytes
    D:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.24.28314\include\memory (2055): WickedEditor.exe!std::make_unique<std::tuple<<lambda_b58ca66cedc21914795fb7008579e703> >,<lambda_b58ca66cedc21914795fb7008579e703>,0>() + 0xA bytes
    D:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.24.28314\include\thread (57): WickedEditor.exe!std::thread::thread<<lambda_b58ca66cedc21914795fb7008579e703>,void>() + 0x17 bytes
    D:\Dev\WickedEngine\WickedEngine\wiJobSystem.cpp (48): WickedEditor.exe!wiJobSystem::Initialize() + 0x26 bytes
    D:\Dev\WickedEngine\WickedEngine\wiInitializer.cpp (27): WickedEditor.exe!wiInitializer::InitializeComponentsAsync()
    D:\Dev\WickedEngine\WickedEngine\MainComponent.cpp (71): WickedEditor.exe!MainComponent::Initialize()
    D:\Dev\WickedEngine\WickedEditor\WickedEditor.cpp (25): WickedEditor.exe!Editor::Initialize()
    D:\Dev\WickedEngine\WickedEngine\MainComponent.cpp (100): WickedEditor.exe!MainComponent::Run()
    D:\Dev\WickedEngine\WickedEditor\main.cpp (205): WickedEditor.exe!wWinMain()
    d:\agent\_work\5\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl (123): WickedEditor.exe!invoke_main()
    d:\agent\_work\5\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl (288): WickedEditor.exe!__scrt_common_main_seh() + 0x5 bytes
    d:\agent\_work\5\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl (331): WickedEditor.exe!__scrt_common_main()
    d:\agent\_work\5\s\src\vctools\crt\vcstartup\src\startup\exe_wwinmain.cpp (17): WickedEditor.exe!wWinMainCRTStartup()
    KERNEL32.DLL!BaseThreadInitThunk() + 0x14 bytes
    ntdll.dll!RtlUserThreadStart() + 0x21 bytes
  Data:
    CD

**Comment by turanszkij** [comment]
Thanks forreporting it, currently I don't have an idea what's wrong there. Are detached threads that running an infinite loop could be identified as memory leak by any chance?
