### ISSUE TITLE
Animations: decouple data from targets

### ISSUE THREAD

**Issue by alexwennstrom** [turanszkij/WickedEngine#105]
I'm about to implement a ECS type system in our visualization engine. I realy like the implementation in WE it is very simple and clean. Some questions arise tho. Most of all considering object-entity that reference a mesh-entity.  In WE there is no concept of resources. For example a mesh-component is the actual mesh an object-component can reference a mesh but they need both to be entities because object needs a mesh-entity reference. Is it not better that a mesh component is only a reference to a mesh-resource? Same thing with animations, animation component contains animation data. But if there are many objects playing same animation independently they all have a copy of animation data (animation data can be quite big). Is it not better to have a animation-resource and let animation-component reference that data? So in a scene, first load all resources (textures, meshes, animations, ...), then, create entities with components, components reference resources (can also be ref counted).

**Comment by turanszkij** [comment]
Hi, there is a "resource concept" (wiResource), it is used for textures and sounds, that are loaded from the disk from common file formats, separate from the scene entity/components, which are stored in a custom format. I could see the idea of decoupling animation data from the animation entity/component to be reasonable. But for meshes, the current approach is fine as it is, there is already the capability to multiple objects/particle systems share the same mesh.

So the animations problem that you describe is actually on point, currently there is not a good way to share animations. And to share animations, we would need to retarget animations to be applied to a different group of entities.

**Comment by alexwennstrom** [comment]
Could just split Animation into data and instance. Data contains pure transforms and keyframes. Instance contains a reference to data, parameters (loop, speed, etc.) and animation time. 

But animation component is not the confusing one the confusing one is the Mesh component. Mesh component belongs to a separate entity than object and object entity references the mesh entity. I'm curious why you choose that design idea because maybe there is a point doing it that way.

**Comment by turanszkij** [comment]
The mesh is separate entity from the object, because multiple objects can have the same mesh.

**Comment by alexwennstrom** [comment]
I understand now why it can be tricky to instantiate animation data. That is because animation channels points to Entity. I stumbled on same problem. I think animation instance can hold a array that maps entities to respective channel into animation data, this is a small overhead an adds complexity but in situations where there is allot of instanced, independent animated objects/characters it should pay off.

**Comment by turanszkij** [comment]
AnimationDataComponent now stores animation keyframe data separately from AnimationComponent. This also maps more closely to GLTF behaviour.
