### ISSUE TITLE
DX12 assert error

### ISSUE THREAD

**Issue by christliu** [turanszkij/WickedEngine#11]
When I run Test as dx12, I got an assert error like this

Program: G:\GameEngine\WickedEngine\Win32\Debug\Tests.exe
File: g:\gameengine\wickedengine\wickeden...\wigraph...x12.cpp
Line: 1435.
I debug for this hr return value and I got DXGI_ERROR_DEVICE_REMOVED.
How was that happen?
Thanks very much.

**Comment by turanszkij** [comment]
Thanks for reporting this, I will look into this.

**Comment by turanszkij** [comment]
If you write `debugdevice` to the command line arguments, you should get a D3D12 ERROR or something like that in the Visual Studio output window. What does it say?
