### ISSUE TITLE
Light direction dependent shadow artefacts when not at the origin

### ISSUE THREAD

**Issue by jdswebb** [turanszkij/WickedEngine#115]
When not at the origin (e.g. at (2000,2000) in the attached example file), shadow artefacts appear depending on the light angle. This happens just changing the yaw. The shadow quality appears to be drastically lower at certain angles and the transition between cascades becomes harsh.

https://www.youtube.com/watch?v=wig-x3_iKFA&

Another video showing it on a larger scene, in case it gives any clues (initially with a bad angle, then a good one):

https://www.youtube.com/watch?v=UmNUgPMmU3M&

[shadow_test6.zip](https://github.com/turanszkij/WickedEngine/files/4663669/shadow_test6.zip)

**Comment by turanszkij** [comment]
Thanks for reporting, this should be fixed now. (cascade near/far plane was not computed correctly, so objects clipped early)
