### ISSUE TITLE
Render in texture

### ISSUE THREAD

**Issue by Geniok** [turanszkij/WickedEngine#118]
I am trying to implement an editor using the ImGUI library.
In order to show a scene, it is necessary to implement a render in a texture, not in a window.
Next, this texture is displayed. I can’t understand how to do this in the current implementation.
Something like this is needed:
![DsnVEYUXgAI2eXn](https://user-images.githubusercontent.com/3386000/82944156-64ed9980-9fa3-11ea-80f0-74184856939c.jpg)

**Comment by turanszkij** [comment]
The RenderPath3D class is responsible to render the scene, it renders to textures in the Render() function and draws that texture to the screen in the Compose() function. The user can override the functionality by deriving from that class. For example RenderPath3D_Forward is one that implements forward rendering, it can be used as reference.

**Comment by Geniok** [comment]
Well, thanks, I'll try to come up with something.

Do you have any plans for introducing the Dear ImGUI library in the future? My performance tests showed that GUI output using ImGUI is faster than with the current implementation.

**Comment by turanszkij** [comment]
I have no plan for integrating a gui library and prefer to improve the current one. It's perfectly fine if someone wants to use an other gui library in their own project.

**Comment by turanszkij** [comment]
Feel free to reopen if you want to continue the discussion.
