### ISSUE TITLE
setup a project in Vs2019

### ISSUE THREAD

**Issue by bendico1** [turanszkij/WickedEngine#119]
Hi,
I'm trying to set up a project in Visual Studio 2019 (X64), but when I build there are these errors: "E0461	initial value of reference to non-const must be an lvalue" and "C2440	'initializing': cannot convert from 'DirectX::XMVECTOR' to 'DirectX::XMVECTOR &".
What's wrong?
Thanks for your support.	

    _Cosmo_

**Comment by turanszkij** [comment]
Hi, Visual Studio 2019 should be able to build the projects by default. I wonder if you have some compiler settings that are not compatible? Can you build the Editor_Windows project for example that is bundled with the repo?

**Comment by bendico1** [comment]
Yes, I can. I successfully build the Editor_Windows and Test projects.
Can you suggest me, please, which are the compiler settings you mentioned?
I setup my project properties as stated in the "Getting started" section of your Github page.
Thank you so much for your help.

**Comment by turanszkij** [comment]
I'm not sure. Could you compare/copy your settings from the Tests or Editor project? That way it would surely work.

**Comment by bendico1** [comment]
Thanks, I solved the issue.

**Comment by turanszkij** [comment]
Could you tell me what the problem was? I think I am using some non-standard c++ stuff and it would be best to fix these.

**Comment by bendico1** [comment]
Cause a terrible mistake of mine, I swapped WickedEngine Debug/Release lib. when I configured my Vs Project properties->"Additional Lib dir".
Sorry, I'm a beginner and I'm trying Wicked engine for learning purpose.

**Comment by turanszkij** [comment]
Thanks for clarifying! Feel free to reopen if you have more questions.
