### ISSUE TITLE
[Question] Support Qt Embedding

### ISSUE THREAD

**Issue by dwlcj** [turanszkij/WickedEngine#12]
Hello Turánszki János!
This is a very cool project. Light and powerful！
Is it possible to embed wiRenderer into Qt widget and if so, how? This functionality would be extremely useful for interactive 3D content in Qt , since both Unity and UE4 cannot be embedded into Qt without extensive hacks.

**Comment by dwlcj** [comment]
wonderful, very much looking forward to it!

**Comment by turanszkij** [comment]
As I understand, you were already successful embedding to qt in this issue: #14 so I'm closing this.
