### ISSUE TITLE
DX12 & Vulkan Path Tracing error

### ISSUE THREAD

**Issue by happydpc** [turanszkij/WickedEngine#121]
When switch the render pass to vulkan or DX12, the path tracing run into an error here:
![image](https://user-images.githubusercontent.com/771776/83962365-42c31800-a8cf-11ea-9a1d-fa9cf6740973.png)

**Comment by happydpc** [comment]
The call stack is :
![image](https://user-images.githubusercontent.com/771776/83962515-ae59b500-a8d0-11ea-92cc-5a22f1a86d02.png)

**Comment by turanszkij** [comment]
Thanks for reporting, it is now fixed.
