### ISSUE TITLE
Select discrete GPU card on hybrid notebooks

### ISSUE THREAD

**Issue by happydpc** [turanszkij/WickedEngine#122]
DX11、DX12 and vulkan cannot use the discrete GPU on notebook with hybrid. Maybe there can be an option to force use discrete or integral GPU.

**Comment by turanszkij** [comment]
It should already select the dedicated GPU, for AMD and Nvidia. These are the settings for the drivers: https://github.com/turanszkij/WickedEngine/blob/master/WickedEngine/wiGraphicsDevice.cpp#L6
I don't have a setup to test this now, but it was working at some point.

**Comment by happydpc** [comment]
Thank you for the tip, I will have a test.

**Comment by happydpc** [comment]
Vulkan may not work, I add this code:

```cpp
	bool foundDiscrete = false;
			//find the discrete device
			for (const auto& device : devices)
			{
				auto props = VkPhysicalDeviceProperties{};
				vkGetPhysicalDeviceProperties(device, &props);
				if (props.deviceType == VkPhysicalDeviceType::VK_PHYSICAL_DEVICE_TYPE_DISCRETE_GPU)
				{
					physicalDevice = device;
					foundDiscrete = true;
					break;
				}
			}
			
			if (!foundDiscrete)
			{
				for (const auto& device : devices)
				{

					if (isDeviceSuitable(device, surface))
					{
						physicalDevice = device;
						break;
					}
				}
			}
```

**Comment by turanszkij** [comment]
That solution looks good. The driver values that I mentioned earlier is maybe only for DirectX

**Comment by turanszkij** [comment]
This is fixed now.
