### ISSUE TITLE
Async Load Resource 

### ISSUE THREAD

**Issue by happydpc** [turanszkij/WickedEngine#123]
I have a question about resource loading. How can I load meshes out of the Update function? I want to load massive models, and how can I implement an async loading work?

**Comment by turanszkij** [comment]
Hi, you can use a c++ thread to load a Scene in the background. You can also use the LoadingScreen class, the Editor uses it for example.

You will have to look out to not render the scene and load into it in the same time. For that, you can load a separate Scene that you create yourself on a background thread, then use `Scene::Merge()` on the main thread to merge it into the global scene (the one you get via `wiScene::GetScene()`) which will be fast.

**Comment by happydpc** [comment]
Thank you for the tips. I will have a try.

**Comment by turanszkij** [comment]
Feel free to reopen to continue discussion.
