### ISSUE TITLE
Update and Render calls taking too much CPU usage

### ISSUE THREAD

**Issue by happydpc** [turanszkij/WickedEngine#127]
When there are no any input events or something need an update, the CPU should be auto idled not to update every frame and prepare command buffer every frame. I wonder how to reuse the render command buffer instead of generating them into the same ones, and also when no events, I can suspend the update routine. 

![image](https://user-images.githubusercontent.com/771776/84597296-a7fda700-ae95-11ea-8330-206bb447b127.png)

**Comment by turanszkij** [comment]
The problem is that there are lots of things that could be changing, even though the user is not inputting anything. Any game script or physics can also change things in the scene or think about shaders that change with time input like the sky. It would be a lot of effort to detect every case like that, and the payoff is only when the user doesn't input anything which is not typical.

**Comment by turanszkij** [comment]
By the way, how many objects do you have in that scene? And what CPU are you using (how many cores)? The numbers you show here are a bit high, let me know if you have a performance problem.

**Comment by happydpc** [comment]
I will soon make a profile. ECS can do very well in optimizing parallel things. But I have a question, can we reuse the command buffers from the last frame when there are no more new dirty things. But still with camera MVP updating. Instead of just generating them again and again when there are massive renderable objects.

**Comment by happydpc** [comment]
I found another problem, How can I share the meshes, and use them with different materials? I found that material was placed in mesh component.

**Comment by turanszkij** [comment]
> can we reuse the command buffers from the last frame when there are no more new dirty things. But still with camera MVP updating. Instead of just generating them again and again when there are massive renderable objects.

The camera MVP is also affecting how command buffers are built. Consider frustum culling, occlusion culling, sorting.

> How can I share the meshes, and use them with different materials? I found that material was placed in mesh component.

Sorry, there is no way to do that currently, as you said the mesh is bound to the material. I will think of a way to solve this.

**Comment by happydpc** [comment]
Thank you much for your support. 
Can wicked engine change the clear color (just set background color), or are there any solutions can enhance the environment ambient color. Now the whole scene looks two dark, I have tried adjust the weather component, but still not bright enough. The horizontal take too much place.

![image](https://user-images.githubusercontent.com/771776/85147427-69932e00-b281-11ea-8031-e843a3f49bf9.png)

**Comment by turanszkij** [comment]
You can try using "simple sky", which lets you specify the up and down sky colors directly, but in that case, there will not be clouds rendering.

An other thing you can do is to increase the "Exposure" in the Post process window, which affects full screen tonemap brightness.
