### ISSUE TITLE
LOD support 

### ISSUE THREAD

**Issue by happydpc** [turanszkij/WickedEngine#129]
There is no option to automatically toggle different meshes according to the view distance. With LOD feature, the big mesh can be easily used in the scene. 
  And also the object component, I think it should take several mesh entities, not just one. With only one mesh contained, the object has to be created again and again.

**Comment by turanszkij** [comment]
There is no mesh LOD support now, so I added it to feature requests. The only LOD support now is impostors (switching out mesh to billboards at distance).

**Comment by CaminoOnPc** [comment]
Also, what is the reasoning behind having wiscene to be used for both models and scenes? Why not have a separate file for a model, let's say wimodel, that would remove some unnecessary things for models such as terrain, weather, etc hence potentially improving loading times and optimizing it overall?

**Comment by turanszkij** [comment]
Having only the wiscene is great for simplicity and flexibility. If the scene doesn't contain weather, or something, the overhead is minimal, only an integer will be read that says there are zero components of that type so they will be skipped. There is no plan to have an other kind of "model" loading.

As for LOD support, this can be implemented right now using custom code by switching meshID per ObjectComponent (based on distance for example). There is also a built in system that can render impostors.

**Comment by turanszkij** [comment]
This was implemented in https://github.com/turanszkij/WickedEngine/commit/604140ad8529a486aee7f8817497fe5d2f9e8bb0
