### ISSUE TITLE
Where is the shaders of Vulkan API?

### ISSUE THREAD

**Issue by Superlee506** [turanszkij/WickedEngine#132]
Hi, thanks for this great project.  As you mentioned in the readme file ,  vulkan shaders are in "WickedEngine/shaders/spirv ". But I can't find these files.

**Comment by turanszkij** [comment]
Hello, you need to build the Shaders_SPIRV project in Visual Studio to build the Vulkan shaders. It requires Python 3 to build Vulkan shaders.

**Comment by Superlee506** [comment]
@turanszkij Thanks~
When vulkan and dx11 are both installed on my computer, how can I choose which version to build?
emmm, could you please provide some detailed build instructions in the documents. I think this would help a lot people who are not familar with VS.
Thanks again.

**Comment by turanszkij** [comment]
If you have Vulkan SDK installed and build, the exe will have DX11, DX12 and Vulkan available. You can choose between API by entering command line argument `vulkan` to choose Vulkan API, or `dx12` to choose DX12, or nothing to default to dx11. This is described in the readme. Command line arguments can be entered in Windows for the shortcut to application executable, or in Visual Studio Project Settings -> Debug -> command line

**Comment by Superlee506** [comment]
Thanks~
