### ISSUE TITLE
Request: Vehicle physics

### ISSUE THREAD

**Issue by RenderingFiend** [turanszkij/WickedEngine#139]
Hi,
I'm writing this after a very frustrating session with Unreal Engine 4 and trying to get their absurd vehicle system to work.
I really like Wicked Engine, I was wondering if you might consider adding a Vehicle template at some point? You've proven to be a highly skilled and dedicated programmer, I feel like if you were to implement this I could kiss UE4 goodbye and just use your engine.
If not, I understand.

**Comment by turanszkij** [comment]
I have zero experience with vehicle physics, but adding this to feature requests.

**Comment by RenderingFiend** [comment]
@turanszkij If you have zero experience with it don't worry about it. Up to you.

**Comment by turanszkij** [comment]
Maybe someone else can take this task in the future if not me. What are you looking for in a vehicle template?

**Comment by RenderingFiend** [comment]
Basically, just a vehicle mesh with physics attributes like suspension, torque, max RPM, stuff like that.
This can be done in UE4 but I'm starting to hate that engine: it seems like all I have to do is change a single variable outside of what they expected most users would do and the engine crashes. I'm tired of all the crashing, and with UE4, they use PhysX for the vehicles, and they have this dumb torque curve setup where you have to add lines to a graph which can be a nightmare since it rarely displays correctly.

In the end I'm looking to make a simple racing game, with any game engine that doesn't crash on me constantly ;)

**Comment by RenderingFiend** [comment]
I'd like to close this issue, I've managed to get it working on UE4 after doing some code modifications.
