### ISSUE TITLE
I has embed in Qt app, but how resize render window?

### ISSUE THREAD

**Issue by dwlcj** [turanszkij/WickedEngine#14]
Hello！I has embed in Qt app, It's work fine.
![fine](https://user-images.githubusercontent.com/252897/45521213-a4844a00-b7ef-11e8-9877-d05076dd4bb3.jpg)

but resize window，It's wrong.
![wrong](https://user-images.githubusercontent.com/252897/45521235-b82fb080-b7ef-11e8-864e-12593fab5db6.jpg)

My resize Code：
`	wiRenderer::GetDevice()->SetResolution(evt->size().width(), evt->size().height());
	wiRenderer::getCamera()->SetUp((float)wiRenderer::GetInternalResolution().x, (float)wiRenderer::GetInternalResolution().y, 0.1f, 800);`

Please help me! Thanks

**Comment by turanszkij** [comment]
Hi, this is now fixed (version 0.20.4). Let me know if you still have problems. Thanks for reporting, have a nice day!

**Comment by dwlcj** [comment]
That is great! 
resize window is ok！
Thanks turanszkij !

**Comment by dwlcj** [comment]
Hi,Embedding Qt is very simple.
This is my code.
`void RenderWidget::initialise()
{
	mTests = new Tests();

	//wiStartupArguments::Parse(L"vulkan");
	//wiStartupArguments::Parse(L"hlsl6");

	mTests->SetWindow(HWND(winId()), GetModuleHandle(NULL));

	mTests->Initialize();

	mIsInitialised = true;

	mTimer->setInterval(12);

	mTimer->start();

	mLoadWidget->hide();

	std::cout << "RenderWidget::initialise11" << std::endl;

	emit initialised();

}
`

`void RenderWidget::resizeEvent(QResizeEvent* evt)
{
	if(mIsInitialised)
	{
		wiRenderer::GetDevice()->SetResolution(evt->size().width(), evt->size().height());
		
		wiRenderer::getCamera()->SetUp((float)wiRenderer::GetInternalResolution().x, (float)wiRenderer::GetInternalResolution().y, wiRenderer::getCamera()->zNearP, wiRenderer::getCamera()->zFarP);
	}
}
`

**Comment by turanszkij** [comment]
Thanks for the qt example!
