### ISSUE TITLE
Volumetric Cloudscapes

### ISSUE THREAD

**Issue by Kliaxe** [turanszkij/WickedEngine#147]
Hi turanszkij!

Not too long ago I finally got the time to play Horizon: Zero Dawn and RDR2, which has an astonishing environment particularly for their clouds. The games then got me inspired to create some volumetric clouds as well.
Lately I've seen you implement support for terrain, alongside with painting tools which makes it possible to make some interesting scenery. With the engine constantly getting better (wow!) I then thought it could be awesome to have some nice looking clouds to go with it. So I began experimenting and think I got something that looks quiet good!

Here is a preview running in Wicked Engine:
![Anmærkning 2020-07-20_1](https://user-images.githubusercontent.com/16865975/87993605-3dbad080-caeb-11ea-9b8d-61adad76ca3c.png)
![Anmærkning 2020-07-20_2](https://user-images.githubusercontent.com/16865975/87993631-49a69280-caeb-11ea-912d-e5551de30ca0.png)
![Anmærkning 2020-07-20_3](https://user-images.githubusercontent.com/16865975/87993640-4c08ec80-caeb-11ea-83ec-0ee17c8066ce.png)
![Anmærkning 2020-07-20_5](https://user-images.githubusercontent.com/16865975/87993641-4d3a1980-caeb-11ea-9efc-02f5b3275f45.png)

Ultimately I want to ask if this could benefit the project :)

**Comment by turanszkij** [comment]
Wow, this is amazing! It would most definitely benefit the project!

**Comment by Kliaxe** [comment]
As you can see in the preview, the atmosphere is a bit different. I also added an alternative atmosphere model, that should match the directional light more. It's basically a more accurate version, but not super realistic or anything. It's based on these articles if you're curious:
https://www.scratchapixel.com/lessons/procedural-generation-virtual-worlds/simulating-sky
https://developer.nvidia.com/gpugems/gpugems2/part-ii-shading-lighting-and-shadows/chapter-16-accurate-atmospheric-scattering
In my implementation I just added a simple button to choose between the two models (customizable and accurate). I think it looks really nice with the clouds.

Since the engine has light shafts, I also added support for that too. I had a hard time deciding the best way to combine the current light texture in the light shaft effect, with the one exported from the clouds. So I thought once i upload the pull request we could just take it from there.

**Comment by Kliaxe** [comment]
Btw are there any easy way to get the primary directional lights energy or intensity in shader, like GetSunDirection() and GetSunColor() ? I can only think of an expensive way of doing it.

**Comment by turanszkij** [comment]
Sounds good, I'm curious about the new atmosphere too. The light shafts work like this:
1) draw sun against black background and using stencil from geometry pass to occlude sun
2) draw current clouds but blacked out (and sharpened silhouettes) on top of sun
3) radial blur post process on full screen, center of blur is the sun
I think the same might work for the volumetric clouds, just draw them black (and maybe reduced quality for perf, because it is only an occluder that will be highly blurred anyway)

**Comment by turanszkij** [comment]
I wonder, if the new atmosphere can be simply applied to objects too? Because the current sky colors get applied to objects as ambient color and reflection color (if there is no cubemap capture). If there is cubemap capture, the ambient and reflection will come from that. If the new atmosphere is very heavy, like raymarching stuff, then it probably won't be applied to regular objects.

Feel free to open the pull request any time (but there is no rush).

**Comment by Kliaxe** [comment]
I thought about that too. Since the new atmosphere is derived from GetDynamicSkyColor() it should just work in the same way as the original. The atmosphere uses something called rayleigh scattering coefficients which can give the iconic blue colors on the top. Right now it uses the GetZenithColor() to modify those coefficients. I didn't really have a place to use the GetHorizonColor() in the code but maybe I'll figure something out. Performance wise I saw a 2-3 ms difference on an old gaming laptop, when using the new atmosphere on ground level, which is impressive in comparison to what we get from it.

This part in tonemapCS.hlsl:
`float luminance = dot(hdr.rgb, float3(0.2126, 0.7152, 0.0722));`
`luminance /= average_luminance; // adaption`
Is that a part of the tonemap or the eye adaption? I makes the scenes in generel a alot more contrast.
Shouldn't it in reality be something like this if so?:
`	if (tonemap_eyeadaption)
        {
            hdr.rgb /= average_luminance;
        };`
I could be totally wrong here and this could be done completely on purpose! This is just me speculating.

Sorry for the delay btw!

**Comment by turanszkij** [comment]
Right, if it's part of the GetDynamicSkyColor(), it should be applied everywhere just fine. 

The average_luminance value is computed in luminance space (so the dot(x, float3(0.2126, 0.7152, 0.0722)) is applied on that too, to be storable in 8 bit texture. The calculation itself is something I came up with long ago, maybe it's not the best possible way to do it.

It's fine, there is no hurry, glad you are working on this! :)
