### ISSUE TITLE
[Question] Support IES lights

### ISSUE THREAD

**Issue by dwlcj** [turanszkij/WickedEngine#15]
Hi turanszkij:
Is there any plan to add IES lights?
By IES lights I mean this:
[https://docs.unrealengine.com/en-us/Engine/Rendering/LightingAndShadows/IESLightProfiles](url)

**Comment by turanszkij** [comment]
No, there is no plan for this. It looks interesting, but I don't think I will investigate this very soon.

**Comment by turanszkij** [comment]
Closing this because it is unlikely to be implemented. I think there are enough lighting methods to choose from already. There is not enough demand for yet an other one at this time.

**Comment by turanszkij** [comment]
For future reference, IES data can be downloaded from: https://ieslibrary.com/en/browse
Could be investigated
