### ISSUE TITLE
[Bug] DX12 CTD on model/scene load

### ISSUE THREAD

**Issue by CasualDev242** [turanszkij/WickedEngine#151]
I can use DX11 just fine, but when I switched to DX12 via desktop shortcut with command line argument, Wicked Engine opens fine, then I choose to load a scene like Sponza or any other, and it says it's loading, then I get a CTD after a few seconds.
I'm not sure if this has been an issue for a while or not (I literally just realized for the first time I can't use "-dx12" I have to use "dx12", I'm dumb but in my defense most dev's use the dash), and I didn't see any output log. I looked through the documentation and I didn't see any options to output an error log either.

System:
Windows 10 Pro 64-bit Build: 19041.450
GTX 1070 gpu
16gb RAM
Ryzen 1700

If there is anything I can do to debug on my end let me know.

I also noticed a couple of other bugs but wanted to ask you if you want me to open separate issues for each or just list them here.

**Comment by turanszkij** [comment]
Hi, sorry for the trouble. What is a CTD? To debug the issue, you could try running the Debug build. Also, if you enter the `debugdevice` command line arg (no dash), the directx debug layer could output an error message to the Visual Studio console output.

**Comment by RenderingFiend** [comment]
CTD = Crash to Desktop.
I had downloaded the build artifact since I didn't need to make any source code changes, but I'll compile it myself and create a debug version. If I figure out the issue I'll let you know.
