### ISSUE TITLE
MSVC19 solution crashes on load

### ISSUE THREAD

**Issue by efedo** [turanszkij/WickedEngine#154]
When opening WickedEngine.sln from the master branch in VC19, the solution crashes after loading for about a second, without any error message or log output. I am attaching the system error event and details of my VC19 environment. It appears to be caused by a Common Object Runtime exception. Any ideas on what might be the cause?

[vc2019_env.txt](https://github.com/turanszkij/WickedEngine/files/5214215/vc2019_env.txt)
[crash_event.zip](https://github.com/turanszkij/WickedEngine/files/5214214/crash_event.zip)

**Comment by turanszkij** [comment]
Hi, sorry about the silence. I have no idea what the problem is, maybe rebooting/reinstalling Visual Studio could help here.
