### ISSUE TITLE
[Question] Support DXR

### ISSUE THREAD

**Issue by dwlcj** [turanszkij/WickedEngine#16]
Hi turanszkij:
Is there any plan to Support DX12 RayTracing?

**Comment by turanszkij** [comment]
This is planned, but not very soon. Right now there is compute shader based raytracing. You can select "Path Tracing" render path in the editor to try it. It can be extended to support hybrid (raster+raytrace) rendering later, and also compatible with DX11.

**Comment by dwlcj** [comment]
Well, turanszkij：
I test Path Tracing render path,it's very slow and too much noise. How can I set it up faster? I've also tested RadeonRays, real-time rendering is very fast.

I found SSR or PlanarReflection not supported material Roughness.
I also found Voxel GI in interior environment is Bad performance, Maybe I didn't use it correctly.
Best regards.

**Comment by turanszkij** [comment]
That's the state of these features for now. Right now I'm focused on rewriting cpu-side systems, so these will not be updated very soon.

**Comment by dwlcj** [comment]
I see, turanszkij.
Amazing project.
