### ISSUE TITLE
Suggestion : Native NVIDIA Blast support

### ISSUE THREAD

**Issue by Nolram12345** [turanszkij/WickedEngine#162]
Title explains what I mean. 
https://developer.nvidia.com/blast

**Comment by turanszkij** [comment]
Hi, thanks for the suggestion, but the license they use doesn't comply with the MIT license the Wicked Engine uses.

**Comment by Nolram12345** [comment]
Oh, okay. Didn't know that, I thought it might be possible to create a "plugin interface" that would allow the use of such libraries under another license.
