### ISSUE TITLE
Precomputed Atmospheric Scattering

### ISSUE THREAD

**Issue by Kliaxe** [turanszkij/WickedEngine#164]
Hi turanszkij!

We talked about this some time ago, when i uploaded the clouds into the engine. At that time I also experimented with some realistic atmosphere, but it was really slow. I wanted to do another attempt, but this time it's done properly.
So after some tweaking and bug fixing I finally got something that is persistent and looks really good in the engine!

This time the implementation is extremely fast and more feature rich compared to the old atmosphere!
It should work for all other effects like fog, ambient capture and even environment probes. It also works for path tracing.
I haven't tested it on Vulkan or Directx12, but in theory it should work.

It's also worth mentioning the implementation is based by Sébastien Hillaires papers on "A Scalable and Production Ready
Sky and Atmosphere Rendering Technique" (great btw). Here he also discusses previous implementations especially from [Eric Bruneton](https://github.com/ebruneton/precomputed_atmospheric_scattering), which was my go to, if it wasn't for his release of these papers. I chose to go with this implementation, because it's rock solid in terms of performance and stability compared to others he compared against. And imo it's easy to expand down the line.
In case you're curious here are the [papers](https://sebh.github.io/publications/egsr2020.pdf)

Here are some screenshots from the engine:
![sc_26-10-2020 15-04-27](https://user-images.githubusercontent.com/16865975/97186409-8a284300-17a1-11eb-92f3-76d8fef96fa3.jpg)
![sc_26-10-2020 15-08-13](https://user-images.githubusercontent.com/16865975/97186424-8eecf700-17a1-11eb-8986-04113b0ad150.jpg)
![sc_26-10-2020 15-09-17](https://user-images.githubusercontent.com/16865975/97186433-91e7e780-17a1-11eb-8949-73ba3d84d973.jpg)
![sc_26-10-2020 15-09-56](https://user-images.githubusercontent.com/16865975/97186440-944a4180-17a1-11eb-92d1-0ada12729f20.jpg)
![sc_26-10-2020 15-11-32](https://user-images.githubusercontent.com/16865975/97186450-96ac9b80-17a1-11eb-8e93-0a102bdb5a7e.jpg)
![sc_26-10-2020 15-13-56](https://user-images.githubusercontent.com/16865975/97186461-990ef580-17a1-11eb-9e23-26e5e4b33acb.jpg)
![sc_26-10-2020 15-21-04](https://user-images.githubusercontent.com/16865975/97186472-9ad8b900-17a1-11eb-9f7d-596943f269f1.jpg)

**Comment by turanszkij** [comment]
It looks beautiful! I'd happily accept your contribution if you'd like to add it to the engine.

**Comment by turanszkij** [comment]
I haven't read the papers, is this precomputed into a cubemap?

**Comment by Kliaxe** [comment]
It's actually computed into some lookup tables and later sampled into the sky color. The best thing is we can utilize the luts for other effects like the directional light to simulate colors depending on the time of day with a transmittance lut. That means we get orange colors at sunset, and vivid colors at noon.

I noticed the playground scene used a directional light with an applied orange color to simulate sunset, which makes totally sense, just be aware it does this for you when using this.

One thing that is missing is aerial perspective, which is the interaction between geometry and atmosphere. Right now you would'nt notice, but it becomes apparent if you're rendering large scale terrain or planets. Don't think it should be so hard to implement, but let me know if I should add that too.

Anyway, I'm glad you're liking it so far! :)

**Comment by turanszkij** [comment]
All of those sound good.

"One thing that is missing is aerial perspective... Don't think it should be so hard to implement, but let me know if I should add that too."

- Up to you, if you'd like to implement it, go ahead. But currently I don't have a vast terrain rendering, so not very important.

**Comment by Kliaxe** [comment]
A PR should be up and running now

**Comment by turanszkij** [comment]
Done in #165  
Thanks for contributing!

**Comment by turanszkij** [comment]
Just a quick question, what controls the sun disk's size? Right now it's a tiny dot, but on your last pic it's large.

**Comment by Kliaxe** [comment]
Oh that was just purely for the image. The sun disc size is controlled via GetSunLuminance(). Inside there's a variable called sunApexAngleDegree which controls the size of the sun.

**Comment by turanszkij** [comment]
Thanks!
