### ISSUE TITLE
[Question]The second parameter in function "ExecuteCommandList"

### ISSUE THREAD

**Issue by jacksparowtxz** [turanszkij/WickedEngine#17]
`deviceContexts[GRAPHICTHREAD_IMMERIATE]->ExecuteCommandList(commandlists[i], true);
			commandlists[i]->Release();
			commandlists[i] = nullptr;
			deviceContexts[i]->ClearState();`
I found that in the function `void ExecuteCommandList(
  ID3D11CommandList *pCommandList,
  BOOL              RestoreContextState
);`,you pass true to the RestoreContextState. After that you use the `clearstate()`to set all state .That means we do not need to save and restore the state after 'excutecommandlist'.So，I don't think this step is necessary.Besides,according to the  API document ,"When applications use FALSE, they can avoid unnecessary and inefficient state transitions.".I think pass "false" to the  'RestoreContextState 'is better.What do you think?

**Comment by turanszkij** [comment]
Thanks for the heads up. That is a dead code path which is not used for very long now. I will rewrite when I bring back multithreaded rendering. 👍

**Comment by turanszkij** [comment]
This is fixed now
