### ISSUE TITLE
Image sprites are not rendered correctly when streched

### ISSUE THREAD

**Issue by CaminoOnPc** [turanszkij/WickedEngine#170]
Whenever you stretch a sprite image like this:

```
static wiSprite imageSprite("image.png");
imageSprite.params.pos = XMFLOAT3(x, y, 0.0f);
imageSprite.params.siz = XMFLOAT2(64, 128);

RenderPath2D* path = (RenderPath2D*)m_Interface->m_Tier0->m_Rendering->m_RenderPath;
path->AddSprite(&imageSprite);
```

You have those weird interlaced lines that appear over an image, the effect can be seen bellow

![image](https://user-images.githubusercontent.com/35667100/97814988-bfe29580-1c93-11eb-8763-983f09f9668a.png)

In fact, this problem persists even in the editor:

![image](https://user-images.githubusercontent.com/35667100/97815003-dbe63700-1c93-11eb-9df5-66137d071ece.png)

This bug does not occur if you set the image to render in a full-screen mode, and this bug only occurs if you set either width or height to be less than the size of the original file, this bug does not occur if you make the image bigger than it is.

```
imageSprite.params.enableFullScreen();
```

However, obviously, that's not ideal.

**Comment by turanszkij** [comment]
I see, this is happening when you specify it in the loading screen sprite. I couldn't repro it if I created a sprite elsewhere and called Draw() on it. I will investigate.

**Comment by turanszkij** [comment]
It is fixed now. The RenderPath2D (which the LoadingScreen is) didn't call the mipmap generation on images, so it was sampling from an uninitialized mip level.
