### ISSUE TITLE
Morph Target Support

### ISSUE THREAD

**Issue by XthemeCore** [turanszkij/WickedEngine#179]
Morph targets can be useful in character customization and facial animation. According to glTF 2.0 specification, the format support morph target as well but has not been implemented yet in Wicked Engine.
[https://github.com/KhronosGroup/glTF-Tutorials/blob/master/gltfTutorial/gltfTutorial_017_SimpleMorphTarget.md](url)

I have implemented this feature. There is no conflict with master branch and no code has been removed. However, the archive version will be 53 or above to prevent breaking assets. I also add the tool for adjust weight in editor. 

If you're interested, I will make the pull request so you can check the code.
![image](https://i.imgur.com/L6qIFf9.gif)

**Comment by turanszkij** [comment]
This sounds and looks great, I'd be very interested in the pull request!

**Comment by turanszkij** [comment]
Thanks for contributing!

**Comment by XthemeCore** [comment]
There is no real implementation for updating normal yet. I just make a quick fix for the asset.

For optimization, I think morph targets should only be updated when their weight changed. It would be a nightmare if I have to update mesh with hundreds of morph targets every frames.

**Comment by turanszkij** [comment]
I added morph normal updating, and put everything to a more optimal place into the mesh update system. Also, now the CreateRenderData() is not called for updating morphs, but instead I update only the position/normal vertex buffer with UpdateBuffer(). This should allow updating lots of morphs at runtime.
