### ISSUE TITLE
It looks like Occlusion Culling is not working as it should.

### ISSUE THREAD

**Issue by Geniok** [turanszkij/WickedEngine#194]
I took the finished scene in the editor. Placed a plane in front of the camera that covers the entire scene. Then I enabled Wireframe output mode. At the same time, all objects that were covered by the plane were displayed.
As far as I understand, when Oclusion Culling was enabled, these objects should not have ended up in the render queue.
![4](https://user-images.githubusercontent.com/3386000/100523318-b5e38200-31c0-11eb-8d9a-6f48b93889e4.png)

[playground_2.zip](https://github.com/turanszkij/WickedEngine/files/5611048/playground_2.zip)

**Comment by turanszkij** [comment]
It won't work like this, only depth buffer can occlude objects, but the wireframe is not writing the depth buffer. Even if it would, the coverage would be minimal.

Instead, if the plane is rendered normally as solid, it should cause objects behind not to be rendered.

**Comment by Geniok** [comment]
Thank you, I see.
I just wanted to test how Oclusion Culling works.
Then such a question, did not find how to set the color of the mesh in Wireframe mode. Now it is always displayed in black. I want to make the grid output in white. Can you tell me how this can be done?

**Comment by turanszkij** [comment]
Sorry about the wireframe issue, it was a bit broken. I fixed it in 54f6c18454d8aae3bb8a51f9aa1ef71e1ed18f7f 
Object color and Material color will affect the wireframe color now.

**Comment by Geniok** [comment]
Thanks!
