### ISSUE TITLE
Problems with enabling Ray Traced shadow.

### ISSUE THREAD

**Issue by Geniok** [turanszkij/WickedEngine#195]
When Ray Traced shadow is enabled, there are bugs in the image in the form of stripes.

![5](https://user-images.githubusercontent.com/3386000/100523523-1b843e00-31c2-11eb-9485-72b5a511eb9b.png)

**Comment by turanszkij** [comment]
This is a problem with denoising. Denoiser is not very good, so a better denoiser has to be written instead.
Strangely, this problem is not as visible for me. Moving the camera around should improve it slightly.

**Comment by turanszkij** [comment]
This issue is "fixed", because rt shadows denoising is removed. The basic temporal AA will remove some shadow jittering when enabled. The true denoising will be implemented in the future.
