### ISSUE TITLE
When reloading the script, resources are not released.

### ISSUE THREAD

**Issue by Geniok** [turanszkij/WickedEngine#196]
If you reload the script by pressing the "R" key, then the resources that were allocated when the script was loaded are not released when the script is reloaded.
This leads to the consumption of RAM, which ultimately leads to its depletion.
It is very simple to check, load any script that can be reloaded, open the resource monitor and press the "R" key 10-20 times. it will be seen how the allocation of RAM increases with each new load of the script.

**Comment by turanszkij** [comment]
Thanks, there is a serious leak somewhere in lua bindings, I will investigate.

**Comment by turanszkij** [comment]
It should be fixed now. Not sure why but RenderPath destruction was not working correctly when it was allocated with new. With this update, allocations are handled better.
