### ISSUE TITLE
Swap Chain Creation Failed

### ISSUE THREAD

**Issue by djdduty** [turanszkij/WickedEngine#2]
I loaded the sln file into visual studio 2015, selected x64 as my target build and in debug mode with the WickedEngineEditor project as the startup project. I compiled everything just fine and tried to debug the WickedEngineEditor exe only to get a "Swap chain creation failed" dialogue. I do have the DirectX sdk installed (it compiled just fine) so I'm not sure the issue. My graphics card is a Nvidia gtx 980 ti hybrid, I'm on windows 10.

When trying to compile / run WickedEngineDemos I get the same issue (I first had to bypass some errors to do with the water demo, you may have broken that by updating the engine api but not the demos? I also had to add the x64 build platform to the primary demo project as it only had Win32 and x86 was conflicting with the x64 engine output binary.)

**Comment by turanszkij** [comment]
Hello, sorry for the complications. 
The debug configuration tries to create the device with D3D11_DEVICE_DEBUG flag, but if you have Windows 10, you have to install the graphics debugging layer to get it to work. You can also just build a release build (it will be much faster than debug), or comment out the 1330th line in wiGraphicsDevice_DX11.cpp (the one with the D3D11_DEVICE_DEBUG flag specified).

For the demo project, I hadn't updated it yet for the current engine version, but I will correct that, sorry.

Thank you for being interested in this repo! :)
