### ISSUE TITLE
Improvements to the component system

### ISSUE THREAD

**Issue by CaminoOnPc** [turanszkij/WickedEngine#207]
It would be great if there was a way to get a reference scene root entity that is the parent of all other objects in the scene, for example, if you were to import a model into the editor and activate physics on the whole model you wouldn't be able to do that if model consists of multiple bones, or if you wanted to move or rotate the whole model you wouldn't be able to do that as well.

**Comment by turanszkij** [comment]
This is too specific as I see it. It doesn't make sense for every entity to have a physics component. For example, it makes sense to have a RigidBodyComponent for an entity that also has an ObjectComponent (mesh instance). It makes sense to have a SoftBodyComponent for an entity with MeshComponent. It doesn't make sense to have a physicscomponent for a Material for example. 

My recommendation is to implement this to your specific needs in your application. For example, you load into a separate scene, then search for entities of interest, apply whatever you want, then merge the separate scene into your main scene. Something like:

```
Scene separate_scene;
LoadModel(separate_scene, "something.wiscene");

// Make physics component for every object:
for(size_t i = 0; i < separate_scene.objects.GetCount(); ++i)
{
  Entity entity = separate_scene.objects.GetEntity(i);
  RigidBodyPhysicsComponent& rigidbody = separate_scene.rigidbodies.Create(entity);
  // ...
}

GetScene().Merge(separate_scene); // separate scene will be added to main scene...
```

Does this sound good?

**Comment by CaminoOnPc** [comment]
Maybe you did not understand me correctly, but what i am referring to is for example when i import a gltf model that doesn't have a root bone that contains all model parts, such as this one on the picture:

https://cdn.discordapp.com/attachments/602811659224088583/791851567598272562/unknown.png

I want that whole model to be one entity so that for example i could select the root node in the editor, and move the whole model by moving that root node, or apply physics to that same root node for example without having to manually combine that whole model into one mesh in the blender as that way i wouldn't be able to apply rotor animations for this helicopter for example.

**Comment by CaminoOnPc** [comment]
As for the code you posted above, yes that could work, however that's not as convenient and i will be required to do that for every scene file that contains just a model and nothing else.

**Comment by CaminoOnPc** [comment]
> Maybe you did not understand me correctly, but what i am referring to is for example when i import a gltf model that doesn't have a root bone that contains all model parts, such as this one on the picture:
> 
> https://cdn.discordapp.com/attachments/602811659224088583/791851567598272562/unknown.png
> 
> I want that whole model to be one entity so that for example i could select the root node in the editor, and move the whole model by moving that root node, or apply physics to that same root node for example without having to manually combine that whole model into one mesh in the blender as that way i wouldn't be able to apply rotor animations for this helicopter for example.

Correction, you can move the whole model when the gltf root is selected, however, as mentioned above you cant activate rigid body physics for the root of the model without the workaround code that you posted above, and that's exactly what i want.

https://streamable.com/9sztgj

**Comment by turanszkij** [comment]
This is now possible by simply adding rigid body physics to any entity. If the entity doesn't have an ObjectComponent with valid mesh, then it is possible to create BOX, SPHERE and CAPSULE collider shapes only. If the entity is a parent, then child entities will behave as expected.

**Comment by turanszkij** [comment]
This should be good now I think, reopen if not.
