### ISSUE TITLE
incorrect lighting when using BC5 (ATI2/3DC) as normal map 

### ISSUE THREAD

**Issue by m0w1337** [turanszkij/WickedEngine#208]
Loading any map (albedo/normal/...) via wiResourceManager::Load(""); will result in inverted colors when the dds file is encoded as BC5 (ATI2/3DC) (See example dds file [here](http://el-wa.org/cyubevr/down_normal.dds))

**Comment by turanszkij** [comment]
Opened in Paint.Net, and in engine, they look fairly similar to me. Could you attach a result of what you expect?
![paintdotnet](https://user-images.githubusercontent.com/12954849/103220776-660fec00-4921-11eb-8240-06eacca81421.png)
![wickedengine](https://user-images.githubusercontent.com/12954849/103220782-67d9af80-4921-11eb-9904-08bfd1efcb89.png)

**Comment by m0w1337** [comment]
Hm opened in gimp it looks like that: 
It is a normal map, that works for an unreal game, nut with wicked i have to set the normal strength to negative.
![grafik](https://user-images.githubusercontent.com/11231913/103221613-58f3fc80-4923-11eb-91e8-5598358f151b.png)

**Comment by turanszkij** [comment]
In my case the map looks like the blue component is always 0. Your image looks like a proper normal map where blue component is 1. Why these two programs are getting different results, and which one is correct I wonder. 

Is this DDS supposed to be storing signed colors? So 0 would correspond to RGB -127 and 1 correspond to +127?

**Comment by m0w1337** [comment]
I think i found the problem:
there is a format of dds when used for normal maps that is discarding the blue channel, so if a BC5/ATI2 file is used as normal map source the engine seems to add the blue channel back in as it should be 1/255 - just like you said. It seems gimp does that by default. Found some Info here: 
https://wiki.beamng.com/Exporting_Textures_-_DDS_Files#BC5_.2F_ATI2_.283Dc.29

**Comment by m0w1337** [comment]
After further reading, the only problem is, that the shader has to calculate the blue channel for these types of normal maps. For anyone wanting to use normal maps with only two color channels (R and G) the normal map shader can be expanded with a simplified blue channel calculation without affecting performance very much.

Insert the following line into objectHF.hlsli:
`normalMap.b				  = normalMap.b == 0 ? 1 : normalMap.b;`
Normalizing is done automatically afterwards.
![Screenshot 2021-01-08 072436](https://user-images.githubusercontent.com/11231913/103981683-973eb680-5182-11eb-8d36-84400291e1f7.png)

**Comment by turanszkij** [comment]
The normal map fix is now added in https://github.com/turanszkij/WickedEngine/commit/d27ede94cc76a91ac1a1c9e4393db6460262d120
