### ISSUE TITLE
the procedure entry point could not be located in the dynamic link library

### ISSUE THREAD

**Issue by raptoravis** [turanszkij/WickedEngine#212]
the procedure entry point could not be located in the dynamic link library

![image](https://user-images.githubusercontent.com/4395022/103410374-e5aded00-4ba5-11eb-8d89-336b63273139.png)

**Comment by turanszkij** [comment]
If you are using Vulkan, you must use the latest Vulkan SDK and runtime. Could you confirm that you have the latest version?

**Comment by raptoravis** [comment]
yes, I aming using the latest: `1.2.162.0`

![image](https://user-images.githubusercontent.com/4395022/103413359-20b71d00-4bb4-11eb-94e4-942d80cae312.png)

**Comment by turanszkij** [comment]
Could you try updating the graphics driver or Windows? I am not sure what makes this fail unfortunately.

**Comment by raptoravis** [comment]
the windows is version 2004, 19041.685

and after updating the graphics driver,  it works finally!

thanks and it is really a good engine.

**Comment by turanszkij** [comment]
Nice! Thanks for letting me know!
