### ISSUE TITLE
Triple screen

### ISSUE THREAD

**Issue by Geniok** [turanszkij/WickedEngine#215]
Hello!
I want to implement Triple screen in my application. How can this be properly organized? I think that it is possible to create 3 cameras, but how to display an image from them simultaneously?

**Comment by turanszkij** [comment]
There are multiple ways. You can for example use 3 render paths (RenderPath3D) each with different cameras. If you set the RenderPath3D's `camera` pointer to a camera, it will use that camera to render, otherwise it will use the global camera that you get with `wiScene::GetCamera()`. It is fine to create cameras (`CameraComponent`) yourself.

At lower level, you can look into how the RenderPath3D handles camera internally. It uses 2 cameras: a main camera and reflection camera and can render the scene from those two cameras at the same time. This can be also extended and you will have more control over how your render logic goes.

**Comment by Geniok** [comment]
Thanks, I will try to implement it!

**Comment by Geniok** [comment]
Hey.
There was a problem with three RenderPath3Ds. The fact is that the MainComponent::Update () method is static, which, among other things, must call the RenderPath3D::Update() method.
In code, it looks something like this:
`void TripleScreenMainComponent::update()
{
#ifdef TRIPLE_SCREEN_SUPPORT
              this->activatePath(&m_rendererMain);
              MainComponent::update();

              this->activatePath(&m_rendererLeft);
              MainComponent::update();

              this->activatePath(&m_rendererRight);
              MainComponent::update();
	}
#else
	MainComponent::update();
#endif
}`

Therefore, the MainComponent::Update() method has to be called three times, which creates increased overhead.

**Comment by turanszkij** [comment]
Oh, I didn't mean to customize the MainComponent, but instead you could have a RenderPath2D as main renderpath. Then inside the main renderpath, you could have 3 RenderPath3Ds and call their Update() and Render() yourself

**Comment by Geniok** [comment]
`RenderPath3D::GetLastPostprocessRT ()` is a protected method, so it cannot be called from `RenderPath2D::Compose ()`. I got out of the situation by calling `RenderPath3D::Compose ()` for each `RenderPath3D`.
Faced with the situation of impossibility to assign each camera its own render resolution. Since the resolution is taken when creating a separate window, and I need to get three `Textures` from each camera of different resolutions as a result of the work.

An example of implementation is mirrors in the car. It is necessary to display in one window a picture from three cameras that look back at a given angle.

**Comment by turanszkij** [comment]
Sorry about the protected method, I don't remember why I did that, but I don't see a reason for it now, so I will change it to public. For changing the resolution of the RenderPath, you could override the `RenderPath2D::GetInternalResolution()` function. The `Compose()` function will scale the internal resolution textures to match the full screen resolution, so you probably don't want to use it for all 3 cameras.

On an other note, if you are doing reflection type thing, take a look at how the planar reflection rendering is implemented in `RenderPath3D`. Although it only supports one reflection camera, so it's not enough for your 3 rear view mirrors, maybe you can extend it somehow.

**Comment by turanszkij** [comment]
The protected method was changed to public in https://github.com/turanszkij/WickedEngine/commit/b1320569048a8fdf1f24b4507320fc06b5ba4ce8

**Comment by Geniok** [comment]
Thanks you!
