### ISSUE TITLE
crashed in vkCreateGraphicsPipeline when optimization disabled 

### ISSUE THREAD

**Issue by raptoravis** [turanszkij/WickedEngine#218]
in order to debug the shaders, in `WickedEngine\compile_shaders_spirv.py`
I tried to add the following line:
`cmd += " -Zi -Od "`
it crashed in vkCreateGraphicsPipeline.

however, with the following it can run:
`cmd += " -Zi "`
but, in renderdoc, when debugging the shader, is is only assembly. 

and, how to debug the shaders then if so?

**Comment by turanszkij** [comment]
Hi,

I just tried this and didn't find any issues. Which version are you using? (version number displayed in top left corner in the editor)

**Comment by raptoravis** [comment]
![image](https://user-images.githubusercontent.com/4395022/104866593-e7372d80-5979-11eb-98c6-5d3a4d023946.png)

![image](https://user-images.githubusercontent.com/4395022/104866630-ff0eb180-5979-11eb-8a9d-97d7fd6e26ea.png)

**Comment by turanszkij** [comment]
Looks like a shader is not found: `upsample_bilateral_uint4.cso`. Please rebuild the Shaders_SPIRV

**Comment by raptoravis** [comment]
no, i am sure it is not related to this missing shader.  (as i just got the lastest and did not refresh vs2019)

**Comment by turanszkij** [comment]
if you get latest and don't rebuild vulkan shaders, than you can get missing shaders. For me this crash seems like that. But if you have any validation layer messages that indicate otherwise, share them. You can turn on validation layer with `debugdevice` command line argument (Project properties->Debug->Command line). The validation layers will print messages to the console output.

**Comment by raptoravis** [comment]
thanks and anyway, I got the latest again:

![image](https://user-images.githubusercontent.com/4395022/104979072-5e35fa00-5a3e-11eb-844c-032b5efccc6d.png)

and, the following is the compile_shaders_spirv.py output, if `-Od` is removed and keep others the same, it can run.

btw, I added `debugdevice` and it seems no difference.

![image](https://user-images.githubusercontent.com/4395022/104979132-7f96e600-5a3e-11eb-885b-b95ed77b0ac8.png)

**Comment by turanszkij** [comment]
Sorry, I still can't reproduce this issue. I think it might be a graphics driver issue, could you try updating driver? Thanks.
