### ISSUE TITLE
Spriv python script doesn't generate build_SPRIV.bat

### ISSUE THREAD

**Issue by kadejsan** [turanszkij/WickedEngine#22]
When I run the script it lists all the .hlsl files and nothing happens. Do you think I am using wrong python tools to run the script?

**Comment by turanszkij** [comment]
Hi, I am not sure what might be wrong. This script is supposed to work with python 2.7. What is your python version? I haven't tested with python 3. The build_SPIRV.bat should be generated in the same directory. Sorry that I don't have a better build system in place for this, but vulkan support is in a very experimental state right now. Thanks for submitting the issue.

**Comment by kadejsan** [comment]
I'll try with 2.7. Thanks for response :)
