### ISSUE TITLE
Crash DX12

### ISSUE THREAD

**Issue by JopharVorin** [turanszkij/WickedEngine#227]
Hi! I have been lurking here for a while, but not being a registred user :)
I am getting an error that i cant get past, i usually solve these things myself.

D3D12 ERROR: ID3D12Device::CreateComputeShader: Shader must be cs_6_4, cs_6_3, cs_6_2, cs_6_1, cs_6_0, cs_5_1, cs_5_0, cs_4_1, cs_4_0. Shader version provided: cs_6_5. [ STATE_CREATION ERROR #881: CREATECOMPUTEPIPELINESTATE_INVALID_SHADER]
D3D12: **BREAK** enabled for the previous message, which was: [ ERROR STATE_CREATION #881: CREATECOMPUTEPIPELINESTATE_INVALID_SHADER ]

Im quite sure there is an issue with my setup...
Do you know the cause?

GTX 1660 Ti is my GPU.

**Comment by turanszkij** [comment]
Hi,
You should update drivers. If newest driver doesn't support shader model 6.5 for your GPU, you can also try modifying a line in compile_shaders_hlsl6.py and rebuild HLSL6 shaders.

This line:
```
cmd += "_6_5 "
```
Can be modified to this:
```
cmd += "_6_4 "
```
Some shaders that use shader model 6.5 features will not compile, but most of them should be ok.

**Comment by JopharVorin** [comment]
Thanks for your response, i have tried this before, and i tried it again now. I get an exception:
Here in Graphics device 12: Line 135:

hr = device->CreateCommandList(0, D3D12_COMMAND_LIST_TYPE_COPY, cmd.commandAllocator.Get(), nullptr, IID_PPV_ARGS(&cmd.commandList));
assert(SUCCEEDED(hr));

I updated my graphics card to latest drivers yesterday. And i can run The official DirectX Graphics Samples, without issue.
Im really sorry for bothering, i usually fix these things myself, but i somehow cant get past this

**Comment by turanszkij** [comment]
Could you change `ID3D12GraphicsCommandList6` to `ID3D12GraphicsCommandList5` in wiGraphicsDevice_DX12.h? Or go even lower than that. Some functions like `DispatchMesh` (mesh shader dispatch) will not compile like this however, but that's not very important.

**Comment by turanszkij** [comment]
Also, no problem because this is useful information, good to know that this doesn't work on a relatively recent GPU, it shall be improved.

**Comment by JopharVorin** [comment]
hr = frames[fr].commandLists[cmd]->Close(); fails, in GraphicsDevice 12: Line: 5598.
I have changed it from 1 to 5 still this error.

I will happily do more debugging, if you tell me what i shall do :)

**Comment by turanszkij** [comment]
Could you tell me your Nvidia driver version? There are too many issues here, so I am starting to doubt that the driver is up to date. I have no issues like this with Nvidia 1070 which I think is older than yours.

**Comment by JopharVorin** [comment]
461.40 Is the version
Yes 1070 is older.
It stands on the internet that my card should support this.

**Comment by turanszkij** [comment]
Do you have an other GPU in your system? Maybe it gets selected instead of the Nvidia. If it's possible, you could check which GPU gets selected by checking the description of the `DXGI_ADAPTER_DESC1 adapterDesc` when it is being filled in wiGraphicsDevice_DX12.cpp

**Comment by JopharVorin** [comment]
It shows my GTX 1660 Ti. Maybe it is bust?

**Comment by turanszkij** [comment]
I have no other ideas, sorry

**Comment by JopharVorin** [comment]
I will switch GPU, i have a 2080 Ti lying around :)

**Comment by JopharVorin** [comment]
Figured out the problem on the other computer!
Turns out you must install an optional update to hike up WDDM version.
