### ISSUE TITLE
reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [turanszkij/WickedEngine#23]
I would like to point out that identifiers like “[`_SHADERINTEROP_UTILITY_H_`](https://github.com/turanszkij/WickedEngine/blob/0e9fff9d3c783d7c6bdf518b42c78fc7603723af/WickedEngine/ShaderInterop_Utility.h#L1 "Update candidate")” and “[`_WI_ALLOCATORS_H_`](https://github.com/turanszkij/WickedEngine/blob/1fabd9ec7f3bebf220166f384ba14d2c9e93258f/WickedEngine/wiAllocators.h#L1 "Another update candidate")” [do not fit](https://www.securecoding.cert.org/confluence/display/cplusplus/DCL51-CPP.+Do+not+declare+or+define+a+reserved+identifier#DCL51-CPP.Donotdeclareordefineareservedidentifier-NoncompliantCodeExample%28HeaderGuard%29 "Do not declare an identifier which is reserved for the compiler implementation.") to the expected naming convention of the C++ language standard.
Would you like to adjust your selection for unique names?

**Comment by turanszkij** [comment]
Hi, what naming convention would you suggest for these header include guards? Instead of ```_SHADERINTEROP_UITILITY_H_``` change it to ```SHADERINTEROP_UITILITY_H```?
In any case, this is low priority for now.

**Comment by elfring** [comment]
Thanks for your adjustment of affected include guards.
