### ISSUE TITLE
Crash on Startup

### ISSUE THREAD

**Issue by dragonCASTjosh** [turanszkij/WickedEngine#234]
I have recently been experiencing a 100% crash on start-up. This occurs in both Debug and Release along with all API backends. 
I am running the latest game ready drivers from NVidia and have a very standard setup. The only thing possibly worth note is im running this from the D: drive (SSD).

Because Github does not allow me to uploads the dumps and stuff i have prepared a gdrive folder contining the dumps for DX11 and VK along with my DxDiag 
https://drive.google.com/drive/folders/1dtU5c8flSHXB1OvF0gT-TtGdJR7zhXeb?usp=sharing

This happens in both cmake and using the provided solution file (only DX11 in solution works). The dumps provided are using the cmake workflow.

**Comment by turanszkij** [comment]
Hi, you mentioned that "only DX11 in solution works", so I think the problem might be missing shaders in other ways. Try to rebuild shaders. I recommend you use the solution instead of the cmake, because I can not help in cmake issues. I think the cmake doesn't build dx11 shaders.

**Comment by turanszkij** [comment]
Unfortunately I couldn't investigate crash dump, couldn't match symbols

**Comment by dragonCASTjosh** [comment]
Fixed by recent CMake changes, possibly 5a2cf88cf44d105bb281698d993a55a8fc68751f
