### ISSUE TITLE
Please Change the Config.ini to this to solve startup issue on Linux

### ISSUE THREAD

**Issue by untndev** [turanszkij/WickedEngine#239]
Content of the /Edior/Config.ini is not set right from git repository there is a simple setting that you should change in order for the Editor to workit's the enable=1
--------------------Config.ini----------------------
enabled 1
x 0
y 0
w 1920
h 1080
fullscreen 0
borderless 1

----------------------

**[Update]**
This is an issue in Ubuntu 20.04 it Works fine on Windows 10 with enabled 0

**Comment by turanszkij** [comment]
This should instead work with enable=0, and the operating system find a suitable resolution automatically (like on windows)

**Comment by untndev** [comment]
> This should instead work with enable=0, and the operating system find a suitable resolution automatically (like on windows)

It works fine on Windows 10 with enabled 0 but not on Ubuntu 20.04 so if somebody faced this problem they should change enabled to 1, it's a work around.

**Comment by turanszkij** [comment]
This should be fixed now, without needing to modify config.ini
