### ISSUE TITLE
Remove unnecessary null pointer checks

### ISSUE THREAD

**Issue by elfring** [turanszkij/WickedEngine#24]
[An extra null pointer check is not needed in functions](https://isocpp.org/wiki/faq/freestore-mgmt#delete-handles-null "Do I need to check for null before delete p?") like the following.
* [gc_obj](https://github.com/turanszkij/WickedEngine/blob/bb10f92b7cb6269c8a46edd2dcd9abe00d25d267/WickedEngine/wiLuna.h#L257 "gc_obj function")
* [node](https://github.com/turanszkij/WickedEngine/blob/2ff8549c3482e4f331835bc49a66e0396ba4367d/WickedEngine/wiRectPacker.cpp#L127 "Destructor for node")
* [SAFE_DELETE](https://github.com/turanszkij/WickedEngine/blob/381f5714587c072aad707c80540daffe4fbf1085/WickedEngine/CommonInclude.h#L31 "SAFE_DELETE macro")

**Comment by turanszkij** [comment]
Hi, thanks for reporting this. I will consider removing the null pointer checks in these cases.

**Comment by turanszkij** [comment]
These are removed now, thanks for reporting.
