### ISSUE TITLE
Customizing shader is a little bit hard

### ISSUE THREAD

**Issue by cailuming** [turanszkij/WickedEngine#247]

**Comment by turanszkij** [comment]
This needs a bit more explanation.

**Comment by cailuming** [comment]
Sorry,I'm a beginer, I mean I dont know how to write a custom shader, for example, 
![image](https://user-images.githubusercontent.com/19427259/110719945-b6bc9300-8248-11eb-9508-8e5996575667.png)
seems no demo code either. Maybe,I have to go through the whole render related code to find valuable information.
And another question, I suspect whether vulkan shader could also be compiled to cso, and why not use SPIRV-Cross

**Comment by cailuming** [comment]
Finally I find how to custom, and bind shader 
![image](https://user-images.githubusercontent.com/19427259/110765775-7b918280-828f-11eb-8e31-e2e01f5e3e49.png)
![image](https://user-images.githubusercontent.com/19427259/110765889-9663f700-828f-11eb-94d0-cb7e52f76cd4.png)
It's similar to D3D API, But I still cannot understand What's  the class Translator used for

**Comment by turanszkij** [comment]
Hi,
Sorry for the lack of information. For an example about custom shaders take a look at the hologram shader: https://github.com/turanszkij/WickedEngine/blob/master/WickedEngine/objectPS_hologram.hlsl
This is registered as custom shader in code here: https://github.com/turanszkij/WickedEngine/blob/master/WickedEngine/wiRenderer.cpp#L1452

The custom shaders are used to set a user created shader for a specific object material (MaterialComponent). The shaders  are can be compiled for vulkan-spirv as well with the compile-shaders-spirv.py python script (this is not final, but a better compile option is not implemented yet). The shader must be placed into the WickedEngine_SHADERS project into the correct filter, so the `PS` filter for pixel shaders for example. The CMAKE can also be used to compile shaders.

The Translator that you found is the translator tool in the editor that lets you move objects. A custom pipeline state is used to render that with solid colors. This uses custom rendering code, but the "custom shader" for materials will not need custom rendering code, just using the MaterialComponent::SetCustomShaderID() function and rendering the scene as normal.

**Comment by cailuming** [comment]
Many thanks, You are so friendly and patient, I'm clear
