### ISSUE TITLE
Vulkan raytracing

### ISSUE THREAD

**Issue by amerkoleci** [turanszkij/WickedEngine#252]
Hi,
When enabling VK_KHR_acceleration_structure (https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VK_KHR_acceleration_structure.html) the VK_KHR_deferred_host_operations is necessary as well, but you enable it only if VK_KHR_ray_query is supported, this causes validation error and crash during vkCreateGraphicsPipelines call.

Same applies for: https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VK_KHR_ray_tracing_pipeline.html

**Comment by turanszkij** [comment]
Thanks!
