### ISSUE TITLE
x32 support?!

### ISSUE THREAD

**Issue by SupinePandora43** [turanszkij/WickedEngine#26]
x32 bit support?!

**Comment by turanszkij** [comment]
Do you mean 32-bit support? 32-bit build is supported.

**Comment by SupinePandora43** [comment]
@turanszkij, but where x32 editor builds?!

**Comment by RenderingFiend** [comment]
@SupinePandora43 You need to compile them. Assuming you are using Visual Studio, open WickedEngine.sln. By default when opening the projectt, at the top of the screen you should notice that by default the solution is set to Debug mode and will say "Win32" right next to it. Win32 = 32-bit build.

**Comment by SupinePandora43** [comment]
@RenderingFiend i will try it.
it will be very hard to me, because i'm usually use VSCode instead of Visual Studio

**Comment by turanszkij** [comment]
I am working on adding 32-bit build download link.

**Comment by turanszkij** [comment]
It should be working now, links updated in the readme. Let me know if there is a problem. :)

**Comment by turanszkij** [comment]
Just out of curiosity, why are you interested in 32-bit build specifically?

**Comment by SupinePandora43** [comment]
@turanszkij my PC is 32-bit

**Comment by SupinePandora43** [comment]
@turanszkij i can switch to x64, but my PC has low performance (CPU and Memory, also needed new system disk)

**Comment by turanszkij** [comment]
Got it, that is a valid reason. But performance will most likely be about the same with 32-bit and 64-bit builds.

**Comment by SupinePandora43** [comment]
@turanszkij  i got error `SetThreadDescription` not finded in `DLL KERNEL32.dll`

**Comment by turanszkij** [comment]
It seems that this function is only available starting from Windows 10, version 1607. What is your operating system version?

**Comment by SupinePandora43** [comment]
windows 7

**Comment by turanszkij** [comment]
Ahh, sorry but Windows 7 is not supported. There are many features that can't be supported in Windows 7 without a big headache and I don't have a Windows 7 machine to test, that's why I only do Windows 10 at the moment, sorry.

**Comment by SupinePandora43** [comment]
also `shadercompilers/dxc.exe` is x64

**Comment by turanszkij** [comment]
You don't need to use that, unless you want to compile Vulkan shaders or HLSL 6.0 shaders. By default, shaders are compiled as HLSL 5.0 automatically in Visual Studio. Also, those shaders are included in the pre-packaged build.

**Comment by SupinePandora43** [comment]
okay

**Comment by SupinePandora43** [comment]
i'm also can't run tests! error: cannot find `XINPUT1_4.dll`

**Comment by turanszkij** [comment]
That also requires Windows 10.

**Comment by turanszkij** [comment]
I will close this, but feel free to reopen if you have anything else to add.
