### ISSUE TITLE
Need help in JobSystem

### ISSUE THREAD

**Issue by cailuming** [turanszkij/WickedEngine#260]
![image](https://user-images.githubusercontent.com/19427259/116637227-e741c300-a995-11eb-902b-f1ec70c4aedb.png)
Hi,I'm confusing about why we call "work()" in main thread when failed to push the job into jobQueue. and the similar as in "Dispatch" function.

**Comment by turanszkij** [comment]
Hi, this is because the job queue can be full, and if that happens, the job system needs to drain it before adding new jobs. The work function removes one job from the jobQueue and executes it, so the jobQueue will have one more free space.

**Comment by cailuming** [comment]
Usually that will not happen, right? The main thread just afford something only when worker threads are buzy.  I think I have got the point by your help if my view is right

**Comment by turanszkij** [comment]
Yes, this should not happen often. If it happens and you find it is a problem, you could consider increasing the capacity of the jobQueue too and that will further reduce the chance to happen. By default the jobQueue can hold 256 jobs:
```cpp
wiContainers::ThreadSafeRingBuffer<Job, 256> jobQueue;
```

You can increase the capacity with the template argument:
```cpp
wiContainers::ThreadSafeRingBuffer<Job, 1024> jobQueue;
```

**Comment by cailuming** [comment]
Thanks,Now I think you are right , increasing the capacity is not better than fetching and eating from the full queue
