### ISSUE TITLE
Wicked Engine does not start

### ISSUE THREAD

**Issue by IgnaceSaenen** [turanszkij/WickedEngine#262]
Hi,

I was trying out the latest package of Wicked on windows. It's the first UWP app I'm launching, ever -> if not a bug please ignore. 

The app launches into DX11 and starts initialization then closes. I managed to take this screenshot, but if there are logs I need to pass on, just let me know. I have a rusty NVS 5200M on a i7 3720QM 4-Core

![image](https://user-images.githubusercontent.com/8048189/117859576-794ba480-b28f-11eb-85a0-9977c665c40e.png)

**Comment by turanszkij** [comment]
Please reopen if you still have crashes or have any more info
