### ISSUE TITLE
Help blender fork upbge?

### ISSUE THREAD

**Issue by BluePrintRandom** [turanszkij/WickedEngine#267]
Hello -  
I use the game engine "upbge" it's really amazing everywhere except skinning.
I was reading - https://wickedengine.net/2017/09/09/skinning-in-compute-shader/ - and it's a little complex for me to apply. 
(I am a py guy :D )

was wondering if you may want to start a branch on our fork of blender to improve skinning.
https://developer.blender.org/D11057 was just added (compute shader infrastructure)

we are a ragtag group of users / C++ / older openGL developers just trying to keep everything running for everyone.
https://github.com/UPBGE/upbge/branches

**Comment by turanszkij** [comment]
Hi, thanks for letting me know about this, but I'm unlikely to go into that right now.
