### ISSUE TITLE
Windows build spirv failed

### ISSUE THREAD

**Issue by zbzdys** [turanszkij/WickedEngine#27]
I'm using Windows10x64 to build spirv but failed, here is the err log:

lightCullingCS.hlsl:2:10: fatal error: 'cullingShaderHF.hlsli' file not found
#include "cullingShaderHF.hlsli"
         ^

In file included from lightCullingCS_ADVANCED.hlsl:2:
./lightCullingCS.hlsl:2:10: fatal error: 'cullingShaderHF.hlsli' file not found
#include "cullingShaderHF.hlsli"
         ^

In file included from lightCullingCS_ADVANCED_DEBUG.hlsl:3:
./lightCullingCS.hlsl:2:10: fatal error: 'cullingShaderHF.hlsli' file not found
#include "cullingShaderHF.hlsli"
         ^

In file included from lightCullingCS_DEBUG.hlsl:2:
./lightCullingCS.hlsl:2:10: fatal error: 'cullingShaderHF.hlsli' file not found
#include "cullingShaderHF.hlsli"
         ^

In file included from lightCullingCS_DEFERRED.hlsl:2:
./lightCullingCS.hlsl:2:10: fatal error: 'cullingShaderHF.hlsli' file not found
#include "cullingShaderHF.hlsli"
         ^

In file included from lightCullingCS_DEFERRED_ADVANCED.hlsl:3:
./lightCullingCS.hlsl:2:10: fatal error: 'cullingShaderHF.hlsli' file not found
#include "cullingShaderHF.hlsli"
         ^

In file included from lightCullingCS_DEFERRED_ADVANCED_DEBUG.hlsl:4:
./lightCullingCS.hlsl:2:10: fatal error: 'cullingShaderHF.hlsli' file not found
#include "cullingShaderHF.hlsli"
         ^

In file included from lightCullingCS_DEFERRED_DEBUG.hlsl:3:
./lightCullingCS.hlsl:2:10: fatal error: 'cullingShaderHF.hlsli' file not found
#include "cullingShaderHF.hlsli"
         ^

tileFrustumsCS.hlsl:2:10: fatal error: 'cullingShaderHF.hlsli' file not found
#include "cullingShaderHF.hlsli"
         ^

about 10 hsls cmds failed to compile, others were ok. I reconfirmed the file "cullingShaderHF.hlsli" existed. 

The file exists but i still have the "file not found" complains. Please help, thanks a lot!

**Comment by turanszkij** [comment]
Sorry for the trouble, but I can't reproduce this. Are you using the latest version? How did you download the repo, by zip, or by git cloning? Could you zip your entire repo and attach it here?

**Comment by zbzdys** [comment]
I downloaded the zip file, then unziped it. I have installed python2.7, so i just double clicked generate_shader_buildtask_spirv.py and got build_SPIRV.bat in the root directory. If i double click it, i can get build_SPIRV_errors.log in its parent-parent directory and no shaders can be compiled. Because there is no WickedEngine\shaders for you to `cd`, i have to create the directory by myself. Now i can double click the build_SPIRV.bat to get 237 file at WickedEngine-master\WickedEngine\shaders\spirv, but still some files failed to compiled and that is the err log shown above.

Thanks for your reply.

**Comment by turanszkij** [comment]
Good catch about the shaders folder not existing from the start, it's fixed now. I still can't reproduce the main problem though. Can you make sure that you have administration privileges for the command line you are running from? I have no other ideas for the moment. :(

**Comment by zbzdys** [comment]
cullingShaderHF.hlsli is coded by ANSI instead of utf-8. I opened the file with Notepad++ and notice this. By changing it to UTF-8 with BOM by notepad++, i have solved the problem. Now all 246 shaders compiled successfully. Thanks.

**Comment by turanszkij** [comment]
Thanks for reporting this. I will look into converting the file encodings to be consistent.
