### ISSUE TITLE
CMake Error Linux

### ISSUE THREAD

**Issue by spierrett** [turanszkij/WickedEngine#271]
I'm having problems building from source. I receive an error in terminal:

-- CALCULATING DEPENDENCIES FOR SHADER lib 
CMake Error: Attempt to add a custom rule to output "/home/[user]/Downloads/engine/WickedEngine/WickedEngine/shaders/spirv/.cso.rule" which already has a custom rule.
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Configuring incomplete, errors occurred!
See also "/home/[user]/Downloads/engine/WickedEngine/build/CMakeFiles/CMakeOutput.log".
See also "/home/[user]/Downloads/engine/WickedEngine/build/CMakeFiles/CMakeError.log".

[CMakeError.log](https://github.com/turanszkij/WickedEngine/files/6667140/CMakeError.log)

[CMakeOutput.log](https://github.com/turanszkij/WickedEngine/files/6667144/CMakeOutput.log)

This is after running: 
mkdir build
cd build
cmake .. -DCMAKE_BUILD_TYPE=Release
make

Platform:
Intel i5-9300HF
8GB RAM
GTX 1650
MX Linux 19.4.1(Debian Buster)

**Comment by turanszkij** [comment]
If you are using Ubuntu, make sure that you are following the steps in the readme: https://github.com/turanszkij/WickedEngine#linux 
The automatic nightly build definitely works on Ubuntu, so you can also reference the build script from here: https://github.com/turanszkij/WickedEngine/blob/master/.github/workflows/build-nightly.yml#L69

If you are not using Ubuntu, then you will probably have to figure out by yourself.

You can also visit the discord server ( https://discord.gg/CFjRYmE ) where on the `linux` channel you could find some more help from people.

**Comment by spierrett** [comment]
Under Linux, the Github page instructions say you need CMake 3.7, but the CMakeList.txts requires v3.8. Can you clarify?

Also, is it that versions higher than 3.8 causes issues or can you use >=3.8?

**Comment by spierrett** [comment]
Required CMake>=3.14.

Compiled latest version from source.
