### ISSUE TITLE
Query on changing the rendering api

### ISSUE THREAD

**Issue by AbhiudayaShrivastava** [turanszkij/WickedEngine#272]
I had a query related to the engine. I have been using it since a, month and I still don't understand exactly how to change the api from dx11 to dx12 or vulkan. Please help Janos!

**Comment by turanszkij** [comment]
Hi, have you read this in the readme: https://github.com/turanszkij/WickedEngine#graphics-api
This list the command line arguments you have to provide to decide which graphics API to choose. You can provide command line arguments multiple ways:

1. If you are running from Visual Studio, go to `Project properties -> Debug -> Command argument` and type in the arguments you want
2. If you are running from a program shortcut (on Windows), you can write the command arguments after the "target" exe: 
![image](https://user-images.githubusercontent.com/12954849/122794262-56fc6c00-d2bc-11eb-80e9-e2fc45f78151.png)
3. If you are running from the command line, enter the command line arguments after the executable's name 

The command line arguments must be separated by space.

If you don't want command line arguments, you can also force the graphics API in your C++ code. Look at how MainComponent::SetWindow() creates the graphics device, and simply do the same before that function is called. (That function must be called by you, so you will know when)

**Comment by AbhiudayaShrivastava** [comment]
Ok, thanks man, u have one hell of a documentation :)
