### ISSUE TITLE
Vulkan Memory Allocator Support

### ISSUE THREAD

**Issue by spierrett** [turanszkij/WickedEngine#273]
Have you considered adding support for [Vulkan Memory Allocator](https://github.com/GPUOpen-LibrariesAndSDKs/VulkanMemoryAllocator)? It seems like it could be a huge help.

**Comment by amerkoleci** [comment]
Wicked is already using that library :)

**Comment by spierrett** [comment]
Oh. I was looking through the documentation and didn't see any mention of it. Great stuff!
