### ISSUE TITLE
cannot build on MSVC2019

### ISSUE THREAD

**Issue by PcChip** [turanszkij/WickedEngine#28]
Not sure if I'm doing something wrong,

I clicked the "Open in Visual Studio" button on the github page, it opened in MSVC, and when I try to build the solution it fails.  I can't even see the error messages because I get a "Path Too Long" exception and it blanks out the error list.  I also tried building just the "WickedEngine_Windows" and "WickedEngine_SHARED", but those fail as well  
  
would love to check this engine out, please let me know what I'm doing wrong!  
  
edit: I downloaded the zip instead of clicking "open in visual studio", then unzipped and opened the .sln  
when I try to build I can at least see the errors now, I get 1732 build errors :\

**Comment by jamesl-github** [comment]
> I clicked the "Open in Visual Studio" button on the github page

did you download all the files from the github page ?

**Comment by turanszkij** [comment]
Hi, both "download zip" and "open in visual studio" options are supposed to work. However, I haven't tried this project in Visual Studio 2019. Visual Studio 2017 is currently supported. I will look into VS 2019 when I will have the time. 
If you are interested to try the engine without building yourself, you can also download pre-built binaries of the latest version. Links are in the top of readme.

**Comment by PcChip** [comment]
Update: I got everything except the UWP to build by including the following in CommonInclude.h

#include <string>
#include <functional>
#include <memory>

very strange!

**Comment by RenderingFiend** [comment]
@PcChip I know you got it to compile, but just in-case someone else has this problem: simply install the Visual Studio 2017 toolset for VS 2019, that works fine (that's what I do).

**Comment by turanszkij** [comment]
I tried upgrading to VS 2019 and works well, except the appveyot build system cannot build the project with this error:

> The project file "WickedEngine\WickedEngine_SHARED.vcxitems" is in the ".vcproj" file format, which MSBuild no longer supports. Please convert the project by opening it in the Visual Studio IDE or running the conversion tool, or use MSBuild 3.5 or earlier to build it.

Reverting to VS 2017 for the time being

**Comment by turanszkij** [comment]
The weird thing is that the mentioned project does not participate in build, so I don't get that error. My only hope will be Appveyor support it seems: https://help.appveyor.com/discussions/problems/24543-upgrading-to-visual-studio-2019-breaks-build

**Comment by vakulich** [comment]
Hi! Yeah, I logged into Appveyor VM after build failed and here is what I found in event log of Appveyor Build Agent itself:

> Build exception: Microsoft.Build.Exceptions.InvalidProjectFileException: The  project file "WickedEngine\WickedEngine_SHARED.vcxitems" is in the ".vcproj"  file format, which MSBuild no longer supports. Please convert the project by  opening it in the Visual Studio IDE or running the conversion tool, or use  MSBuild 3.5 or earlier to build it. at  Appveyor.BuildAgent.Infrastructure.VsSolution.DiscoverProjects(String srcPath,  String projectPath) at  Appveyor.BuildAgent.BuildRunner.<Build>d__23.MoveNext() --- End of stack  trace from previous location where exception was thrown --- at  System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at  System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task  task) at Appveyor.BuildAgent.BuildRunner.<StartAsync>d__16.MoveNext()
> 

Also manual build with msbuild started very much successfully with MSVS2019 project configuration still in place:

> C:\projects\wickedengine>msbuild "C:\projects\wickedengine\WickedEngine.sln" /m /verbosity:minimal
> Microsoft (R) Build Engine version 16.1.76+g14b0a930a7 for .NET Framework
> Copyright (C) Microsoft Corporation. All rights reserved.
> 
>   compilation object save succeeded; see C:\projects\wickedengine\WickedEngine\shaders\bloomSeparatePS.cso
>   compilation object save succeeded; see C:\projects\wickedengine\WickedEngine\shaders\captureImpostorPS_albedo.cso
>   btAxisSweep3.cpp
>   btBroadphaseProxy.cpp
> ...

Looks like it is problem with Build Agent to me.. =)

**Comment by turanszkij** [comment]
I tried again recently (hoping it was somehow fixed since the previous time), but the problem still persists. I could get access to a remote desktop session to an appveyor build machine and tried to build from there, where it succeeded no problem. So it looks like appveyor specific issue, not Visual Studio.

**Comment by turanszkij** [comment]
The standard Appveyor build still doesn't work, but they suggested a reasonable workaround for my situation. That includes removing the build: section in the appveyor.yml file and instead using a custom build script section:

```
build_script:
  - msbuild "C:\projects\wickedengine\WickedEngine.sln" /m /verbosity:minimal /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
```

Maybe someone will find it useful in the future.
