### ISSUE TITLE
Screen Space Reflection performance improvements

### ISSUE THREAD

**Issue by turanszkij** [turanszkij/WickedEngine#280]
It is slower currently than ray traced reflection, but ideally it would be much faster. Commonly the SSR is a fast version of RT reflections and RT reflections would only be called on missed rays.
Need a better hierarchical traversal probably.

**Comment by turanszkij** [comment]
Thanks!

**Comment by Kliaxe** [comment]
Oh wow that was a fast reply!
At the time I first uploaded the newer solution, you mentioned the hierarchically accelerated screen space tracing. I only recently realized how truly impressive it actually is, so that is definitely happening.

**Comment by turanszkij** [comment]
This was handled in: https://github.com/turanszkij/WickedEngine/pull/395
