### ISSUE TITLE
Ambient Occlusion Improvements.

### ISSUE THREAD

**Issue by TheIronLefty** [turanszkij/WickedEngine#292]
Hi, i have been following this project for a while cause the engine seems very awesome and was wondering if it would be possible to improve the AO by using Activision's Ground Truth Ambient Occlusion (GTAO) Method.

> https://www.activision.com/cdn/research/Practical_Real_Time_Strategies_for_Accurate_Indirect_Occlusion_NEW%20VERSION_COLOR.pdf
> 
> https://iryoku.com/downloads/Practical-Realtime-Strategies-for-Accurate-Indirect-Occlusion.pdf
> 
> https://github.com/MaxwellGengYF/Unity-Ground-Truth-Ambient-Occlusion

Its code was ported to Unity 3years ago, and it works better than MSAO or SSAO.

**Comment by turanszkij** [comment]
Hi, a new AO method like that can be added to the engine in the future. I'm not sure when I would do this, but anyone else could also try it. There are a lot of example AO implementations already that can be used as a base.

**Comment by TheIronLefty** [comment]
Thanks for the response Janos, i am unfortunately inexperienced to try/do this on my own, but i have found other AO solution if it comes time for experimenting.

https://github.com/GPUOpen-Effects/FidelityFX-CACAO

**Comment by MolassesLover** [comment]
Hey, @TheIronLefty! I'll try to make time to implement both GTAO and CACAO, so I'd stay on the lookout for that if I were you.
