### ISSUE TITLE
GraphicsDevice::Map() issue with dx11

### ISSUE THREAD

**Issue by AthosArantes** [turanszkij/WickedEngine#293]
According to official documentation of [D3D11_MAP_FLAG enumeration](https://docs.microsoft.com/en-us/windows/win32/api/d3d11/ne-d3d11-d3d11_map_flag): 

> D3D11_MAP_FLAG_DO_NOT_WAIT cannot be used with D3D11_MAP_WRITE_DISCARD or D3D11_MAP_WRITE_NOOVERWRITE.

The current implementation sets D3D11_MAP_FLAG_DO_NOT_WAIT regardless of map type.
Possible fix?:

```
void GraphicsDevice_DX11::Map(const GPUResource* resource, Mapping* mapping) const
{
	...

	D3D11_MAP map_type = D3D11_MAP_READ_WRITE;
	UINT map_flags = D3D11_MAP_FLAG_DO_NOT_WAIT;
	if (mapping->_flags & Mapping::FLAG_READ)
	{
		...
	}
	else if (mapping->_flags & Mapping::FLAG_WRITE)
	{
		map_type = D3D11_MAP_WRITE_NO_OVERWRITE;
		map_flags = 0;
	}
	HRESULT hr = immediateContext->Map(internal_state->resource.Get(), 0, map_type, map_flags, &map_result);

	...
}
```

**Comment by turanszkij** [comment]
Thank you, it's fixed in https://github.com/turanszkij/WickedEngine/commit/f8c2653c260a01b455816af07a3c429c97a0b779
