### ISSUE TITLE
Linux Editor: No dialog backend available

### ISSUE THREAD

**Issue by shifttab** [turanszkij/WickedEngine#297]
When I click Load Model I get a pop-up saying No dialog backend available. Do I lack a package? perhaps gtk?
Also it segfaults when I close the editor. I have Release build though.

> Created GraphicsDevice_Vulkan
> 
> [wiInitializer] Initializing Wicked Engine, please wait...
> Version: 0.56.85
> 
> wiJobSystem Initialized with [4 cores] [3 threads]
> 
> wiFont Initialized
> wiInput Initialized
> wiLua Initialized
> wiImage Initialized
> TODO wiNetwork_Linux
> wiTextureHelper Initialized
> wiHairParticle Initialized
> wiPhysicsEngine_Bullet Initialized
> wiOcean Initialized
> wiEmittedParticle Initialized
> wiRenderer Initialized
> File not found: startup.lua
> No dialog backend available
> Segmentation fault

OS: Debian Bullseye

**Comment by turanszkij** [comment]
Probably the file dialog library doesn't support that OS. On Linux, we use this library: https://github.com/samhocevar/portable-file-dialogs

**Comment by shifttab** [comment]
It only supports KDE and GNOME.
