### ISSUE TITLE
Some hair particles rotated

### ISSUE THREAD

**Issue by wacyym** [turanszkij/WickedEngine#298]
For some reason one particle has wrong transformation, but randomness is setted to 0
![image](https://user-images.githubusercontent.com/6958185/130488207-61c1ac77-b71c-42e7-bd7d-f9e59cdc6d62.png)

Minimal reproduction project:
[hair_bug.zip](https://github.com/turanszkij/WickedEngine/files/7033722/hair_bug.zip)

**Comment by turanszkij** [comment]
Hi, the randomness value is used to randomize particle lengths, not the orientation. But I see the bug though on my side. I am working on a lot of updates in a different branch, and it doesn't occur there (a lot of hair particle system is going to be updated).

**Comment by turanszkij** [comment]
It's fixed now.
