### ISSUE TITLE
vulkan failed to submit graphics command buffer

### ISSUE THREAD

**Issue by zbzdys** [turanszkij/WickedEngine#30]
I must say your work is wonderful! I have built the engine successfully and the tests were beautiful.

When i switched the backend from default dx11 to vulkan, i got an exception:
failed to submit graphics command buffer

I have upgraded the driver to solve the extension problem, but this one seems like semaphore is used without initialization.

I learn vulkan by vulkan-totorial.com and i have some code like yours. but when the exception occurs, i find pWaitSemaphores is unreadable(file wiGraphics_Vulkan.cpp line 4535). In my tutorial sample code, this variable of structure submitinfo is readable in the vs debugger.

I build and run with Windows 10 x64, Vulkan sdk 1.1.106 and gtx 1080ti(driver version 431).

thanks!

**Comment by zbzdys** [comment]
enable debug mode, here are the messages:

[VULKAN validation layer]:  [ UNASSIGNED-CoreValidation-DrawState-InvalidImageLayout ] Object: 0x481bbf98 (Type = 6) | Submitted command buffer expects image 0xd0[../images/logo_small.png]  (subresource: aspectMask 0x1 array layer 0, mip level 6) to be in layout VK_IMAGE_LAYOUT_GENERAL--instead, current layout is VK_IMAGE_LAYOUT_TRANSFER_DST_OPTIMAL.
[VULKAN validation layer]:  [ UNASSIGNED-CoreValidation-DrawState-InvalidImageLayout ] Object: 0x481bbf98 (Type = 6) | Submitted command buffer expects image 0xd0[../images/logo_small.png]  (subresource: aspectMask 0x1 array layer 0, mip level 7) to be in layout VK_IMAGE_LAYOUT_GENERAL--instead, current layout is VK_IMAGE_LAYOUT_TRANSFER_DST_OPTIMAL.
[VULKAN validation layer]:  [ UNASSIGNED-CoreValidation-DrawState-InvalidImageLayout ] Object: 0x44bc7578 (Type = 6) | Submitted command buffer expects image 0x8f43[HELPERTEXTURE_COLOR]  (subresource: aspectMask 0x1 array layer 0, mip level 0) to be in layout VK_IMAGE_LAYOUT_GENERAL--instead, current layout is VK_IMAGE_LAYOUT_TRANSFER_DST_OPTIMAL.
[VULKAN validation layer]:  [ UNASSIGNED-CoreValidation-DrawState-InvalidImageLayout ] Object: 0x44bc7578 (Type = 6) | Submitted command buffer expects image 0x8f66  (subresource: aspectMask 0x1 array layer 0, mip level 0) to be in layout VK_IMAGE_LAYOUT_GENERAL--instead, current layout is VK_IMAGE_LAYOUT_TRANSFER_DST_OPTIMAL.
[VULKAN validation layer]:  [ UNASSIGNED-CoreValidation-DrawState-InvalidImageLayout ] Object: 0x4873e038 (Type = 6) | Submitted command buffer expects image 0x8f66  (subresource: aspectMask 0x1 array layer 0, mip level 0) to be in layout VK_IMAGE_LAYOUT_GENERAL--instead, current layout is VK_IMAGE_LAYOUT_TRANSFER_DST_OPTIMAL.
[VULKAN validation layer]:  [ UNASSIGNED-CoreValidation-DrawState-InvalidImageLayout ] Object: 0x4873e038 (Type = 6) | Submitted command buffer expects image 0xd0[../images/logo_small.png]  (subresource: aspectMask 0x1 array layer 0, mip level 0) to be in layout VK_IMAGE_LAYOUT_GENERAL--instead, current layout is VK_IMAGE_LAYOUT_TRANSFER_DST_OPTIMAL.
[VULKAN validation layer]:  [ UNASSIGNED-CoreValidation-DrawState-InvalidImageLayout ] Object: 0x4873e038 (Type = 6) | Submitted command buffer expects image 0xd0[../images/logo_small.png]  (subresource: aspectMask 0x1 array layer 0, mip level 1) to be in layout VK_IMAGE_LAYOUT_GENERAL--instead, current layout is VK_IMAGE_LAYOUT_TRANSFER_DST_OPTIMAL.
[VULKAN validation layer]:  [ UNASSIGNED-CoreValidation-DrawState-InvalidImageLayout ] Object: 0x4873e038 (Type = 6) | Submitted command buffer expects image 0xd0[../images/logo_small.png]  (subresource: aspectMask 0x1 array layer 0, mip level 2) to be in layout VK_IMAGE_LAYOUT_GENERAL--instead, current layout is VK_IMAGE_LAYOUT_TRANSFER_DST_OPTIMAL.
[VULKAN validation layer]:  [ UNASSIGNED-CoreValidation-DrawState-InvalidImageLayout ] Object: 0x4873e038 (Type = 6) | Submitted command buffer expects image 0xd0[../images/logo_small.png]  (subresource: aspectMask 0x1 array layer 0, mip level 3) to be in layout VK_IMAGE_LAYOUT_GENERAL--instead, current layout is VK_IMAGE_LAYOUT_TRANSFER_DST_OPTIMAL.
[VULKAN validation layer]:  [ UNASSIGNED-CoreValidation-DrawState-InvalidImageLayout ] Object: 0x4873e038 (Type = 6) | Submitted command buffer expects image 0xd0[../images/logo_small.png]  (subresource: aspectMask 0x1 array layer 0, mip level 4) to be in layout VK_IMAGE_LAYOUT_GENERAL--instead, current layout is VK_IMAGE_LAYOUT_TRANSFER_DST_OPTIMAL.
[VULKAN validation layer]:  [ UNASSIGNED-CoreValidation-DrawState-InvalidImageLayout ] Object: 0x4873e038 (Type = 6) | Submitted command buffer expects image 0xd0[../images/logo_small.png]  (subresource: aspectMask 0x1 array layer 0, mip level 5) to be in layout VK_IMAGE_LAYOUT_GENERAL--instead, current layout is VK_IMAGE_LAYOUT_TRANSFER_DST_OPTIMAL.
[VULKAN validation layer]:  [ UNASSIGNED-CoreValidation-DrawState-InvalidImageLayout ] Object: 0x4873e038 (Type = 6) | Submitted command buffer expects image 0xd0[../images/logo_small.png]  (subresource: aspectMask 0x1 array layer 0, mip level 6) to be in layout VK_IMAGE_LAYOUT_GENERAL--instead, current layout is VK_IMAGE_LAYOUT_TRANSFER_DST_OPTIMAL.
[VULKAN validation layer]:  [ UNASSIGNED-CoreValidation-DrawState-InvalidImageLayout ] Object: 0x4873e038 (Type = 6) | Submitted command buffer expects image 0xd0[../images/logo_small.png]  (subresource: aspectMask 0x1 array layer 0, mip level 7) to be in layout VK_IMAGE_LAYOUT_GENERAL--instead, current layout is VK_IMAGE_LAYOUT_TRANSFER_DST_OPTIMAL.
[VULKAN validation layer]:  [ UNASSIGNED-CoreValidation-DrawState-InvalidImageLayout ] Object: 0x459f92c8 (Type = 6) | Submitted command buffer expects image 0x8f43[HELPERTEXTURE_COLOR]  (subresource: aspectMask 0x1 array layer 0, mip level 0) to be in layout VK_IMAGE_LAYOUT_GENERAL--instead, current layout is VK_IMAGE_LAYOUT_TRANSFER_DST_OPTIMAL.
[VULKAN validation layer]:  [ UNASSIGNED-CoreValidation-DrawState-InvalidImageLayout ] Object: 0x459f92c8 (Type = 6) | Submitted command buffer expects image 0x8f66  (subresource: aspectMask 0x1 array layer 0, mip level 0) to be in layout VK_IMAGE_LAYOUT_GENERAL--instead, current layout is VK_IMAGE_LAYOUT_TRANSFER_DST_OPTIMAL.

**Comment by turanszkij** [comment]
Hi, thanks for reporting this. The Vulkan device is in experimental state, not stable. I am still thinking about the best way to avoid those image layout warnings. However, they should be no problem on Nvidia hardware currently, and it doesn't crash for me. 

Did you compile the vulkan shaders successfully? When the crash occurs, how many frames have passed? You can see that by inspecting GraphicsDevice::FRAMECOUNT value in the debugger.

**Comment by zbzdys** [comment]
Yes all shaders recompiled and the whole solution recompiled too. 

About several frames are processed before the crash happens, the crash happens less than one second when i hit run button with Release mode. I have upgraded my nvidia driver to 431, and the upgrade solved my extension problem. The crash stopped at vkQueueSubmit call at line 4542 and cant inspect GraphicsDevice::FRAMECOUNT.

![image](https://user-images.githubusercontent.com/18547591/61677013-8c932600-ad30-11e9-92f8-ff3a28fd155d.png)

**Comment by zbzdys** [comment]
I think i should close this issue, vulkan is in experimental state and no pushy. thanks.
