### ISSUE TITLE
Got a infinite loop when set entity parent from A to B

### ISSUE THREAD

**Issue by bitTalk1** [turanszkij/WickedEngine#301]
May be a Bug at  "++i"

void Scene::Component_Attach(...){
...
		if (hierarchy.GetCount() > 1)
		{
			for (size_t i = hierarchy.GetCount() - 1; i > 0; --i)
			{
				Entity parent_candidate_entity = hierarchy.GetEntity(i);
				for (size_t j = 0; j < i; ++j)
				{
					const HierarchyComponent& child_candidate = hierarchy[j];

					if (child_candidate.parentID == parent_candidate_entity)
					{
						hierarchy.MoveItem(i, j);

						++i; //  *****

						break;
					}
				}
			}
		}
...
}

**Comment by turanszkij** [comment]
Can you give an example where you reproduce the infinite loop?

**Comment by bitTalk1** [comment]
may be make an error operation:
setting  A's  parent to B, and then set B 's parent to A
