### ISSUE TITLE
small grid generated when  swapchain format is FORMAT_R16G16B16A16_FLOAT  in DX12

### ISSUE THREAD

**Issue by bitTalk1** [turanszkij/WickedEngine#303]
Turn  of  PostProcess's Dithering can clear these girds;

![图片](https://user-images.githubusercontent.com/11308319/132491097-5d66a4a1-9038-4323-8ae9-c09c3c391013.png)

**Comment by turanszkij** [comment]
The dithering is specifically made for HDR->LDR conversion and probably not needed if the swapchain is floating point. But I have not experience with HDR swapchain.
