### ISSUE TITLE
How to upload dynamic texture such as video frame ?

### ISSUE THREAD

**Issue by bitTalk1** [turanszkij/WickedEngine#304]

**Comment by turanszkij** [comment]
You'll need to create a texture with `Usage = USAGE_UPLOAD`, and copy linear texture data from CPU into it's mapped_data pointer. Then create a `Usage = USAGE_DEFAULT` texture that will be a GPU only texture, and do a CopyResource() from upload texture to default texture. I think it should work but there is not any actual tests or usages like this.
