### ISSUE TITLE
cling based C++ as scripting language / hot code reload

### ISSUE THREAD

**Issue by blockspacer** [turanszkij/WickedEngine#32]
cling based C++ as scripting language / hot code reload
Why? Able to run C++ script in runtime or compile it for max speed ( as in example https://github.com/derofim/cling-cmake )

> **HOT code reload**
> possible approaches:
> 
> store app state
> fix cling undo for files
> https://root-forum.cern.ch/t/loading-unloading-class-as-interpreted-macro-in-cling-multiple-times/32976/2
> 
> execute cling code to change callbacks & variables
> nested cling::Interpreter with multiple cling::MetaProcessor
> IDK how to do it, but you can create child cling::Interpreter

**Comment by turanszkij** [comment]
Hi,
Right now there is C++ for performance critical parts, and LUA scripting for fast iteration times and hot reload. Is that not sufficient for you? Currently I'm not interested in adding any complications to the build system or any dependencies. But feel free to integrate it into the engine for yourself, and if you open a pull request, I would review it and if it is not intrusive to the existing build pipeline, maybe consider adding it.

**Comment by blockspacer** [comment]
Note that Cling may be used to improve development workflow, not only as scripting engine.

Develop much faster with Cling help (dev/debug build of existing code), release same code compiled without Cling at all (release build).

**Comment by turanszkij** [comment]
Closing this as it is unlikely to be implemented. I don't want additional dependencies and complicating the build pipeline. If someone wants to have this feature, they are free to do for their project.
