### ISSUE TITLE
how to set Perspective camera  ?

### ISSUE THREAD

**Issue by bitTalk1** [turanszkij/WickedEngine#321]
I render a rectangle object,but it limited on both left and right side, and look like  a circle.

![图片](https://user-images.githubusercontent.com/11308319/134752919-b60241a3-89da-4b55-966f-0e38d0a97f6a.png)
![图片](https://user-images.githubusercontent.com/11308319/134753243-65066795-f3a0-4b87-9442-d4cd76f54727.png)

**Comment by turanszkij** [comment]
Sorry, I don't understand the problem. There is a SetCustomProjection function for the CameraComponent which might be suitable for you.

**Comment by bitTalk1** [comment]
I set CameraComponent's  Eye/At/Up directly and then call CreatePerspective  to set camera's view and project  in each frame.

problem has two:
1.  presentation zone  has been clip  on both left and right side.
2.  Rectangle Object look like a cirle.

**Comment by turanszkij** [comment]
I'm not sure about this, there is not enough information. You might need to do some graphics debugging to fix it. Check if view/projection matrix is what you expect, check viewport for the problematic render pass, check what the shader outputs. RenderDoc might help.

**Comment by turanszkij** [comment]
reopen if needed
