### ISSUE TITLE
Start wrapping wicked into blender 2.8

### ISSUE THREAD

**Issue by BluePrintRandom** [turanszkij/WickedEngine#33]
Can you set this engine up in blender 2.8 like old bge?

press P -> builds game logic and runs?

maybe use a nodal edit system to generate game logic like ue4 kinda?

**Comment by turanszkij** [comment]
Hi, there is no support for that and none planned. There was some support to export a lot of things from Blender a long time ago (nothing like game logic though) but it was dropped when a big refactoring took place.
What do you think is required to add this support and how hard would it be?

**Comment by turanszkij** [comment]
Closing this as this is not likely to be implemented.
