### ISSUE TITLE
Wicked Editor black screen DX12

### ISSUE THREAD

**Issue by PlasmaDev5** [turanszkij/WickedEngine#331]
When running Wicked under DX12 i only see a back screen. I did not have this issue in the old DX11 version and do not have this issue when running Vulkan. I am able to run many other games and engines in DX12 mode so i do not believe its an hardware issue 

![image](https://user-images.githubusercontent.com/3044415/136666787-65e87bdd-8d2c-4908-b133-828e482cd7ec.png)

System Spec:
[DxDiag.txt](https://github.com/turanszkij/WickedEngine/files/7316017/DxDiag.txt)

Full Log:
https://pastebin.com/6SD5XnBU

**Comment by dragonCASTjosh** [comment]
im on latest windows 10 and should be latest drivers

**Comment by dragonCASTjosh** [comment]
Good news, i managed to get a RenderDoc capture for this issue
https://drive.google.com/file/d/1VvagCLRRtL3WyVO7yCQboY5ZtqRL77_s/view?usp=sharing
