### ISSUE TITLE
set  render order for multi cameras

### ISSUE THREAD

**Issue by bitTalk1** [turanszkij/WickedEngine#333]
I add multi cameras to global scene , can I control the render order of those cameras ?

**Comment by turanszkij** [comment]
No, you can't specify render order like this unless you implement it with your code. As I said, to render something, you will need the RenderPath. The RenderPath has a layerMask that can be used to specify which objects will be rendered (the RenderPath layerMask and the scene entities' layerMask components will be bitwise OR-ed to determine this).

**Comment by turanszkij** [comment]
reopen if needed
