### ISSUE TITLE
multi-thread rendering

### ISSUE THREAD

**Issue by alloysystem** [turanszkij/WickedEngine#34]
do you have any plan to support multi-thread rendering just like filament.
the main thread will construct the rendering commands into one queue and the rendering back-end will fetch the command and executing the commands in another thread ?

**Comment by turanszkij** [comment]
Hi, multithreaded rendering is supported with DX11, DX12 and Vulkan by each thread recording into their own command list and then main thread submitting those onto the queue.

**Comment by turanszkij** [comment]
Feel free to reopen this if you have anything else to add, but it is unlikely that a different solution will be implemented.
