### ISSUE TITLE
Editor stuck when start up on windows

### ISSUE THREAD

**Issue by cailuming** [turanszkij/WickedEngine#346]
![image](https://user-images.githubusercontent.com/19427259/140630494-192224ad-1b76-4365-8831-e065924a7d94.png)
![image](https://user-images.githubusercontent.com/19427259/140630517-c13e940d-f2fd-4e69-acda-2a55aa8133e2.png)

**Comment by cailuming** [comment]
![image](https://user-images.githubusercontent.com/19427259/140647538-0cfff11f-59ce-4b5b-a7ff-770053360c6a.png)
![image](https://user-images.githubusercontent.com/19427259/140647624-d5c7ae92-ca7c-4a67-9bb2-783daf986875.png)
![image](https://user-images.githubusercontent.com/19427259/140647663-4b691e2b-b6e5-441d-99d8-7b8417899ed3.png)

It seems that not only the Editor, all other module projects have the similar problem but a little different

**Comment by cailuming** [comment]
![image](https://user-images.githubusercontent.com/19427259/140647995-3ae7644d-8fde-4991-9152-82cf28c7a83c.png)
Device has been suspended, my card is GTX1060

**Comment by turanszkij** [comment]
Thanks. Unfortunately this is not giving me a complete idea what went wrong. Could you also:
- post the callstack
- add `debugdevice` in the command line arguments, and when the crash happens , post the console log (in text format)

**Comment by cailuming** [comment]
[Editor_debugDevice_log.txt](https://github.com/turanszkij/WickedEngine/files/7492421/Editor_debugDevice_log.txt)
[Editor_vulkan_log.txt](https://github.com/turanszkij/WickedEngine/files/7492426/Editor_vulkan_log.txt)
![image](https://user-images.githubusercontent.com/19427259/140648565-8d7ddff6-9d7c-49fa-b803-3f7661a20df2.png)

**Comment by cailuming** [comment]
![image](https://user-images.githubusercontent.com/19427259/140648863-342d7ee6-71f2-43e9-b62a-00f96217242f.png)
callstack

**Comment by turanszkij** [comment]
Thanks for giving me the details. I can't see the reason for dx12 failure unfortunately. However, I find it strange that vulkan failed on checking descriptorIndexing feature. According to Vulkan hardware database, the GTX 1060 graphics card supports that feature: https://vulkan.gpuinfo.org/displayreport.php?id=12836#features_core_12
Are you using the latest graphics drivers?

**Comment by cailuming** [comment]
Thanks,I think you are right, it works fine when I update my drivers to the latest version,  what new features has been added?
![image](https://user-images.githubusercontent.com/19427259/140650201-d38f8a1e-9ac2-4562-9a2b-c8278f816674.png)

**Comment by turanszkij** [comment]
Great! It depends on what was your last version. The biggest change recently was removing DX11 a while ago, and modernizing the shaders to take advantage of dx12 and vulkan more.
