### ISSUE TITLE
SDL resizable windows

### ISSUE THREAD

**Issue by portaloffreedom** [turanszkij/WickedEngine#349]
SDL build does not allow for a resizable window at the moment

**Comment by turanszkij** [comment]
The windows version handles the windows resize (and display dpi change) OS event like this:
```cpp
case WM_SIZE:
case WM_DPICHANGED:
	if(editor.is_window_active)
		editor.SetWindow(hWnd);
break;
```
So it only needs to call `MainComponent::SetWindow()` again and after that the engine will detect automatically whatever resources it needs to resize.

**Comment by portaloffreedom** [comment]
Thanks! This is very helpful!
