### ISSUE TITLE
General Puzzles V2

### ISSUE THREAD

**Issue by cailuming** [turanszkij/WickedEngine#353]
Hi there, How can I get the texture of final RenderTarget after postprocessing, I need draw the texture on Imgui::Image

**Comment by turanszkij** [comment]
If you need the 3D scene, use `RenderPath3D::GetLastPostprocessRT()` or `RenderPath2D::GetRenderResult()` if you need the 2D overlay. These are combined in the `Compose()` straight to the swapchain output, so if you need both combined, you need to render the 2D overlay on top of the 3D scene yourself into a texture.

**Comment by cailuming** [comment]
Thanks a lot

**Comment by cailuming** [comment]
![image](https://user-images.githubusercontent.com/19427259/140944617-ee6bf710-68ff-484b-bd2c-4cfa35baae53.png)
![image](https://user-images.githubusercontent.com/19427259/140944733-f01189b3-a6db-4e35-993d-f8521418403d.png)
It's illegal to access the pointer when "m_pixels" is null. I found that the texture I got from "GetLastPostprocessRT()" shows black in Imgui::Image , so I decide to save the texture to file for sekking the reason, But I also failed to save the texture.

**Comment by cailuming** [comment]
![image](https://user-images.githubusercontent.com/19427259/140946060-4146b08b-dcb9-48e0-8277-7cf81ef8e2f7.png)
Here is what I did in update function

**Comment by cailuming** [comment]
![image](https://user-images.githubusercontent.com/19427259/140947915-b5542071-6112-42b6-b22b-0efccbab6764.png)
When I modify it to this , It works fine, But I don't know whether it could disturb other system

**Comment by turanszkij** [comment]
I added support for additional formats for texture saving in this commit: ddb22482b8f87c473f03dfe9948403cf962ee8c1 
The new supported formats are: `FORMAT_R16G16B16A16_FLOAT` and `FORMAT_R11G11B10_FLOAT` which are used commonly in render paths.

**Comment by cailuming** [comment]
![image](https://user-images.githubusercontent.com/19427259/141240935-f9b5928e-0bd9-4440-8e01-fd2e2a938323.png)
the format of texture from RenderPath3D is FORMAT_R11G11B10_FLOAT, But as I tested, Imgui::Image only support FORMAT_R8G8B8A8_UNORM ,maybe.  So is there some way to convert FORMAT_R11G11B10_FLOAT to FORMAT_R8G8B8A8_UNORM?

**Comment by turanszkij** [comment]
`wiRenderer::CopyTexture2D()` can be used to convert between texture formats. It uses compute shader, so cannot be inside a render pass. An other method would be to draw a full screen texture to a render pass. But I doubt this would be the problem. I was thinking that maybe the problem is that this texture format doesn't have alpha, so it's recognized as fully transparent. The wiImage::Draw() for example could be used to draw a transparent texture as opaque by setting opaque blend mode.

**Comment by cailuming** [comment]
I found that there is not Render To Texture related function or set Render Target related something

**Comment by turanszkij** [comment]
This would be the simplest way of drawing a full screen image and force it to be opaque inside a render pass (using pixel shader):
```cpp
wiImageParams fx;
fx.enableFullScreen(); // this is the most optimal setting for full screen image
fx.blendFlag = BLENDMODE_OPAQUE; // this will make it not use the texture's alpha, result will be always non-transparent
wiImage::Draw(&texture, fx, cmd);
```

**Comment by cailuming** [comment]
Thanks for details, I created a new renderpass,   using the depth texture of Renderpath3D and myself created Render target color texture as attachments. And then I Call wiImage::draw as you said,still get black. I suspect the Imgui isn't integrated perfectly to wi Engine, Or I need do more test to make it to work

**Comment by cailuming** [comment]
![image](https://user-images.githubusercontent.com/19427259/141610371-07600842-7fcf-4248-8272-6dd6f1c0a4b3.png)
God,finally, after many times painfull try, I got this. All is my fault, it's a reason of uv offset , thank you so much again!

**Comment by cailuming** [comment]
Hi, how can I add a second or multi cameras to scene and switch among them?

**Comment by turanszkij** [comment]
You can add multiple camera proxies to the `Scene::cameras`. You can one active camera in the `RenderPath3D::camera` which is a pointer to a single `CameraComponent`. It is best if your main camera is not part of the Scene, but your custom user code, or you can also use the global camera that you can get from `wiScene::GetCamera()`. But if you want to snap the main camera to a scene camera, you can just copy the main camera from scene camera, or follow it's transform, etc. It's up to you really.

This lua script for example animates the main camera between several different cameras in the scene: https://github.com/turanszkij/WickedEngine/blob/master/Content/scripts/camera_animation_clamped.lua

**Comment by cailuming** [comment]
Nice day, I'm confused about rendering a scene to texture(RenderTexture) using one camera, and rendering the output texture to the scene, just like a TV screen in the scene . I have tried to use two RenderPath3D, one for output texture, another is for rendering the texture to TV screen in the scene.  but failed to run. Need I override the RenderPath and implement myself another one?

**Comment by turanszkij** [comment]
This is quite advanced and there is no example for this, so you'll have to experiment. You can use multiple render paths, each having it's own camera, scene and rendering resolution, and get their final texture. 

But you can also implement a custom render to texture inside the renderpath too. For that, you can look at how the planar reflections are implemented, which is an effect that renders the scene from an other camera (but in a simpler way, without post processing and screen space effects).

For implementing something advanced like this and things don't work, you will need to use a graphics debugger.

**Comment by cailuming** [comment]
Thanks,I will do more experiments

**Comment by cailuming** [comment]
Hi, I met some problems with below image, and have no idea what's going on,
![image](https://user-images.githubusercontent.com/19427259/144731581-1a48000c-10d9-4346-9b25-003a2088909d.png)

lot's of random white or black squares

**Comment by cailuming** [comment]
Hi, I found the collision mode both Triangle Mesh and Convex Hull for terrain would be crash,
![image](https://user-images.githubusercontent.com/19427259/156565377-c3a2e0e9-1dac-43aa-8221-12932b545135.png)
![image](https://user-images.githubusercontent.com/19427259/156565553-ff4e5517-b4a4-4369-a93f-b0d36fd3258d.png)
![image](https://user-images.githubusercontent.com/19427259/156565623-7717452d-5a47-4e46-bb17-84c036d69891.png)
and another issue , when I slide the slider, it will complain as following
![image](https://user-images.githubusercontent.com/19427259/156566270-eed532de-c3bf-4fcf-bc8f-48e9f61bf74f.png)
![image](https://user-images.githubusercontent.com/19427259/156566339-4839c2c2-878f-4d9b-8c8c-8d89aa21cc8a.png)
by the way, displacement for terrain not work

**Comment by turanszkij** [comment]
Hi, in the first case it looks like you don't have the object selected, but the light, that's why it's failing "no MeshComponent provided" assert. In the second case I don't know.

About the terrain displacement, it looks like terrain currently doesn't support tessellation (when "terrain" is enabled for the MeshComponent). I will implement this later. You can also disable "terrain" feature of the mesh in the editor Mesh window. It will disable material blending, but it will still have the same geometry and tessellation support.

**Comment by cailuming** [comment]
Still problems, I'm sure I have selected the terrain object by right click this time , but when I chose the ConvexHull mode, It will stuck forever until I kill the process.
![image](https://user-images.githubusercontent.com/19427259/157640619-1079d2bd-2602-4493-92b2-dfb4e7b091d6.png)

Second, When creating the terrain , I clicked create button, and shows the dialog right , watch the resolution and height values, which are default value, In this case, I slide the  Y slider , It will crash.

Or I missed something somewhere, sorry for that

**Comment by turanszkij** [comment]
This commit fixes the Y slider bug and a problem with "triangle mesh" type physics: https://github.com/turanszkij/WickedEngine/commit/313fd0cd439603262d2f62fdf88b1e8e98462c62

The convex hull physics hanging issue didn't occur for me. It is pretty slow in Debug build to calculate a convex hull, but it does finish. It is much faster in Release build. By the way, for a terrain (or any concave mesh) the convex hull physics collider will not work very well.

**Comment by cailuming** [comment]
Fine now,though,  another question about physics system, when I load a model in such as a cone, and change the object collision mode to Convex Hull or triangle mesh , and toggle the simulation on, but nothing happened.
![image](https://user-images.githubusercontent.com/19427259/157798705-df94a7c1-f150-431f-af5f-655c37d15b4f.png)
But, when I load straightly the PhysicsTest.wiscene in , It works well, and when I change one of those shape collision mode to triangle mesh, the one I changed would stop dropping

**Comment by cailuming** [comment]
Hi there, I have some problems
1. How should I do to enbale the pathtracing denoiser
![image](https://user-images.githubusercontent.com/19427259/158121415-84783dd4-6b1a-418c-83ab-9543c2c217a0.png)
2. When I put the light inside the bunny, almost no light get out, the bunny is entirely transmited
3. How should I change the particle color during lifetime , for example, when the particle spawns, it will be red, and dies with blue 
4. particles in path tracing mode not work or I encountered when delete an emitter causing crash

**Comment by cailuming** [comment]
Thanks always, I imagine the trail flame of  aircraft, the color may be white to blue or to other color gradient

**Comment by cailuming** [comment]
![image](https://user-images.githubusercontent.com/19427259/158148803-fb1242e1-246e-4f43-a318-145612538e86.png)
it's gorgeous，I builded in release mode , But debug mode still not support, I'm trying to make it support too

**Comment by turanszkij** [comment]
Nice, if you want this in Debug mode, you will also need to put the lib and dlls in similar directories, just replacing `Release` with `Debug` in paths.

> Thanks always, I imagine the trail flame of aircraft, the color may be white to blue or to other color gradient

Yeah this is a good idea and wouldn't be hard to implement, just not sure what's the best way to allow configuring this in the emitter. 
An other way to do it would be to use two emitters, one orange for the main flame and one blue for the tail of the flames that lives a bit longer.

**Comment by cailuming** [comment]
Hi, I need help when I'm trying to make a triangle or some other polygon manually, the case is following
TestCode:
       ```
 Entity object = scene::GetScene().Entity_CreateObject("TestObject");
	Entity light = scene::GetScene().Entity_CreateLight("TestLight");
	Entity meshID = scene::GetScene().Entity_CreateMesh("TestMesh");
	ObjectComponent &obj = *scene::GetScene().objects.GetComponent(object);
	obj.meshID = meshID;
	LightComponent* lightComp = scene::GetScene().lights.GetComponent(light);
	lightComp->energy = 100;
	MeshComponent *mesh = scene::GetScene().meshes.GetComponent(meshID);

	mesh->SetRenderable(true);
	mesh->subsets.emplace_back();

	mesh->vertex_positions.resize(3);
	mesh->vertex_normals.resize(3);
	mesh->vertex_colors.resize(3);
	mesh->vertex_uvset_0.resize(3);
	mesh->vertex_uvset_1.resize(3);
	mesh->vertex_atlas.resize(3);
	mesh->indices.resize(3);
	mesh->vertex_positions[0] = XMFLOAT3(0,1,0);
	mesh->vertex_positions[1] = XMFLOAT3(1, 0, 0);
	mesh->vertex_positions[2] = XMFLOAT3(-1, 0, 0);
	mesh->vertex_normals[0] = XMFLOAT3(1, 1, -1);
	mesh->vertex_normals[1] = XMFLOAT3(1, 1, -1);
	mesh->vertex_normals[2] = XMFLOAT3(1, 1, -1);

	mesh->vertex_colors[0] = wi::Color::Red().rgba;
	mesh->vertex_colors[1] = wi::Color::Blue().rgba;
	mesh->vertex_colors[2] = wi::Color::Green().rgba;

	mesh->indices[0] = 0;
	mesh->indices[1] = 1;
	mesh->indices[2] = 2;

	mesh->vertex_uvset_0[0] = XMFLOAT2(0,0);
	mesh->vertex_uvset_0[1] = XMFLOAT2(0, 1);
	mesh->vertex_uvset_0[2] = XMFLOAT2(1, 1);
	
	mesh->subsets.back().indexCount = (uint32_t)mesh->indices.size();

	mesh->subsets.back().materialID = scene::GetScene().Entity_CreateMaterial("Material");
	mesh->subsets.back().indexOffset = 0;
	MaterialComponent* material = scene::GetScene().materials.GetComponent(mesh->subsets.back().materialID);
	material->SetUseVertexColors(true);
	material->baseColor = Color::Yellow();
	material->shaderType = material->SHADERTYPE_PBR;
	mesh->ComputeNormals(MeshComponent::COMPUTE_NORMALS_SMOOTH_FAST);
	 
	mesh->CreateRenderData();
```
But it shows nothing but black,I'm sure I have add light and some other prerequirements,and it really work when I load some model.
![image](https://user-images.githubusercontent.com/19427259/160962769-b3e3236d-f4e3-4784-9917-aa1bc2581a2e.png)

**Comment by turanszkij** [comment]
Thanks for posting the code, it was easy for me to try it out. And in fact it works, I get this triangle:
![image](https://user-images.githubusercontent.com/12954849/161023527-39456107-cb82-47e5-852c-f506b1f8fc6e.png)
But I had to go behind it, because the culling of it is reversed. This is because the indexing is the reverse order. To fix it, you can reorder the indices like this for example:
```cpp
mesh->indices[0] = 0;
mesh->indices[1] = 2;
mesh->indices[2] = 1;
```
Or you can also call the `mesh->FlipCulling();` to reverse the index winding order.

**Comment by cailuming** [comment]
Hi,I met some problems, This is rendered by blender in Eevee, 
![image](https://user-images.githubusercontent.com/19427259/162351169-ca89fc0f-5471-428a-b322-63cf1a8a069a.png)
and this is rendered by our engine
![image](https://user-images.githubusercontent.com/19427259/162351079-7ad6c883-fdbf-4d4c-af33-ef35308d5ae7.png)
what makes me confused is that the point light and shadow is not so much contract and the color on the top of helmet behaves green , but the original color should tends more white and bright

**Comment by turanszkij** [comment]
1) I clicked on the ground mesh and in the mesh window Flip Normals button
2) I added an Environmnet probe with the EnvProbe Button -> Put
Result: 
![image](https://user-images.githubusercontent.com/12954849/162374677-ea548296-d8c9-42f8-bbcb-a047e37da77b.png)
The helmet models have high metalness, so they don't have much color of their own, because they will take more of the environment color. In a black environment, their color will be mostly black too.

**Comment by turanszkij** [comment]
And this is their helmet with metalness = 0 (setin Material window)
![image](https://user-images.githubusercontent.com/12954849/162375094-9552528f-6b5d-4d9b-b676-1ffedc1295cf.png)

**Comment by cailuming** [comment]
Thanks, may be I missed some settings and difference between blender eevee and WickedEngine, I'll do more experence to make it looks similar
