### ISSUE TITLE
[Question]Client script compilation

### ISSUE THREAD

**Issue by rikseth** [turanszkij/WickedEngine#37]
I have used game engines like unreal engine and cry engine. There the editor compiles the codes while the editor and engine is running. How does they load the user written game scripts at runtime?

**Comment by turanszkij** [comment]
I don't know how those engines do it. In this engine, script reloading can be done at runtime with LUA scripts. It's only a matter of loading text files and let the LUA virtual machine compile them.

**Comment by turanszkij** [comment]
If you want to continue discussion, feel free to reopen this.
