### ISSUE TITLE
one  issue in findQueueFamilies

### ISSUE THREAD

**Issue by alloysystem** [turanszkij/WickedEngine#38]
QueueFamilyIndices findQueueFamilies(VkPhysicalDevice device, VkSurfaceKHR surface) {
		QueueFamilyIndices indices;
--------------------------------------------
issue
			if (queueFamily.queueCount > 0 && **queueFamily.queueFlags == VK_QUEUE_TRANSFER_BIT**) {
				indices.copyFamily = i;
			}
--------------------------------------------------
fix
			if (queueFamily.queueCount > 0 && **queueFamily.queueFlags & VK_QUEUE_TRANSFER_BIT**) {
				indices.copyFamily = i;
			}
		return indices;
	}

**Comment by turanszkij** [comment]
Hi,
This is not a bug, for copy family I want to specifically select a queue that is dedicated queue for transfer. Currently, GPU without dedicated transfer queue is not supported.

**Comment by alloysystem** [comment]
ok, I get it. many graphics card do not have dedicated transfer queue.

**Comment by turanszkij** [comment]
I will look into how to best handle GPU without dedicated transfer queue at some point, thanks for brining it to my attention.

**Comment by turanszkij** [comment]
Implemented a better way to select transfer queue so it doesn't need to be dedicated. Although it will prefer the dedicated queue when there is one available.
