### ISSUE TITLE
SPH viscosity smoothing kernel correctness

### ISSUE THREAD

**Issue by yhamdoud** [turanszkij/WickedEngine#383]
Hi,

I think that the viscosity smoothing kernel is erroneously applied instead of the Laplacian of this smoothing kernel in the SPH fluid simulation. I'm far from being an expert on fluid dynamics, so it would be nice if someone could confirm my findings.

I came across [a blog post on WickedEngine's SPH implementation](https://wickedengine.net/2018/05/21/scalabe-gpu-fluid-simulation/) when researching the topic. Something caught my eye in the section covering the viscosity force term computation. In the pseudocode, the smoothing kernel W is calculated and applied as follows:
```glsl
const float W = -(r3 / (2 * h3)) + (r2 / h2) + (h / (2 * r)) - 1;
particleA.force2 += (particleB.mass / particleA.mass) * (1.0f / particleB.density) * (particleB.velocity - particleA.velocity) * W * rNorm;
```
However, if we look at [the article that the post references](http://rlguy.com/sphfluidsim/), it calls for applying the Laplacian of the given smoothing kernel. I had a look at the accompanying source code of the article and indeed, [it seems to calculate and use the constant part of the Laplacian of W.](https://github.com/rlguy/SPHFluidSim/blob/07548003daf6ebcc3020f6fed37e30981d9f7e81/src/sphfluidsimulation.cpp#L71).

This is also in line with one of the papers I looked at, [Particle-Based Fluid Simulation for Interactive Applications](https://matthias-research.github.io/pages/publications/sca03.pdf):

![image](https://user-images.githubusercontent.com/18217298/147994174-806f8218-7407-4e19-92a6-470a3e12de99.png)

The relevant code doesn't seem to be changed since the blog was post was authored:
https://github.com/turanszkij/WickedEngine/blob/dfcdbdd40c5ff8d5425063258dbef740150cbd7e/WickedEngine/shaders/emittedparticle_sphforceCS.hlsl#L119-L120
I've changed it and loaded the emitter_fluid_50k scene and the simulation seems to be a bit more stable now. This is after tweaking the emitter settings a bit, viscosity in particular. I'm not sure if there is a better test scene, since I haven't actively used WickedEngine before.

Thanks for your time, I hope I'm not completely of the mark here!

**Comment by turanszkij** [comment]
That part is computed here: 
https://github.com/turanszkij/WickedEngine/blob/dfcdbdd40c5ff8d5425063258dbef740150cbd7e/WickedEngine/shaders/emittedparticle_sphforceCS.hlsl#L112
spiky constant is precomputed on CPU: https://github.com/turanszkij/WickedEngine/blob/master/WickedEngine/wiEmittedParticle.cpp#L438

Or am I missing your point? What was your change?

**Comment by yhamdoud** [comment]
> That part is computed here:
> 
> https://github.com/turanszkij/WickedEngine/blob/dfcdbdd40c5ff8d5425063258dbef740150cbd7e/WickedEngine/shaders/emittedparticle_sphforceCS.hlsl#L112
> 
> spiky constant is precomputed on CPU: https://github.com/turanszkij/WickedEngine/blob/master/WickedEngine/wiEmittedParticle.cpp#L438
> 
> Or am I missing your point? What was your change?

That's the gradient of the the spiky kernel, used for smoothing the pressure force calculation. The constant part of the spiky gradient and the Laplacian of the viscosity kernel are similar except for a sign change. Here are the changes #384. I didn't add any changes to the current emitter examples, not sure if that's desirable. If you want to get a stable simulation you need to lower the default viscosity value a bit.

**Comment by turanszkij** [comment]
Thanks, I'll need to take some time to revisit this.

**Comment by turanszkij** [comment]
Thanks for the contribution, your modifications are merged.

**Comment by turanszkij** [comment]
Updated the emitter_fluid asset and the viscosity slider's default range in editor: https://github.com/turanszkij/WickedEngine/commit/0355104b8b84cb78560070abd398c82b833aa355
I think this can be closed now, but feel free to reopen if you have anything else to add.

**Comment by yhamdoud** [comment]
> Thanks for the contribution, your modifications are merged.

My pleasure :slightly_smiling_face:
