### ISSUE TITLE
[BUG] Duplicating a skeletal model in the editor makes incorrect transformations.

### ISSUE THREAD

**Issue by BenjaminGu** [turanszkij/WickedEngine#389]
![image](https://user-images.githubusercontent.com/16999381/151127140-e9c24420-e8c0-4590-892c-5dcefef3875e.png)

**Comment by turanszkij** [comment]
Hi, thanks for reporting it. If you select the parent entity of the whole model, you can duplicate it correctly. You can do that in the Scene graph view, for this model, it is an unnamed entity, so it will be displayed with numbers only.

I will try to fix the incorrect transform of duplicating the object itself, it looks like a scaling issue related to GLTF importing.

**Comment by turanszkij** [comment]
The problem: gltf model is scaled with -1 on Z axis to transform from right handed to left handed system. Previously, this parenting info was lost when duplicating child. Now it is retained correctly in the above fix.
