### ISSUE TITLE
Vulkan backend is not work

### ISSUE THREAD

**Issue by alloysystem** [turanszkij/WickedEngine#39]
Vulkan backend is not work

**Comment by turanszkij** [comment]
What problem are you getting? Right now not every GPU will be supported with Vulkan. High end GPU from Nvidia should be working, I can't test on others, sorry.

**Comment by alloysystem** [comment]
Thanks for your replying. Loading shader exception as my graphics card is rx580.

**Comment by turanszkij** [comment]
Could you provide more info about the exception? Did you build SPIRV shaders beforehand?

**Comment by turanszkij** [comment]
I checked latest version, Vulkan works for me. You could also try adding:
`debugdevice`
To the startup arguments list and run with the debugger attached. What error messages do you get on the Visual Studio output window?

**Comment by turanszkij** [comment]
Feel free to reopen if you are still having issues.
