### ISSUE TITLE
Odd size DDS with mipmaps loaded incorrectly

### ISSUE THREAD

**Issue by dwlcj** [turanszkij/WickedEngine#40]
Hello Turánszki János!
I noticed if dds image Size Not Square Will display incorrectly.

**Comment by dwlcj** [comment]
dds is error：
![dds_error](https://user-images.githubusercontent.com/252897/66694598-9e5ce780-ece7-11e9-86e9-bb45b90c07b1.png)
png is ok！
![png_ok](https://user-images.githubusercontent.com/252897/66694601-a583f580-ece7-11e9-919b-e5cc62b52141.png)
image：
![961506e77970ccc93502cb0a6bb5b0bb](https://user-images.githubusercontent.com/252897/66694608-cba99580-ece7-11e9-817a-c48c4ce3d468.png)

**Comment by turanszkij** [comment]
Hi, thanks for reporting. It must be an issue with mip-mapped DDS that is not square size and block compressed. Please use square size texture if you are using block compressed DDS format (BC1, BC2, BC3, etc) with mipmaps. I'm not sure I can fix the dds loader to support this corner case and if it's worth it.

**Comment by dwlcj** [comment]
Alright.

**Comment by PaulSJ** [comment]
@turanszkij Check wiResourceManager.cpp around line 109, width/height are swapped

**Comment by turanszkij** [comment]
@PaulSJ Thank you very much, it's fixed now. What an embarrassing bug.
