### ISSUE TITLE
improve in-editor text boxes

### ISSUE THREAD

**Issue by ghost** [turanszkij/WickedEngine#411]
Specifically allow moving in-between letters by using the arrow keys or mouse.

**Comment by turanszkij** [comment]
Yes, this would be nice, I'll link it to the other GUI improvements issue: #51

**Comment by turanszkij** [comment]
Done https://github.com/turanszkij/WickedEngine/commit/90fbbba9bada3f7c049c8d17b545a05c51ec7324
