### ISSUE TITLE
Linux Paint Tool Doesn’t paint textures

### ISSUE THREAD

**Issue by EvanNibbe** [turanszkij/WickedEngine#417]
When I open a .obj file, I can see the structure just fine, but if I right click on the terrain, then press “Paint tool”, then change the color to red, then draw over the texture, nothing happens. I can use Mode: Vertexcolor, which then makes colors appear centered on the vertices.

My current setup is Ubuntu 20.04.3 LTS, with the X11 windowing system, 31.3 GB Ram, Vulkan 1.3.211.0

I have not run any C++ or LUA code in your system yet.

Also: feature recommendation: please add the ability to load a .png image as the texture in Material. Currently, when pressing on the default single color to replace it, no file type is ever recognized as the thing to use.

**Comment by turanszkij** [comment]
Confirmed that the file dialog file type filtering is broken on Linux, will be fixed.

**Comment by turanszkij** [comment]
The file dialog should be fixed in this commit: https://github.com/turanszkij/WickedEngine/commit/8973a39c5d8d68d48d803ecd36ddec5d4acc5e7f
Main problem was that it didn't handle lowercase extensions on linux, sorry for that.

**Comment by EvanNibbe** [comment]
Also, what does it mean on cmake where it says 
OpenImageDenoise not found, it will be disabled.

?
//I realize this is a non-fatal error since it compiles anyways with make, but will that mean the image quality is lower?

**Comment by EvanNibbe** [comment]
Thanks for fixing the issue.
![Uploading image.jpg…]()

**Comment by MolassesLover** [comment]
`OpenImageDenoise not found, it will be disabled.` means that the [OpenImageDenoise](https://www.openimagedenoise.org/) binaries haven't been found by Wicked Engine, disabling denoising. This affects rendering quality drastically in some occasions.

**Comment by turanszkij** [comment]
OpenImageDenoise is completely optional. If available, it will be used to improve final quality of path tracing and lightmap renders.
