### ISSUE TITLE
Path Tracing Render Denoise

### ISSUE THREAD

**Issue by dwlcj** [turanszkij/WickedEngine#42]
Hi!
Path Tracing Render is amazing.
But I found that there were too many noise points where the light was not enough.
Is there any way to reduce noise?
in addition
Can these two libraries help:
1、NVIDIA OptiX Denoise Library
2、Intel Open Image Denoise Library

**Comment by turanszkij** [comment]
Hi, you are right, a denoiser would surely help. Those are two libraries that are probably very good, but not designed for real time denoising. Those can be integrated into any application. Denoising library won't be integrated into the engine, but writing a real time denoiser might be happening at some point in the future.

As a side note, if you are not getting enough light in some spots, you can increase the amount of bounces in the Renderer settings with "Raytrace bounces" slider. This will slow down the path tracing even more.

**Comment by turanszkij** [comment]
This was implemented since, the [Open Image Denoise](https://github.com/OpenImageDenoise/oidn) library can be added to the project and it will be enabled automatically after rebuilding.
