### ISSUE TITLE
Water reflection bug

### ISSUE THREAD

**Issue by Cop46** [turanszkij/WickedEngine#423]
Hello,
The water reflection appear to be broken in the 0.60.61 version.

![Reflection](https://user-images.githubusercontent.com/32778861/166100312-44ccfca1-bf70-49fe-bb5e-525bacb436c0.jpg)
.

**Comment by turanszkij** [comment]
This can occur when your water mesh is not a plane, because these planar reflections can only be used for planar surfaces. Try the example water_test.wiscene or water_plane.wiscene. The reflections look correct on those.

**Comment by tictech1970** [comment]
What version or fork of Wicked Engine does that editor have, it looks incredible, it is very necessary for usability, where can I download it?

**Comment by Cop46** [comment]
> What version or fork of Wicked Engine does that editor have, it looks incredible, it is very necessary for usability, where can I download it?
This is a project I made on wicked with imgui. For now is not released. When it's finiesh I think I can made a special version for wicked's users :)

**Comment by tictech1970** [comment]
Awesome.

**Comment by turanszkij** [comment]
The issue was that the water mesh was not a plane, I think it can be closed.
