### ISSUE TITLE
Snow storm with particle systems example not found.

### ISSUE THREAD

**Issue by tictech1970** [turanszkij/WickedEngine#428]
Where is the demo file for the Snow storm with particle systems seen on the index site and in the video?

https://www.youtube.com/watch?v=dZ9l5O90zpM

**Comment by turanszkij** [comment]
It's not part of the sample models on github, but on Patreon: https://www.patreon.com/posts/60351808 (everyone can download it)

**Comment by tictech1970** [comment]
Thanks, is awesome.
