### ISSUE TITLE
Path Tracing Render material

### ISSUE THREAD

**Issue by dwlcj** [turanszkij/WickedEngine#43]
Hi!
material "Cast Shadow" Attribute don't work in Path Tracing Render.
and how to Making a glass material.
Thanks!

**Comment by turanszkij** [comment]
Hi, cast shadow will not work in path tracing, everything is supposed to always cast shadow. Cast shadow toggle is supposed to be a performance feature in rasterized mode, but it doesn't matter in path tracing for performance.

You can make glass material by decreasing a mterial's "Alpha". You can increase the material's "Refraction index" to make it distort light for a glass like effect. In non-path tracing mode, you will also need to set the material's blend mode to "Alpha" for example to make transparency work.

**Comment by dwlcj** [comment]
Thanks!

**Comment by turanszkij** [comment]
Feel free to reopen if you have anything else to add.
