### ISSUE TITLE
[bug] Far plane assertion failed in the Editor

### ISSUE THREAD

**Issue by Sororfortuna** [turanszkij/WickedEngine#432]
Probably a simple bug to fix, bringing down the far plane slider to it's minimum
will cause assertion failure.
![image](https://user-images.githubusercontent.com/18470725/167238457-56de90d0-c534-405e-8ac1-8a11f06fa423.png)

**Comment by turanszkij** [comment]
Thanks for reporting this, I increased the min value of the slider.
