### ISSUE TITLE
32-Bit and size_t

### ISSUE THREAD

**Issue by RobertMtx** [turanszkij/WickedEngine#434]
I'm curious to know how difficult it would be to get things working in 32-bit. I generated a 32-bit project successfully, but there are several VS compile errors, due to the way `size_t `changes sizes. I'm assuming there will be other similar issues - especially with any type of data streaming (model loading). Is there any information about making the latest WickedEngine compile and work in 32-bit mode?

Thanks! This project looks really impressive! I've been building a game project for over 15 years, and upgrading to 64-bit would be a bit of a nightmare (I've made attempts, but just too much code). Anyway, I'd love to get WickedEngine integrated into it, if possible.

**Comment by turanszkij** [comment]
I don't know honestly, not something I would like to do. It did support 32 bit and 64 bit some time ago, so things like model loading should be fine. I think DX12 API might have a problem with 32 bits, and other parts of the code that failed to compile for you.

**Comment by RobertMtx** [comment]
Thanks for the information. I may need to look at my project again and see if I can work my way up to 64 bit. Maybe a little at a time. It makes more sense for me to go forward than for you to go backward.

Its those type padding warnings that bother me the most. The compiler throws extra bytes all over the place - even into simple POD types - which means if I happened to stream any of those simple types to file without parsing every member, or recording the size of the struct, the stream offset will get knocked out of alignment.

My engine was started so long ago, it still has components of DirectX 9 in it. I'm pretty sure I will have to get rid of those if I go to 64-bit. That is the plan anyway, but I hate making huge changes all at once like that - without being able to test as I go, etc.

**Comment by turanszkij** [comment]
The serialization explicitly uses 64 bit types to remain compatible across 32/64 bits, so things like reading files that were created by the engine should be portable.
