### ISSUE TITLE
[Feature Request] Triplanar mapping

### ISSUE THREAD

**Issue by Cop46** [turanszkij/WickedEngine#439]
Hello,
Have you planned to add support of triplanar texture mapping in world coord to material ?
Thanks

**Comment by turanszkij** [comment]
I tried this some time ago, when there was a separate terrain shader. It was too much work to support it for all shader types, texture slots, render effects.

Now this could be maybe supported more efficiently by baking it into the terrain virtual textures.

**Comment by turanszkij** [comment]
This probably won't be supported out of the box.
