### ISSUE TITLE
UI system

### ISSUE THREAD

**Issue by dwlcj** [turanszkij/WickedEngine#44]
I found that the wiGUI is still very simple at present, and many functions are lost.
Is it possible to integrate external UI engines: for example, imgui...
Or there is another development plan for UI system.

**Comment by turanszkij** [comment]
Hi, development plan is to improve the wiGUI system. If you prefer to use imgui, you will have to integrate it for your application. It is possible to do by overriding RenderPath::Update(), Render() and Compose() functions where you can implement custom rendering logic.

**Comment by turanszkij** [comment]
I will close this feature request because it won't be implemented. If you decide to integrate imgui for yourself and have any problems, feel free to reach out.
