### ISSUE TITLE
Windows/Sprites: styling improvements

### ISSUE THREAD

**Issue by Sororfortuna** [turanszkij/WickedEngine#441]
I feel the interface system may benefit from a few enhancements to increase usability and the breadth of designs that can be achieved in a less time-consuming manner if a few of these features were to be implemented:

- Shadow property w/ base color, directional inset/offset & blur radius
- Border outline     (this could be implemented in a similar way to shadows, but with only color & thickness)
- Corner rounding (the ability to round individual corners of a element by a certain amount), this way round windows & things like tabs in Sublime text could be achieved

as of currently  I am using images and a lot of overlapping action to get similar effects, which is probably not very resource efficient and is very difficult to manage due to different resolutions. It would be very great if something like this could be performed using the native UI system:

![image](https://user-images.githubusercontent.com/18470725/168029829-ad87560d-101f-4548-b51c-e5fbdf3a3344.png)

**Comment by Sororfortuna** [comment]
That's a good observation, I look forward to this the most, also some functionality can be mimicked from CSS:
https://developer.mozilla.org/en-US/docs/Web/CSS/border-radius
https://developer.mozilla.org/en-US/docs/Web/CSS/box-shadow

**Comment by turanszkij** [comment]
Sprites now support corner rounding, and border softening #502 . Example usage for rendering an image:
```cpp
wi::image::Params params;
params.pos = XMFLOAT3(GetLogicalWidth() * 0.5f, GetLogicalHeight() * 0.3f, 0);
params.siz = XMFLOAT2(400, 200);
params.pivot = XMFLOAT2(0.5f, 0.5f);
params.border_soften = 0.05f;				// <-
params.enableCornerRounding();				// <-
params.corners_rounding[0].radius = 60;	    // <-
params.corners_rounding[0].segments = 12;   // <-
params.corners_rounding[1].radius = 20;	    // <-
params.corners_rounding[1].segments = 6;    // <-
params.corners_rounding[3].radius = 260;    // <-
params.corners_rounding[3].segments = 40;   // <-
wi::image::Draw(wi::texturehelper::getWhite(), params, cmd);
```
![image_renderer](https://user-images.githubusercontent.com/12954849/183312996-b48d0567-26ca-415b-b72c-4b68e6f1055d.png)
