### ISSUE TITLE
Ragdoll support?

### ISSUE THREAD

**Issue by docstrang** [turanszkij/WickedEngine#444]
Ragdoll support in the future?

**Comment by turanszkij** [comment]
I tagged it as feature request.

**Comment by VinnyVicious** [comment]
Not just ragdolling, but it would be cool to have some sort of animation blender with ragdoll to simulate something like Euphoria:

https://www.youtube.com/watch?v=0Pm0Cvm0zdI

**Comment by turanszkij** [comment]
Ragdoll physics now available https://github.com/turanszkij/WickedEngine/commit/8597b70b602aceb468be74c7e9f4264d8ede1db6

**Comment by VinnyVicious** [comment]
This was impressive. Thank you!
