### ISSUE TITLE
Cel shading or Toon shading.

### ISSUE THREAD

**Issue by tictech1970** [turanszkij/WickedEngine#451]
Is there a way to create materials like Cel shading or Toon shading?.

**Comment by turanszkij** [comment]
There are two built in shader types for this:
- Unlit: light will not affect the material, only the base color. This way pre baked lighting or cartoon effect can be provided in the base color texture.
- Cartoon: lighting will be modulated to look cartoonish.
You can enable these in `MaterialComponent::shaderType` (also can be tried in editor's material window).

**Comment by tictech1970** [comment]
Thanks.
