### ISSUE TITLE
How can you create a door system with physics?

### ISSUE THREAD

**Issue by tictech1970** [turanszkij/WickedEngine#452]
How can you create a door system with physics?

**Comment by turanszkij** [comment]
This is not something I can answer fully, but you could use rigid body for doors, and hinge constraints to lock them to a single axis rotation. And your game code could somehow also disable doors so that they can't be opened (for example make doors fully kinematic when they are locked)

**Comment by tictech1970** [comment]
Ok, I understand perfectly, thanks.
