### ISSUE TITLE
runtime mesh generate example

### ISSUE THREAD

**Issue by WuCheng0912** [turanszkij/WickedEngine#456]
hi, is there an example for gen mesh at runtime such as the cube/sphere with custom vertices

**Comment by turanszkij** [comment]
Hi, this code  generates a mesh for a terrain chunk and adds it to a scene: https://github.com/turanszkij/WickedEngine/blob/master/Editor/TerrainGenerator.cpp#L771

this imports OBJ and converts it to objects and meshes: https://github.com/turanszkij/WickedEngine/blob/master/Editor/ModelImporter_OBJ.cpp

GLTF importer: https://github.com/turanszkij/WickedEngine/blob/master/Editor/ModelImporter_GLTF.cpp
