### ISSUE TITLE
TiledDeferred Render Bug At Intel HD630? 

### ISSUE THREAD

**Issue by dwlcj** [turanszkij/WickedEngine#46]
DX11 Mode
TiledForward Render
![TiledForward](https://user-images.githubusercontent.com/252897/67911615-25540000-fbc2-11e9-81ad-3eb58c32fe9c.png)
TiledDeferred Render
![TiledDeferred](https://user-images.githubusercontent.com/252897/67911641-33098580-fbc2-11e9-9c64-22d89434e996.png)

**Comment by turanszkij** [comment]
Hi, yes it seems Intel doesn't like something about the tiled deferred compute shader. :(

**Comment by turanszkij** [comment]
Looks like R11G11B10_FLOAT texture format UAV loads are not implemented on Intel GPU. This is not in the DirectX spec though, but it works fine on Nvidia at least. However, this texture format is used for light buffers in this engine for performance and quality reasons. An easy fix is to change one line in wiRenderer.h:
```cpp
static const wiGraphics::FORMAT RTFormat_deferred_lightbuffer = wiGraphics::FORMAT_R11G11B10_FLOAT;
```
To this:
```cpp
static const wiGraphics::FORMAT RTFormat_deferred_lightbuffer = wiGraphics::FORMAT_R16G16B16A16_FLOAT;
```

**Comment by turanszkij** [comment]
FORMAT_R11G11B10_FLOAT is definitely faster in deferred and no noticable quality loss so I would like to keep it. Need to figure out someting for Intel GPU.

**Comment by turanszkij** [comment]
Workaround implemented for GPU that doesn't support that UAV format in previous commit.
