### ISSUE TITLE
[Feature] Save the height map of a procedural terrain.

### ISSUE THREAD

**Issue by docstrang** [turanszkij/WickedEngine#470]
I think it is interesting to save the height map of a procedural terrain, I know that it is possible to generate the same terrain based on the seed but being able to save an image of the height map would be nice.

**Comment by turanszkij** [comment]
Sure, this can be implemented, I think it's a good idea.

**Comment by tictech1970** [comment]
Thanks

**Comment by turanszkij** [comment]
I added support for this, now generated terrain can be exported into heightmap texture with PNG format. PNG is 8bits, so it will be lossy. Maybe next, it would be better to implement heightmap support for high precision float image format, but I need to look into that later.
