### ISSUE TITLE
Physics System leaks memory

### ISSUE THREAD

**Issue by matpx** [turanszkij/WickedEngine#471]
wiPhysics_Bullet.cpp seems to leak memory.

btRigidBody, btCollisionShape, btTriangleIndexVertexArray and btDefaultMotionState don't seem to get deleted when a RigidBodyPhysicsComponent is removed from a Scene.

**Comment by turanszkij** [comment]
Thanks, I added deletions for objects allocated with new. Not sure why these were missing.
