### ISSUE TITLE
Wrong surfel_index in surfel_integrateCS.hlsl?

### ISSUE THREAD

**Issue by Evil-Ryu** [turanszkij/WickedEngine#479]
In surfel_integrateCS.hlsl,  the surfel_index was directly set as group id, but I think only active surfels should be considered.

`
void main(uint3 DTid : SV_DispatchThreadID, uint3 Gid : SV_GroupID, uint3 GTid : SV_GroupThreadID, uint groupIndex : SV_GroupIndex)

{
        uint surfel_index = Gid.x;
	// should be:  uint surfel_index = surfelAliveBuffer[Gid.x]; ?
	Surfel surfel = surfelBuffer[surfel_index];
        ......

}
`

**Comment by turanszkij** [comment]
Yes, this looks like a mistake, good catch!
