### ISSUE TITLE
[Feature] Blend animations spaces.

### ISSUE THREAD

**Issue by docstrang** [turanszkij/WickedEngine#482]
Is it possible to blend animations spaces depending on some values? I think it would be a very important feature for character animations like walking and running.

**Comment by turanszkij** [comment]
Animations can be blended by the `AnimationComponent::amount` parameter. You can play multiple animations at once and use different `amount` for each. I don't know what you meant by "spaces" though.

**Comment by docstrang** [comment]
Thanks for the answer, spaces I mean the possibility of assigning a value that acts as a bridge between the animations, for example the speed if it is 0 the anim is idle, if the value is between 0.01 and 0.05 it is walk and greater than 0.05 it is run , is it possible?

**Comment by turanszkij** [comment]
I think you will be able to do that with custom code that fades in/out animations based on your value. For example:
```cpp
AnimationComponent walk;
AnimationComponent run;

// play both anims
walk.Play();
run.Play();

// Set animations' amount in your game code, eg. every frame:
float player_movement_speed = // your game code value between 0 and 1 for example
walk.amount = 1 - player_movement_speed; 
run.amount = player_movement_speed;
```

**Comment by turanszkij** [comment]
You can also try this on the included "Havoc" model in the editor which has lots of animations. For example, playing the "Idle" animation, then selecting the "HeavyKick" animation and playing it at the same time. Then you can control the amount parameter of "HeavyKick" so you can "fade" it out.

**Comment by docstrang** [comment]
Thanks, I'll try.
