### ISSUE TITLE
Saving a glTF model as a wiscene doesn't load back correctly

### ISSUE THREAD

**Issue by Giacom** [turanszkij/WickedEngine#49]
Hello,

I am having an issue where I try to load a glTF model as a wiscene and when I load it back in the editor it comes out blank white.

Steps to reproduce:

1. Download this glTF 2.0 sample (any format will do): https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0/DamagedHelmet
2. Import the model into the editor, it will look fine at this point.

![image](https://user-images.githubusercontent.com/1524810/68422148-861da280-0197-11ea-9e5c-260de744a9f6.png)

3. Save your scene as a wiscene file.
4. Close and reopen the editor.
5. You should see something like the image below.

![image](https://user-images.githubusercontent.com/1524810/68422200-9fbeea00-0197-11ea-8edc-5e8239a746ad.png)

Commit 2c91a16097ec55e7b8077db767aa6793a26ea560

Windows 10 & DX11 backend

**Comment by turanszkij** [comment]
Hi, this is supposed to work. However, there are some corner cases that you might hit. The wiscene models don't store textures within themselves, but relative paths to textures instead. If you load the gltf model, and save it, you must ensure that the texture directory structure remains the same as it was relative to the gltf file.
- Are you saving the wiscene in the same directory where the gltf file is?
- Did you modify any textures on the model before saving?
- There are some bundled gltf files in the models directory (DamagedHelmet, CesiumMan, BusterDrone), can you load and save those models successfully? These models were verified specifically with the editor and should be fully usable.
- If you are loading binary gltf version (.glb), textures will be unpacked from the glb file and written to the directory as png where the glb file was loaded from. The wiscene will contain references to those png textures, so make sure you have those textures available near the wiscene file.

Let me know if those suggestions don't work. Thanks for testing!

**Comment by Giacom** [comment]
Yes you are right, the wiscene file had to be in the same directory as the glTF file. I thought it packed everything in the file.

Thanks for explaining how the importer works, I'll keep that in mind next time.
