### ISSUE TITLE
[Regression] ComponentLibrary commit causes a big drop in framerate

### ISSUE THREAD

**Issue by brakhane** [turanszkij/WickedEngine#520]
The merge of #511 caused a big reduction in framerate on my 1080 when showing the Terrain in the Editor. From ~110 FPS to 46 FPS.

The frame profiler suggests the only difference is the Editor Update, which went from 3.8 ms to 16.5 ms.

You can see screenshots of before and after the change [here](https://imgur.com/a/owsuREz)

Steps to reproduce:

1. `git checkout 8aeed`
2. delete editor/shaders directory
3. rebuild the editor and start
4. Select Terrain Generator, FPS and Profiler
5. Notice framerate is around 50

When using `git checkout 8aeed^` to checkout the parent and redoing the steps 2-5, I get the normal, higher framerate.

Let me know if I should do additional checks.

**Comment by turanszkij** [comment]
Thank you for notifying me, this is quite severe performance drop. I investigated this and seems like when the component manager interface was introduced, the ComponentManager functions were no longer inlined. As seen on profiler:
![image](https://user-images.githubusercontent.com/12954849/185792089-435d90bc-bd3f-44f9-ba60-c84a7e9055df.png)

To solve this, I tried adding final keyword to ComponentManager, and got back function inlining:
![image](https://user-images.githubusercontent.com/12954849/185792136-a09bddfc-acae-4a10-9ea6-0857fd290e7e.png)

This will be up in the next PR merge today

**Comment by turanszkij** [comment]
This fixes it: https://github.com/turanszkij/WickedEngine/commit/12e410d8939d5ff1380e117cd9e15b0da8f86f02
