### ISSUE TITLE
Bug with RT Shadows

### ISSUE THREAD

**Issue by Cop46** [turanszkij/WickedEngine#548]
I think there is a bug with the raytracing shadows.
See the attached video.

https://user-images.githubusercontent.com/32778861/187675053-b5232785-0249-4d4f-b8a2-32dd2c265f49.mp4

**Comment by turanszkij** [comment]
The first half of the video is empty, the second half I don't see a problem. Please explain what I should be looking at.

**Comment by Cop46** [comment]
Hello Turanszkij
Please download the video, I don't understand why by Firefox or Chrome this is not visible correctly...
The problem is when I use the RTShadows there is a flickering problem with shadows. Sometimes appear correctly, sometimes not.

**Comment by turanszkij** [comment]
I downloaded the video, but only a very short part is visible at the end. I don't see flickering that would be unusual. Because RT shadow is half resolution and temporal effect, flickering cannot be avoided completely.

**Comment by Cop46** [comment]
https://user-images.githubusercontent.com/32778861/187690279-24c5980f-a07a-4040-812d-69323f4b58a5.mp4

Maybe convertied like this...this is more readable ?

**Comment by turanszkij** [comment]
This was fixed in: 60ef0ae251ced6253df58485b091ba87492ab6a2

**Comment by ershovdz** [comment]
Hello, I have the similar issue with latest version of the engine:
[https://www.youtube.com/watch?v=X8Wzc-gZuTY](url)
