### ISSUE TITLE
Shadowmap artifacts

### ISSUE THREAD

**Issue by ershovdz** [turanszkij/WickedEngine#551]
Is it possible to fix (or to make less noticeable) these shadowmap artifacts (aliasing, shadow acne) ? May be I can change some settings to resolve it ? 
![shadowmap_artifacts](https://user-images.githubusercontent.com/600507/188161786-14077562-08e5-4ec9-854f-d2189a96ae7d.png)

Scene for example:
[1111.zip](https://github.com/turanszkij/WickedEngine/files/9478411/1111.zip)

**Comment by Cop46** [comment]
Hello,
I have changed a litle the split for cascaded shadows in wiRenderer.cpp at line 2287 like this :
	const float splits[CASCADE_COUNT + 1] = {
		referenceSplitClamp * 0.0f,		// near plane
		referenceSplitClamp * 0.01f,	// near-mid split
		referenceSplitClamp * 0.05f,	// mid-far split
		referenceSplitClamp * 1.0f,		// far plane
	};

And changed a litle the scaling factor of your scene (litle bigger) to have this result.
Maybe there is some better way, I don't know.
![Shadows](https://user-images.githubusercontent.com/32778861/188180916-72213c5e-4ee1-461d-8b4d-24ab38ae2c78.jpg)

**Comment by ershovdz** [comment]
Thanks, it's a little better !

**Comment by turanszkij** [comment]
You can increase shadow resolution, try the suggestions above by Cop46, or modify depth bias for shadow rendering pipelines (they are hard coded in wiRenderer.cpp)

**Comment by turanszkij** [comment]
The shadow rendering pipelines are using rasterizers[RSTYPE_SHADOW] and rasterizers[RSTYPE_SHADOW_DOUBLESIDED], those are created around here currently: https://github.com/turanszkij/WickedEngine/blob/master/WickedEngine/wiRenderer.cpp#L1865
The depth bias parameters are:
```cpp
rs.depth_bias = -1;
rs.depth_bias_clamp = 0;
rs.slope_scaled_depth_bias = -4.0f;
```
