### ISSUE TITLE
wickedengine.net has problems with cURL

### ISSUE THREAD

**Issue by expenses** [turanszkij/WickedEngine#557]
Hi! wickedengine.net seems to have some problem where I can't fetch it with `curl`. I get `curl: (92) HTTP/2 stream 0 was not closed cleanly: PROTOCOL_ERROR (err 1)` when I try and do that. Of course it loads normally in a browser.

This isn't a big issue but it's stopping my RSS feeder from being able to fetch your blog :)

**Comment by turanszkij** [comment]
Sorry, I have no idea about this. The website is hosted on Wordpress, so the issue is probably on Wordpess side.

**Comment by expenses** [comment]
https://stackoverflow.com/a/59955444 recommends to use `--http1.1` when you get errors like this, and `curl --http1.1 https://wickedengine.net/feed/` works fine. https://interplayoflight.wordpress.com/ has the same issue so you're correct in that it's probably a Wordpress issue.
