### ISSUE TITLE
Editor: language options

### ISSUE THREAD

**Issue by turanszkij** [turanszkij/WickedEngine#572]
Adding new languages to the editor should be possible.

**Comment by megumumpkin** [comment]
Which languages should be available and how will the program match and load the languages?

**Comment by turanszkij** [comment]
There should be at least an option to override text for languages. I don't have concrete vision how exactly would be best, but the optional languages can go into text files, the default English language should work without loading any additional files.

For example: If config.ini contains an entry `language = russian`, then engine would try to load laguages/russian.txt and override texts.

**Comment by turanszkij** [comment]
done
