### ISSUE TITLE
Editor crash

### ISSUE THREAD

**Issue by mmssddss** [turanszkij/WickedEngine#583]
I found the whole editor will crash without any log if i mis-typed the `self:move()` to `self.move()`
This typo makes it very difficult to debug lua in the wicked engine

**Comment by turanszkij** [comment]
Yes, I agree this should be improved if possible. Need to look into how to avoid crash when accessing invalid object in lua.

**Comment by mmssddss** [comment]
use `lua_pcall` instead of `lua_call` when calling a function may solve this problem

**Comment by turanszkij** [comment]
That's a good idea. Some calls were already using pcall, but I noticed some weren't. It should be fixed in the new commit: https://github.com/turanszkij/WickedEngine/commit/b6a2967f47dd92522f76bc6cb9b308abb2d5fa03

**Comment by turanszkij** [comment]
Reopen if this is still a problem.
