### ISSUE TITLE
Add a new very powerful physics engine

### ISSUE THREAD

**Issue by Nader-B10** [turanszkij/WickedEngine#590]
A very powerful physics engine ( PhysX 5 ) with great and powerful features developed by Nvidia and made open source about a day ago  

.Engine official website : https://developer.nvidia.com/physx-sdk
 

![physX-gif-web](https://user-images.githubusercontent.com/113104542/200766263-e60d8766-91c3-4927-b7e8-53835520c33f.gif)

  

------------------------------------------------------------------------------------------
https://youtu.be/QuKBZlRFpiA

-------------------------------------------------------------
https://developer.nvidia.com/blog/open-source-simulation-expands-with-nvidia-physx-5-release/

------------------------------------------------------------------------

https://user-images.githubusercontent.com/113104542/200768769-a1220baa-24aa-44e7-9e71-9f74d4549f3e.mp4

https://user-images.githubusercontent.com/113104542/200768391-e142a704-eaa9-4221-8af5-0b35ce0274bd.mp4

https://user-images.githubusercontent.com/113104542/200770626-fee0fb8d-2289-4731-8c5e-f39b1130d9e8.mp4

**Comment by turanszkij** [comment]
The License for this product is not compatible with the engine: https://github.com/NVIDIA-Omniverse/PhysX/blob/release/104.0/LICENSE.md
It specifies additional requirements, like reproducing their copyright notice in binary.

But it could be added as third-party optional plugin, separate from this repository.
