### ISSUE TITLE
Assertion VK_RESOLVE_MODE_MIN_BIT failed

### ISSUE THREAD

**Issue by portaloffreedom** [turanszkij/WickedEngine#591]
While trying to debug for another issue, I get this error:
```
WickedEngineEditor: /home/matteo/projects/WickedEngine/WickedEngine/wiGraphicsDevice_Vulkan.cpp:2534: wi::graphics::GraphicsDevice_Vulkan::GraphicsDevice_Vulkan(wi::platform::window_type, wi::graphics::ValidationMode): Assertion `depth_stencil_resolve_properties.supportedDepthResolveModes& VK_RESOLVE_MODE_MIN_BIT' failed.
```

**Comment by turanszkij** [comment]
This should not cause a real issue currently as we don't use min/max resolve on anything.

**Comment by turanszkij** [comment]
These asserts are replaced by feature reporting instead, so it will no longer be a problem: https://github.com/turanszkij/WickedEngine/commit/e12d966028ab7eac81f7d9dbe2fc82d5294aaada
