### ISSUE TITLE
[Feature] Dynamic occlusion .

### ISSUE THREAD

**Issue by docstrang** [turanszkij/WickedEngine#592]
I think it is quite important to add dynamic occlusion as a feature, I mean not showing an object that is being occluded by another and that both are within the camera's field of view.

**Comment by turanszkij** [comment]
This is already supported: 
![image](https://user-images.githubusercontent.com/12954849/201193013-4536428e-fc51-4203-8e7c-f1a9c1986ef8.png)

In code: `wi::renderer::SetOcclusionCullingEnabled(true)`
