### ISSUE TITLE
Shader compiler err on Win10 vs 2015, Win SDK 8.1

### ISSUE THREAD

**Issue by 00alia00** [turanszkij/WickedEngine#6]
1>------ Build started: Project: WickedEngine_SHADERS, Configuration: Release x64 ------

1>C:\Dev\Git\External\WickedEngine\WickedEngine\generateMIPChain2D_GaussianCS.hlsl(29,11-62): error X3676: typed UAV loads are only allowed for single-component 32-bit element types

**Comment by turanszkij** [comment]
Hi, the project relies on the Windows 10 SDK, which allows shader compilation with typed UAV additional format loads. It also requires Visual Studio 2017 because the engine builds against D3D 11.3.
Thanks for following this!

**Comment by 00alia00** [comment]
Ah, i got everything else to compile and run in that configuration. Even loaded the demo scene and got the editor running. Pretty neat! Just not like 5 of the hlsl files.

**Comment by turanszkij** [comment]
Good to hear. I will do something about this because this problem has come up for other people as well. Thanks for the feedback!
