### ISSUE TITLE
Naming convention

### ISSUE THREAD

**Issue by amerkoleci** [turanszkij/WickedEngine#61]
Decide the convention, I saw there are some member with lower camel case, others with upper camel case, or something like result_passed, maybe good would be to have lower camel case for struct members (IE: TextureDesc)

**Comment by turanszkij** [comment]
Struct members should be lowerCamelCase. In some graphics structs this is not true currently which could be fixed. 

Struct and class names should be UpperCamelCase.

Function names usually UpperCamelCase().

I am experimenting with snake_case in some places. This is mainly used for inline or constexpr small functions and member variables in some specific cases. I would like to keep whatever is in snake_case for the time being.

**Comment by Je06jm** [comment]
Also, in headers, we have both
`#ifndef H_BLA_BLA
#define H_BLA_BLA
// Declarations here
#endif`
and
`#pragma once`

**Comment by turanszkij** [comment]
I am using the `#pragma once` in C++ files, and the `#ifndef` stuff in headers that get included into non-cpp files too, like shaders for example.
