### ISSUE TITLE
Looks like a bug in FSR1/2 solutions

### ISSUE THREAD

**Issue by trsh** [turanszkij/WickedEngine#612]
![2022-12-20_190726](https://user-images.githubusercontent.com/3727523/209145016-c14be20e-8bb5-4578-9396-9beebff8eb55.png)

Those lines should not be there. From my personal experience when working with fsr1 (I had horizonal ones or CRT effect), I can say its most likely a bug which also contributes to making the scene overall more blurry and distorted (what is also the case).

**Comment by trsh** [comment]
Fsr2 quality on 0.5 scale can do much better in terms of quality. Some examples from actual implementation:
no scale -> https://tellusim.com/images/blog/upscale/Scene_3_FSR2_100.png
0.5 -> https://tellusim.com/images/blog/upscale/Scene_3_FSR2_200.png

**Comment by turanszkij** [comment]
Issue in FSR 2.1 should be fixed. I saw no issue in FSR 1.0. You may reopen if you have other things to add.
