### ISSUE TITLE
Latest VXGI introduces boiling effect and patterns in light

### ISSUE THREAD

**Issue by trsh** [turanszkij/WickedEngine#615]
https://streamable.com/miiifc

Right in center. 
Editor from https://github.com/turanszkij/WickedEngine/actions/runs/3840625505
Default settings with VXGI on.

**Comment by trsh** [comment]
Another good spot is the Lion. If you go closer and away, the light/highlights are moving and changing.

**Comment by trsh** [comment]
Some sort of patterns in light can be seen in most places

![2023-01-05_115524](https://user-images.githubusercontent.com/3727523/210752337-b115e51d-e4a4-48a7-91a2-3f926e5a82e9.png)

**Comment by turanszkij** [comment]
These issues are because the voxel gi effects per pixel are now rendered in much lower resolution, because performance. The dithering pattern in reflections is because sample count of reflections is reduced, and this improves the look a bit. I know these are not perfect, but they are intentional to keep reasonable performance.

**Comment by trsh** [comment]
Yeah, but at this state, is hard to call the new VXGI as any kind of improvement.

Old VXGI

![2023-01-05_121346](https://user-images.githubusercontent.com/3727523/210756066-138ca5eb-b0b0-4132-b538-4b1494a9a812.png)

New VXGI

![2023-01-05_121510](https://user-images.githubusercontent.com/3727523/210756289-172126c0-4333-44a9-8c2c-f655c38eb829.png)

DDGI

![2023-01-05_121536](https://user-images.githubusercontent.com/3727523/210756477-1c20d2f8-a85f-4c00-91c2-233a84214188.png)

**Comment by turanszkij** [comment]
If you want to compare to DDGI, turn off VXGI reflections, because DDGI doesn't support reflections. And there are several big improvements to the new VXGI - better voxelization, clipmaps for example.

You can reduce the reflection dithering pattern BTW by lowering ray step size.

**Comment by turanszkij** [comment]
You can use the old version for now then, but it will not support large scene/LOD and accurate voxelization like this. I agree that upsampling quality and performance should be improved in the new one.

**Comment by trsh** [comment]
As for performance, on my RTX 3060, in in Sponza I have ~320fps with new VXGI off and ~180 with on. More then I need.

My suggestions:

1) The boiling (with even reflections off) in my video and image above, should be treated as bug and eliminated at all cost.
2) Should try to stabilize the render with reflections ON. Its just feels to _organic_, when I move camera around its changing and moving and blinking.  
3) And yes should try to improve quality with reflections ON. Ged rid of those patterns, etc. Right now I would turn it off in every case. 
4) Maybe more quality settings?

**Comment by turanszkij** [comment]
I have temporal upscaler also there just disabled (because some temporal problems) so I will add option to enable it. And downscale quality setting can also be added.

**Comment by turanszkij** [comment]
Added option to have full resolution resolve. This is very heavy but it will show what it is now capable of, and with FSR 2.1 it could be even usable. Also some quality tweaks for the dithering in reflections, and with Temporal AA / FSR2.1 it will improve it a bit more.

**Comment by trsh** [comment]
Testing full resolution. So far very good. Quality is on-point and 90 fps and with fsr2.1 up to 144 fps.

**Comment by trsh** [comment]
Some things:

There is a bit of a problem when moving towards area light like this https://streamable.com/kw4y3b . Its starts blinking.

**Comment by trsh** [comment]
![2023-01-06_122548](https://user-images.githubusercontent.com/3727523/210986535-6cf6bac5-af05-489e-9927-5394c554d8eb.png)

Leaking is still a thing even with these updates?

**Comment by turanszkij** [comment]
Yeah, I'm not too happy with the remaining leaking, maybe I'll find some way to improve it, maybe not. The flickering issue seems to occur with voxel size that is not power of two, otherwise there is just transition between voxel LOD (clipmap). I'll see what I can find, thanks for reporting.
