### ISSUE TITLE
More control and improvements for shadow maps

### ISSUE THREAD

**Issue by trsh** [turanszkij/WickedEngine#616]
When playing with sponza for me the LOD'ing of shadows a bit to aggressive. They start degrade and and disappear in way to small distances for me.

**Comment by turanszkij** [comment]
This has been added, now you can customize shadow cascade for directional light in the editor. You can add/remove cascade and set their distances here: 
<img width="503" alt="image" src="https://user-images.githubusercontent.com/12954849/212477773-1434598d-a9f1-4437-abca-ab33cc6f3496.png">

**Comment by trsh** [comment]
@turanszkij thank you!
