### ISSUE TITLE
Where is the bounding box ?

### ISSUE THREAD

**Issue by cailuming** [turanszkij/WickedEngine#626]
Hello, I'm a little bit out of update with recent version changes, which causes the runtime error as bellow:
![image](https://user-images.githubusercontent.com/19427259/213643126-0747e791-5afb-44f8-af07-da77246ae056.png)
![image](https://user-images.githubusercontent.com/19427259/213643051-64f00926-a719-4413-86e4-e5b6af17d1ac.png)
Could you please tell me where does bounding box go? 
By the way D3D12 doesn't work again in my program, but it does work in default Editor project. I don't know why...
![image](https://user-images.githubusercontent.com/19427259/213644310-75a1d268-511b-4a97-bd50-1e8b3eba3522.png)

> 
> [wi::initializer] Initializing Wicked Engine, please wait...
> Version: 0.71.137
> 
> wi::jobsystem Initialized with [12 cores] [11 threads] (8 ms)
> 
> wi::input Initialized (0 ms)
> wi::physics Initialized [Bullet] (0 ms)
> Assertion failed!
> 
> Program: ...ster\CustomBuild\GameProject\Debug\GameProject.exe
> File: F:\projects\WickedEngine-master\Wic...\wiGraph...X12.cpp
> Line: 3614
> 
> Expression: SUCCEEDED(hr)
> 
> For information on how your program can cause an assertion
> failure, see the Visual C++ documentation on asserts
> 
> (Press Retry to debug the application - JIT must be enabled)Assertion failed!
> 
> Program: ...ster\CustomBuild\GameProject\Debug\GameProject.exe
> File: F:\projects\WickedEngine-master\Wic...\wiGraph...X12.cpp
> Line: 3614
> 
> Expression: SUCCEEDED(hr)
> 
> For information on how your program can cause an assertion
> failure, see the Visual C++ documentation on asserts
> 
> (Press Retry to debug the application - JIT must be enabled)“GameProject.exe”(Win32): 已加载“C:\Windows\System32\clbcatq.dll”。
> 0x00007FFFBDFDCD29 处(位于 GameProject.exe 中)引发的异常: Microsoft C++ 异常: _com_error，位于内存位置 0x000000211B4FD8F0 处。
> 0x00007FFFBDFDCD29 处(位于 GameProject.exe 中)引发的异常: Microsoft C++ 异常: _com_error，位于内存位置 0x000000211B5FDB10 处。
> “GameProject.exe”(Win32): 已加载“C:\Windows\System32\AudioSes.dll”。
> “GameProject.exe”(Win32): 已加载“C:\Windows\System32\powrprof.dll”。
> 0x00007FFFBDFDCD29 处(位于 GameProject.exe 中)引发的异常: Microsoft C++ 异常: _com_error，位于内存位置 0x000000211B6FDD40 处。
> Assertion failed!
> 
> Program: ...ster\CustomBuild\GameProject\Debug\GameProject.exe
> File: F:\projects\WickedEngine-master\Wic...\wiGraph...X12.cpp
> Line: 3614
> 
> Expression: SUCCEEDED(hr)
> 
> For information on how your program can cause an assertion
> failure, see the Visual C++ documentation on asserts
> 
> (Press Retry to debug the application - JIT must be enabled)“GameProject.exe”(Win32): 已加载“C:\Windows\System32\umpdc.dll”。
> wi::font Initialized (24 ms)
> “GameProject.exe”(Win32): 已加载“C:\Windows\System32\TextShaping.dll”。
> wi::texturehelper Initialized (28 ms)
> “GameProject.exe”(Win32): 已加载“C:\Windows\System32\ResourcePolicyClient.dll”。
> wi::image Initialized (31 ms)
> 0x00007FFFBDFDCD29 处(位于 GameProject.exe 中)引发的异常: Microsoft C++ 异常: _com_error，位于内存位置 0x000000211B1F9380 处。
> Assertion failed!
> 
> Program: ...ster\CustomBuild\GameProject\Debug\GameProject.exe
> File: F:\projects\WickedEngine-master\Wic...\wiGraph...X12.cpp
> Line: 3614
> 
> Expression: SUCCEEDED(hr)
> 
> For information on how your program can cause an assertion
> failure, see the Visual C++ documentation on asserts
> 
> (Press Retry to debug the application - JIT must be enabled)wi::lua Initialized (41 ms)
> 0x00007FFFBDFDCD29 处(位于 GameProject.exe 中)引发的异常: Microsoft C++ 异常: _com_error，位于内存位置 0x000000211B3FD550 处。
> Assertion failed!
> 
> Program: ...ster\CustomBuild\GameProject\Debug\GameProject.exe
> File: F:\projects\WickedEngine-master\Wic...\wiGraph...X12.cpp
> Line: 3614
> 
> Expression: SUCCEEDED(hr)
> 
> For information on how your program can cause an assertion
> failure, see the Visual C++ documentation on asserts
> 
> (Press Retry to debug the application - JIT must be enabled)0x00007FFFBDFDCD29 处(位于 GameProject.exe 中)引发的异常: Microsoft C++ 异常: _com_error，位于内存位置 0x000000211B8FDED0 处。
> Assertion failed!
> 
> Program: ...ster\CustomBuild\GameProject\Debug\GameProject.exe
> File: F:\projects\WickedEngine-master\Wic...\wiGraph...X12.cpp
> Line: 3614

**Comment by turanszkij** [comment]
You can still get AABB like this:
```cpp
int index = scene.objects.GetIndex(tempGate);
const AABB& aabb = scene.aabb_objects[index];
```
The difference to older version is that aabb_objects is now just simple std::vector. But it uses the same indexing as `objects`.

**Comment by turanszkij** [comment]
For DX12 issue, it looks like failing on shader, please check by rebuilding all shaders.

**Comment by cailuming** [comment]
Thanks, the DX12 issue is caused by shader as you said, but the aabb_objects is always zero after the scene loaded.
![image](https://user-images.githubusercontent.com/19427259/213860201-cb2739c6-c4ad-4d2d-9a43-d5f13222b2ed.png)
And I found the RunObjectUpdateSystem is called every frame
![image](https://user-images.githubusercontent.com/19427259/213860287-b5f80892-88dc-43a4-8624-89b84f436962.png)
the object.getCount() returns different value . I don't know why...

**Comment by turanszkij** [comment]
The aabb_objects will always have the same count as number of objects when the scene was updated. Scene is updated inside LoadModel. I think this could be a problem inside your code.
