### ISSUE TITLE
Disabling FSR 2.1 keeps the resolution scale value according presets

### ISSUE THREAD

**Issue by Bzucko** [turanszkij/WickedEngine#629]
After disabling FSR 2.1, the resolution scale value should be set to 1.

**Comment by turanszkij** [comment]
This was intentional, because when you enable FSR, you can still tweak resolution scaling, and I didn't think it would be appropriate to reset it. But maybe resetting would make more sense, I'll think about it.

**Comment by turanszkij** [comment]
I think since resolution scaling is independent from FSR, I'll keep current behaviour
