### ISSUE TITLE
GI light transport feels to weak

### ISSUE THREAD

**Issue by trsh** [turanszkij/WickedEngine#631]
![2023-01-27_231142](https://user-images.githubusercontent.com/3727523/215201103-1e5b7e25-2143-4764-9467-5994b05b795c.png)

In the image the sun intensity is pretty high, GI is boosted, maxed out rays etc. But as we can see we have these dark nightly places more away from direct light. In such daylight, the entire build should swim in light in every corner.

**Comment by trsh** [comment]
This one is in DDGI, but same stand for all methods.

**Comment by turanszkij** [comment]
Try setting higher exposure or eye adaption. To my best knowledge, the lighting calculations for GI are correct.

**Comment by turanszkij** [comment]
But to be honest I also always found it too dark in default settings, so if someone can prove me what's wrong (if anything) I would welcome it.

**Comment by Bzucko** [comment]
I am not properly sure how this technique exactly works, but with debug enabled you can see, that it heavily depends on the spheres positions and distances between them. Start increasing the number of spheres from really low numbers and check in which position the light distribution works and in which not. There are huge differences in terms of lit the corners. 
In your example there is no chance to lit the places near camera with reflected sun light when there are curtains blocking light and the sun angle is in oposite direction.
I guess DDGI is not ideal solution for this kind of "closed" scenes.
There are also many sponza photo and offline renders references...I found both types, with bright corners(could be HDR photo) and also dark corners.

**Comment by trsh** [comment]
Will try, to bad my blender skills suck.

**Comment by trsh** [comment]
Ok I think I was mixing up a little with a scene that is also influenced by sky. Can we do that in wicked? Get radiance from sky for GI?

The tests (all without sky):

Blender (sun intensity 400):

![2023-01-28_130236](https://user-images.githubusercontent.com/3727523/215263500-7a4e7d2a-44be-4f4d-bfdb-89f5c35c7855.png)

Blender (sun intensity 100):

![aaa](https://user-images.githubusercontent.com/3727523/215263542-a66b0957-984b-4e72-a22f-3354a0f4249c.png)

DDGI sun intensity 10

![2023-01-28_130615](https://user-images.githubusercontent.com/3727523/215263805-33ac6ee2-ed40-4b9d-bda7-20d06cf3343d.png)

DDGI sun intensity 80

![2023-01-28_132024](https://user-images.githubusercontent.com/3727523/215263834-f4785c21-241a-4f87-8695-80fe6df1db74.png)

For this time being I would say the GI works correctly

**Comment by trsh** [comment]
@turanszkij also another question. Is it possible to have a parameter, that effects, how much the light propagates?

**Comment by turanszkij** [comment]
The sky does affect the GI, it is used for ray miss color. Furthermore, there is sky exposure parameter in the weather, which multiplies sky brightness. 

As for parameter to control how much light propagates, doesn't make sense for me. What part of light propagation would it control? Light propagation energy is multiplied by what surface color the rays hit.

**Comment by trsh** [comment]
> The sky does affect the GI, it is used for ray miss color. Furthermore, there is sky exposure parameter in the weather, which multiplies sky brightness.
> 
> As for parameter to control how much light propagates, doesn't make sense for me. What part of light propagation would it control? Light propagation energy is multiplied by what surface color the rays hit.

True. I was thinking maybe in DDGI or VXGI there is some additional vodoo regarding this. Will test the sky and report back soon.

**Comment by trsh** [comment]
![2023-01-28_171851](https://user-images.githubusercontent.com/3727523/215274529-dbf6508a-6d19-4747-81de-5c14d5f0d822.png)
Sky doesn't add much to GI, even with max exposure. Will try in blender.

**Comment by trsh** [comment]
Getting similar results in blender so I guess I am closing this. It just feel weird to see dark corners in bright daylight.
