### ISSUE TITLE
RTAO artifacts against sky

### ISSUE THREAD

**Issue by nathants** [turanszkij/WickedEngine#639]
Black lines and artifacts appear around the edges of objects when the sky is behind them. 

This happens with RTAO but not the other ao types. 

![477A9AEE-E14B-4FDD-8CD9-71A0E2547258](https://user-images.githubusercontent.com/1566190/217411655-ad56dbe9-5c28-4569-a3d0-d7f3b0115544.jpeg)

**Comment by nathants** [comment]
i made a [scene](https://r2.nathants.workers.dev/link/69a77404-56a4-417d-9210-b993fbae86ba/rtao.wiscene) that reproduces the issue and a [video](https://r2.nathants.workers.dev/link/69a77404-56a4-417d-9210-b993fbae86ba/rtao_sky_artifacts.mp4) showing it happen.

**Comment by nathants** [comment]
just repro’d this on windows. looks like the scene didn’t save render/camera settings. rtao on, size 5, power 2. camera move up a lot, it’s under the map.

**Comment by turanszkij** [comment]
Thanks, I will investigate.

Render and main camera settings are saved not in the scene, but the config.ini file, just for future reference. If you add a new camera to the scene, that will be saved into the scene.

**Comment by nathants** [comment]
ah, good to know. will add cameras for the next scene.

**Comment by turanszkij** [comment]
This was caused by sky pixels bleeding in black ambient occlusion to geometry. The above commit fills sky pixels with white ao instead and that improves this artifact.
