### ISSUE TITLE
Animation blending amount strange behavior

### ISSUE THREAD

**Issue by nathants** [turanszkij/WickedEngine#642]
animation blending is not working how i would expect. i have a glb file (attached) that i open in WickedEditor. i have an animation `arms-walking` which when played with amount 1.0 looks fine, but when played with a lesser amount looks odd. am i doing something wrong?

![full_amount](https://user-images.githubusercontent.com/1566190/218624600-eaab67b9-f783-4bab-b83c-a6cd714377a4.png)

![small_amount](https://user-images.githubusercontent.com/1566190/218624641-38ca30f4-d243-4bc7-a41f-85fbb08b9f53.png)

[rain_rig_simplified.glb.zip](https://github.com/turanszkij/WickedEngine/files/10728156/rain_rig_simplified.glb.zip)

**Comment by turanszkij** [comment]
Hm, I tested anim amount on my other animations (from mixamo) and it behaves correctly. But I can see weird arm movement with this character with reduced amount, so issue will be something to do with this model. I will investigate.

**Comment by nathants** [comment]
so it looks like this is rig specific. this odd behavior was when using a blender cloudrig from rain v2. when using a blender rigidy rig, blending works fine.

**Comment by nathants** [comment]
i made some progress on this. 

it seems to happen when using the standard blender gltf exporter, but not when using the gltf exporter in the blender addon “auto-rig pro”. 

i have experienced this with rigs made from blender’s rigify, and auto-rig pro generated rigs. the “nina” character available on blender market exhibits this behavior.

at the moment i am using auto-rig pro, but it may be worth investigating further to get the standard gltf exporter to work. it’s main advantage aside from cost is much faster export.

**Comment by turanszkij** [comment]
I have used Blender's gltf exporter for the animations in character controller sample, and I didn't have problems with it. Those animations are from Mixamo

**Comment by nathants** [comment]
interesting. so likely it is has to do with both the rig in blender and the rig as serialized via export.
