### ISSUE TITLE
float emit in wiEmittedParticle clashes with qt emit

### ISSUE THREAD

**Issue by Cambloid** [turanszkij/WickedEngine#644]
When using WickedEngine with the qt framework, the variable emit in wiEmittedParticle.h clashes with qt emit

**Comment by Cambloid** [comment]
When using WickedEngine with the qt framework, the variable emit in wiEmittedParticle.h clashes with qt emit

**Comment by turanszkij** [comment]
What kind of clash? Is it possible to avoid on your side, for example including QT after wicked engine, or using it in a different namespace?

**Comment by Cambloid** [comment]
It clashes with the emit define from qt, it can be avoided by undefining emit or adding it before any qt header.

I thought i just mention it here as i am testing the framework out.

**Comment by turanszkij** [comment]
Yes, unfortunately this is a problem for global defines. I can't really protect against any random library redefining things, but as you said you can use undef, or include order changes.
