### ISSUE TITLE
Shader compilation failure on Graphics 620

### ISSUE THREAD

**Issue by Enzojz** [turanszkij/WickedEngine#658]
Got massive shdaer compilation failure on my 8th Gen i7 notebook, whose graphics is GT620. On my RTX2070Super everything is fine.

The shader are these comes with source code of engine.

I can use the editor (steam version) without any problem on this computer.

Compiled with MSVC latest version.

Access violation at line 3896 of wiGraphicsDevice_DX12.cpp

			stream.stream1.PS = { shader_internal->shadercode.data(), shader_internal->shadercode.size() };

The card supports DX12

The output is:

    [Error] shader compile FAILED: shaders/hlsl6/objectVS_common_tessellation.cso
    
    [Error] shader compile FAILED: shaders/hlsl6/lensFlareVS.cso
    
    [Error] shader compile FAILED: shaders/hlsl6/gpusortlib_sortInnerCS.cso
    
    [Error] shader compile FAILED: shaders/hlsl6/emittedparticle_kickoffUpdateCS.cso
    
    wi::GPUBVH Initialized (80 ms)
    [Error] shader compile FAILED: shaders/hlsl6/oceanSurfacePS.cso
    
    [Error] shader compile FAILED: shaders/hlsl6/volumetriclight_spotVS.cso
    
    [Error] shader compile FAILED: shaders/hlsl6/impostorPS.cso
    
    [Error] shader compile FAILED: shaders/hlsl6/objectVS_prepass_alphatest.cso
    
    [Error] shader compile FAILED: shaders/hlsl6/hairparticle_simulateCS.cso
    
    [Error] shader compile FAILED: shaders/hlsl6/oceanSurfaceSimplePS.cso
    
    [Error] shader compile FAILED: shaders/hlsl6/gpusortlib_sortStepCS.cso
    
    [Error] shader compile FAILED: shaders/hlsl6/voxelVS.cso
    
    [Error] shader compile FAILED: shaders/hlsl6/impostorPS_prepass.cso
    
    [Error] shader compile FAILED: shaders/hlsl6/fft_512x512_c2c_CS.cso
    
    [Error] shader compile FAILED: shaders/hlsl6/emittedparticle_finishUpdateCS.cso
    
    wi::gpusortlib Initialized (56 ms)
    [Error] shader compile FAILED: shaders/hlsl6/objectVS_prepass.cso
    
    [Error] shader compile FAILED: shaders/hlsl6/envMapVS.cso
    
    [Error] shader compile FAILED: shaders/hlsl6/hairparticle_finishUpdateCS.cso
    
    [Error] shader compile FAILED: shaders/hlsl6/objectVS_prepass_alphatest_tessellation.cso
    
    [Error] shader compile FAILED: shaders/hlsl6/envMap_skyPS_static.cso
    
    [Error] shader compile FAILED: shaders/hlsl6/fft_512x512_c2c_v2_CS.cso
    
    [Error] shader compile FAILED: shaders/hlsl6/emittedparticle_emitCS.cso
    
    [Error] shader compile FAILED: shaders/hlsl6/objectPS_debug.cso
    
    [Error] shader compile FAILED: shaders/hlsl6/lightVisualizerPS.cso
    
    [Error] shader compile FAILED: shaders/hlsl6/objectVS_prepass_tessellation.cso
    
    wi::HairParticleSystem Initialized (101 ms)
    [Error] shader compile FAILED: shaders/hlsl6/renderlightmapPS.cso
    
    [Error] shader compile FAILED: shaders/hlsl6/sunPS.cso
    
    [Error] shader compile FAILED: shaders/hlsl6/vPointLightVS.cso
    
    [Warning] File not found: shaders/hlsl6/renderlightmapPS.cso
    [Error] shader compile FAILED: shaders/hlsl6/volumetricCloud_upsamplePS.cso
    
    [Error] shader compile FAILED: shaders/hlsl6/shadowPS_transparent.cso
    
    [Error] shader compile FAILED: shaders/hlsl6/emittedparticle_emitCS_volume.cso
    
    [Error] shader compile FAILED: shaders/hlsl6/tileFrustumsCS.cso
    
    [Error] shader compile FAILED: shaders/hlsl6/vSpotLightVS.cso
    
    [Error] shader compile FAILED: shaders/hlsl6/captureImpostorPS.cso
    
    [Error] shader compile FAILED: shaders/hlsl6/forceFieldPlaneVisualizerVS.cso
    
    wi::Ocean Initialized (102 ms)
    [Error] shader compile FAILED: shaders/hlsl6/downsampleDepthBuffer4xPS.cso
    
    [Error] shader compile FAILED: shaders/hlsl6/vxgi_temporalCS.cso
    
    [Error] shader compile FAILED: shaders/hlsl6/voxelGS.cso
    
    [Error] shader compile FAILED: shaders/hlsl6/skyAtmosphere_skyLuminanceLutCS.cso
    
    [Error] shader compile FAILED: shaders/hlsl6/forceFieldPointVisualizerVS.cso
    
    [Error] shader compile FAILED: shaders/hlsl6/generateMIPChain2DCS_unorm4.cso
    
    [Error] shader compile FAILED: shaders/hlsl6/cubeShadowVS.cso
    
    [Error] shader compile FAILED: shaders/hlsl6/lightCullingCS_DEBUG.cso
    
    [Error] shader compile FAILED: shaders/hlsl6/emittedparticle_emitCS_FROMMESH.cso
    
    [Error] shader compile FAILED: shaders/hlsl6/vxgi_resolve_diffuseCS.cso
    
    [Error] shader compile FAILED: shaders/hlsl6/generateMIPChainCubeCS_float4.cso
    
    [Error] shader compile FAILED: shaders/hlsl6/copytexture2D_float4_borderexpandCS.cso
    
    [Error] shader compile FAILED: shaders/hlsl6/generateMIPChainCubeArrayCS_float4.cso
    
    [Error] shader compile FAILED: shaders/hlsl6/objectPS_simple.cso
    
    [Error] shader compile FAILED: shaders/hlsl6/emittedparticle_sphpartitionCS.cso
    
    [Error] shader compile FAILED: shaders/hlsl6/blur_gaussian_unorm4CS.cso
    
    [Error] shader compile FAILED: shaders/hlsl6/paint_textureCS.cso
    
    [Error] shader compile FAILED: shaders/hlsl6/envMap_skyVS.cso
    
    [Error] shader compile FAILED: shaders/hlsl6/volumetricLight_PointPS.cso
    
    [Error] shader compile FAILED: shaders/hlsl6/blur_gaussian_wide_float3CS.cso
    
    [Error] shader compile FAILED: shaders/hlsl6/blur_bilateral_float3CS.cso
    
    [Error] shader compile FAILED: shaders/hlsl6/vertexcolorPS.cso
    
    [Error] shader compile FAILED: shaders/hlsl6/ssaoCS.cso
    
    [Error] shader compile FAILED: shaders/hlsl6/blur_bilateral_unorm1CS.cso
    
    [Error] shader compile FAILED: shaders/hlsl6/blur_bilateral_wide_unorm1CS.cso
    
    [Error] shader compile FAILED: shaders/hlsl6/emittedparticle_sphcellallocationCS.cso
    
    [Error] shader compile FAILED: shaders/hlsl6/msao_blurupsampleCS_blendout.cso
    
    [Error] shader compile FAILED: shaders/hlsl6/objectPS_paintradius.cso
    
    [Error] shader compile FAILED: shaders/hlsl6/msaoCS.cso
    
    [Error] shader compile FAILED: shaders/hlsl6/objectPS_voxelizer.cso
    
    [Error] shader compile FAILED: shaders/hlsl6/ssr_raytraceCS.cso
    
    [Error] shader compile FAILED: shaders/hlsl6/ssr_kickjobsCS.cso
    
    [Error] shader compile FAILED: shaders/hlsl6/emittedparticle_sphbinningCS.cso
    
    [Error] shader compile FAILED: shaders/hlsl6/volumetricLight_DirectionalPS.cso
    
    [Error] shader compile FAILED: shaders/hlsl6/depthoffield_tileMaxCOC_horizontalCS.cso
    
    [Error] shader compile FAILED: shaders/hlsl6/outlinePS.cso
    
    [Error] shader compile FAILED: shaders/hlsl6/depthoffield_mainCS_earlyexit.cso
    
    [Error] shader compile FAILED: shaders/hlsl6/ssr_bilateralCS.cso
    
    [Error] shader compile FAILED: shaders/hlsl6/depthoffield_prepassCS_earlyexit.cso
    
    [Error] shader compile FAILED: shaders/hlsl6/motionblur_kickjobsCS.cso
    
    [Error] shader compile FAILED: shaders/hlsl6/emittedparticle_sphdensityCS.cso
    
    [Error] shader compile FAILED: shaders/hlsl6/luminancePass2CS.cso
    
    [Error] shader compile FAILED: shaders/hlsl6/aerialPerspectiveCS_capture_MSAA.cso
    
    [Error] shader compile FAILED: shaders/hlsl6/volumetricCloud_renderCS_capture_MSAA.cso
    
    [Error] shader compile FAILED: shaders/hlsl6/cubeMapPS.cso
    
    [Error] shader compile FAILED: shaders/hlsl6/aerialPerspectiveCS.cso
    
    [Error] shader compile FAILED: shaders/hlsl6/motionblur_tileMaxVelocity_verticalCS.cso
    
    [Error] shader compile FAILED: shaders/hlsl6/emittedparticle_sphforceCS.cso
    
    [Error] shader compile FAILED: shaders/hlsl6/shadowPS_water.cso
    
    [Error] shader compile FAILED: shaders/hlsl6/lightCullingCS_ADVANCED_DEBUG.cso
    
    [Error] shader compile FAILED: shaders/hlsl6/ffx-fsr2/ffx_fsr2_reconstruct_previous_depth_pass.cso
    
    [Error] shader compile FAILED: shaders/hlsl6/upsample_bilateral_unorm1CS.cso
    
    [Error] shader compile FAILED: shaders/hlsl6/tonemapCS.cso
    
    [Error] shader compile FAILED: shaders/hlsl6/volumetricCloud_renderCS.cso
    
    [Error] shader compile FAILED: shaders/hlsl6/temporalaaCS.cso
    
    [Error] shader compile FAILED: shaders/hlsl6/emittedparticle_simulateCS.cso
    
    [Error] shader compile FAILED: shaders/hlsl6/skyAtmosphere_transmittanceLutCS.cso
    
    [Error] shader compile FAILED: shaders/hlsl6/surfel_coverageCS.cso
    
    [Error] shader compile FAILED: shaders/hlsl6/visibility_resolveCS.cso
    
    [Error] shader compile FAILED: shaders/hlsl6/upsample_bilateralPS.cso
    
    [Error] shader compile FAILED: shaders/hlsl6/ddgi_updateCS_depth.cso
    
    [Error] shader compile FAILED: shaders/hlsl6/ffx-fsr2/ffx_fsr2_compute_luminance_pyramid_pass.cso
    
    [Error] shader compile FAILED: shaders/hlsl6/emittedparticle_simulateCS_SORTING.cso
    
    [Error] shader compile FAILED: shaders/hlsl6/chromatic_aberrationCS.cso
    
    [Error] shader compile FAILED: shaders/hlsl6/generateMIPChain3DCS_unorm4.cso
    
    [Error] shader compile FAILED: shaders/hlsl6/luminancePass1CS.cso
    
    [Error] shader compile FAILED: shaders/hlsl6/virtualTextureTileAllocateCS.cso
    
    [Error] shader compile FAILED: shaders/hlsl6/objectDS.cso
    
    [Error] shader compile FAILED: shaders/hlsl6/emittedparticle_simulateCS_DEPTHCOLLISIONS.cso
    
    [Error] shader compile FAILED: shaders/hlsl6/normalsfromdepthCS.cso
    
    [Error] shader compile FAILED: shaders/hlsl6/surfel_integrateCS.cso
    
    [Error] shader compile FAILED: shaders/hlsl6/objectPS_ANISOTROPIC.cso
    
    [Error] shader compile FAILED: shaders/hlsl6/copytexture2D_unorm4CS.cso
    
    [Error] shader compile FAILED: shaders/hlsl6/lightCullingCS_ADVANCED.cso
    
    [Error] shader compile FAILED: shaders/hlsl6/objectPS_TRANSPARENT.cso
    
    [Error] shader compile FAILED: shaders/hlsl6/emittedparticle_simulateCS_SORTING_DEPTHCOLLISIONS.cso
    
    [Error] shader compile FAILED: shaders/hlsl6/ddgi_raytraceCS.cso
    
    [Error] shader compile FAILED: shaders/hlsl6/visibility_surfaceCS_WATER.cso
    
    [Error] shader compile FAILED: shaders/hlsl6/objectPS_SHEEN_TRANSPARENT.cso
    
    [Error] shader compile FAILED: shaders/hlsl6/impostor_prepareCS.cso
    
    [Error] shader compile FAILED: shaders/hlsl6/vxgi_resolve_specularCS.cso
    
    [Error] shader compile FAILED: shaders/hlsl6/blur_gaussian_float3CS.cso
    
    [Error] shader compile FAILED: shaders/hlsl6/visibility_surfaceCS_PLANARREFLECTION_REDUCED.cso
    
    [Warning] File not found: shaders/hlsl6/ddgi_raytraceCS.cso
    [Error] shader compile FAILED: shaders/hlsl6/objectHS_prepass_alphatest.cso
    
    [Error] shader compile FAILED: shaders/hlsl6/generateMIPChain2DCS_float4.cso
    
    [Error] shader compile FAILED: shaders/hlsl6/visibility_surfaceCS_CLEARCOAT_REDUCED.cso
    
    [Error] shader compile FAILED: shaders/hlsl6/visibility_shadeCS_CARTOON.cso
    
    [Error] shader compile FAILED: shaders/hlsl6/blur_gaussian_wide_unorm1CS.cso
    
    wi::EmittedParticleSystem Initialized (202 ms)
    [Error] shader compile FAILED: shaders/hlsl6/filterEnvMapCS.cso
    
    [Error] shader compile FAILED: shaders/hlsl6/objectPS_PLANARREFLECTION.cso
    
    [Error] shader compile FAILED: shaders/hlsl6/objectPS_CLEARCOAT.cso
    
    [Error] shader compile FAILED: shaders/hlsl6/blur_gaussian_float1CS.cso
    
    [Error] shader compile FAILED: shaders/hlsl6/objectVS_debug.cso
    
    [Error] shader compile FAILED: shaders/hlsl6/blur_gaussian_wide_float4CS.cso
    
    [Error] shader compile FAILED: shaders/hlsl6/blur_bilateral_unorm4CS.cso
    
    [Error] shader compile FAILED: shaders/hlsl6/objectPS_CARTOON_TRANSPARENT.cso
    
    [Error] shader compile FAILED: shaders/hlsl6/renderlightmapVS.cso
    
    [Error] shader compile FAILED: shaders/hlsl6/visibility_surfaceCS_PARALLAXOCCLUSIONMAPPING.cso
    
    [Error] shader compile FAILED: shaders/hlsl6/visibility_surfaceCS_SHEEN_CLEARCOAT.cso
    
    [Error] shader compile FAILED: shaders/hlsl6/hbaoCS.cso
    
    [Error] shader compile FAILED: shaders/hlsl6/blur_bilateral_wide_float1CS.cso
    
    [Error] shader compile FAILED: shaders/hlsl6/ssr_raytraceCS_earlyexit.cso
    
    [Error] shader compile FAILED: shaders/hlsl6/msao_blurupsampleCS_premin.cso
    
    [Error] shader compile FAILED: shaders/hlsl6/volumetriclight_pointVS.cso
    
    [Error] shader compile FAILED: shaders/hlsl6/depthoffield_tileMaxCOC_verticalCS.cso
    
    [Error] shader compile FAILED: shaders/hlsl6/visibility_surfaceCS_UNLIT_REDUCED.cso
    
    [Error] shader compile FAILED: shaders/hlsl6/msao_preparedepthbuffers1CS.cso
    
    [Error] shader compile FAILED: shaders/hlsl6/visibility_shadeCS_ANISOTROPIC.cso
    
    [Error] shader compile FAILED: shaders/hlsl6/motionblurCS.cso
    
    [Error] shader compile FAILED: shaders/hlsl6/objectVS_voxelizer.cso
    
    [Error] shader compile FAILED: shaders/hlsl6/depthoffield_mainCS_cheap.cso
    
    [Error] shader compile FAILED: shaders/hlsl6/msao_blurupsampleCS_premin_blendout.cso
    
    [Error] shader compile FAILED: shaders/hlsl6/volumetricCloud_shapenoiseCS.cso
    
    [Error] shader compile FAILED: shaders/hlsl6/ddgi_debugVS.cso
    
    [Error] shader compile FAILED: shaders/hlsl6/objectPS_hologram.cso
    
    [Error] shader compile FAILED: shaders/hlsl6/volumetricCloud_reprojectCS.cso
    
    [Error] shader compile FAILED: shaders/hlsl6/impostorPS_simple.cso
    
    [Error] shader compile FAILED: shaders/hlsl6/ssr_raytraceCS_cheap.cso
    
    [Error] shader compile FAILED: shaders/hlsl6/upsample_bilateral_float4CS.cso
    
    [Error] shader compile FAILED: shaders/hlsl6/envMap_skyPS_dynamic.cso
    
    [Error] shader compile FAILED: shaders/hlsl6/ffx-fsr2/ffx_fsr2_depth_clip_pass.cso
    
    [Error] shader compile FAILED: shaders/hlsl6/underwaterCS.cso
    
    [Error] shader compile FAILED: shaders/hlsl6/shadowPS_alphatest.cso
    
    [Error] shader compile FAILED: shaders/hlsl6/surfel_indirectprepareCS.cso
    
    [Error] shader compile FAILED: shaders/hlsl6/raytrace_debugbvhPS.cso
    
    [Error] shader compile FAILED: shaders/hlsl6/objectGS_voxelizer.cso
    
    [Error] shader compile FAILED: shaders/hlsl6/depthoffield_neighborhoodMaxCOCCS.cso
    
    [Error] shader compile FAILED: shaders/hlsl6/visibility_resolveCS_MSAA.cso
    
    [Error] shader compile FAILED: shaders/hlsl6/lightCullingCS.cso
    
    [Error] shader compile FAILED: shaders/hlsl6/vxgi_sdf_jumpfloodCS.cso
    
    [Error] shader compile FAILED: shaders/hlsl6/terrainVirtualTextureUpdateCS.cso
    
    [Error] shader compile FAILED: shaders/hlsl6/skyAtmosphere_cameraVolumeLutCS.cso
    
    [Error] shader compile FAILED: shaders/hlsl6/virtualTextureResidencyUpdateCS.cso
    
    [Error] shader compile FAILED: shaders/hlsl6/objectDS_prepass.cso
    
    [Error] shader compile FAILED: shaders/hlsl6/depthoffield_postfilterCS.cso
    
    [Error] shader compile FAILED: shaders/hlsl6/objectPS_WATER.cso
    
    [Error] shader compile FAILED: shaders/hlsl6/objectPS_PLANARREFLECTION_TRANSPARENT.cso
    
    [Error] shader compile FAILED: shaders/hlsl6/skinningCS.cso
    
    [Error] shader compile FAILED: shaders/hlsl6/blur_gaussian_wide_float1CS.cso
    
    [Error] shader compile FAILED: shaders/hlsl6/generateMIPChainCubeArrayCS_unorm4.cso
    
    [Error] shader compile FAILED: shaders/hlsl6/motionblurCS_earlyexit.cso
    
    [Error] shader compile FAILED: shaders/hlsl6/objectPS_CLEARCOAT_TRANSPARENT.cso
    
    [Error] shader compile FAILED: shaders/hlsl6/visibility_surfaceCS_CARTOON.cso
    
    [Error] shader compile FAILED: shaders/hlsl6/blur_bilateral_float4CS.cso
    
    [Error] shader compile FAILED: shaders/hlsl6/blur_bilateral_wide_unorm4CS.cso
    
    [Error] shader compile FAILED: shaders/hlsl6/msao_blurupsampleCS.cso
    
    [Error] shader compile FAILED: shaders/hlsl6/visibility_surfaceCS_PARALLAXOCCLUSIONMAPPING_REDUCED.cso
    
    [Error] shader compile FAILED: shaders/hlsl6/volumetricCloud_detailnoiseCS.cso
    
    [Error] shader compile FAILED: shaders/hlsl6/visibility_shadeCS_UNLIT.cso
    
    [Error] shader compile FAILED: shaders/hlsl6/visibility_surfaceCS_SHEEN_CLEARCOAT_REDUCED.cso
    
    [Error] shader compile FAILED: shaders/hlsl6/ssr_depthHierarchyCS.cso
    
    [Error] shader compile FAILED: shaders/hlsl6/lightShaftsCS.cso
    
    [Error] shader compile FAILED: shaders/hlsl6/volumetricCloud_shadow_renderCS.cso
    
    [Error] shader compile FAILED: shaders/hlsl6/depthoffield_mainCS.cso
    
    [Error] shader compile FAILED: shaders/hlsl6/motionblur_neighborhoodMaxVelocityCS.cso
    
    [Error] shader compile FAILED: shaders/hlsl6/fsr_upscalingCS.cso
    
    [Error] shader compile FAILED: shaders/hlsl6/ffx-fsr2/ffx_fsr2_lock_pass.cso
    
    [Error] shader compile FAILED: shaders/hlsl6/aerialPerspectiveCS_capture.cso
    
    [Error] shader compile FAILED: shaders/hlsl6/upsample_bilateral_unorm4CS.cso
    
    [Error] shader compile FAILED: shaders/hlsl6/volumetricCloud_renderCS_capture.cso
    
    'RailwaySandbox.exe' (Win32): Loaded 'C:\Windows\System32\powrprof.dll'. 
    [Error] shader compile FAILED: shaders/hlsl6/ffx-fsr2/ffx_fsr2_prepare_input_color_pass.cso
    
    'RailwaySandbox.exe' (Win32): Loaded 'C:\Windows\System32\umpdc.dll'. 
    [Error] shader compile FAILED: shaders/hlsl6/surfel_updateCS.cso
    
    [Error] shader compile FAILED: shaders/hlsl6/sharpenCS.cso
    
    [Error] shader compile FAILED: shaders/hlsl6/visibility_indirect_prepareCS.cso
    
    [Error] shader compile FAILED: shaders/hlsl6/upsample_bilateral_float1CS.cso
    
    [Error] shader compile FAILED: shaders/hlsl6/terrainVirtualTextureUpdateCS_normalmap.cso
    
    wi::audio Initialized [XAudio2] (296 ms)
    [Error] shader compile FAILED: shaders/hlsl6/screenspaceshadowCS.cso
    
    [Error] shader compile FAILED: shaders/hlsl6/objectVS_simple.cso
    
    [Error] shader compile FAILED: shaders/hlsl6/windCS.cso
    
    [Error] shader compile FAILED: shaders/hlsl6/surfel_raytraceCS.cso
    
    [Error] shader compile FAILED: shaders/hlsl6/objectDS_prepass_alphatest.cso
    
    [Warning] File not found: shaders/hlsl6/surfel_raytraceCS.cso
    [Error] shader compile FAILED: shaders/hlsl6/objectPS_CARTOON.cso
    
    [Error] shader compile FAILED: shaders/hlsl6/ddgi_updateCS.cso
    
    [Error] shader compile FAILED: shaders/hlsl6/shadowVS_alphatest.cso
    
    [Error] shader compile FAILED: shaders/hlsl6/objectHS_simple.cso
    
    [Error] shader compile FAILED: shaders/hlsl6/objectPS_PARALLAXOCCLUSIONMAPPING_TRANSPARENT.cso
    
    [Error] shader compile FAILED: shaders/hlsl6/objectPS_SHEEN_CLEARCOAT_TRANSPARENT.cso
    
    [Error] shader compile FAILED: shaders/hlsl6/virtualTextureTileRequestsCS.cso
    
    [Error] shader compile FAILED: shaders/hlsl6/objectPS_SHEEN_CLEARCOAT.cso
    
    [Error] shader compile FAILED: shaders/hlsl6/objectPS_PARALLAXOCCLUSIONMAPPING.cso
    
    [Error] shader compile FAILED: shaders/hlsl6/objectPS_UNLIT_TRANSPARENT.cso
    
    [Error] shader compile FAILED: shaders/hlsl6/visibility_surfaceCS_ANISOTROPIC_REDUCED.cso
    
    [Error] shader compile FAILED: shaders/hlsl6/shadowVS_transparent.cso
    
    [Error] shader compile FAILED: shaders/hlsl6/visibility_surfaceCS_UNLIT.cso
    
    [Error] shader compile FAILED: shaders/hlsl6/visibility_shadeCS.cso
    
    [Error] shader compile FAILED: shaders/hlsl6/visibility_surfaceCS_REDUCED.cso
    
    [Error] shader compile FAILED: shaders/hlsl6/impostorVS.cso
    
    [Error] shader compile FAILED: shaders/hlsl6/visibility_surfaceCS_ANISOTROPIC.cso
    
    [Error] shader compile FAILED: shaders/hlsl6/visibility_surfaceCS_SHEEN_REDUCED.cso
    
    [Error] shader compile FAILED: shaders/hlsl6/visibility_shadeCS_SHEEN.cso
    
    wi::physics Initialized [Bullet] (0 ms)
    [Error] shader compile FAILED: shaders/hlsl6/occludeeVS.cso
    
    [Error] shader compile FAILED: shaders/hlsl6/shadowVS.cso
    
    [Error] shader compile FAILED: shaders/hlsl6/objectVS_simple_tessellation.cso
    
    [Error] shader compile FAILED: shaders/hlsl6/visibility_shadeCS_WATER.cso
    
    [Error] shader compile FAILED: shaders/hlsl6/postprocessVS.cso
    
    [Error] shader compile FAILED: shaders/hlsl6/sphereVS.cso
    
    [Error] shader compile FAILED: shaders/hlsl6/raytrace_screenVS.cso
    
    [Error] shader compile FAILED: shaders/hlsl6/cubeShadowVS_transparent.cso
    
    [Error] shader compile FAILED: shaders/hlsl6/objectPS_prepass.cso
    
    [Error] shader compile FAILED: shaders/hlsl6/cubeShadowVS_alphatest.cso
    
    [Error] shader compile FAILED: shaders/hlsl6/volumetricLight_SpotPS.cso
    
    [Error] shader compile FAILED: shaders/hlsl6/skyPS_static.cso
    
    [Error] shader compile FAILED: shaders/hlsl6/objectPS_prepass_alphatest.cso
    
    [Error] shader compile FAILED: shaders/hlsl6/resolveMSAADepthStencilCS.cso
    
    [Error] shader compile FAILED: shaders/hlsl6/voxelPS.cso
    
    [Error] shader compile FAILED: shaders/hlsl6/shadingRateClassificationCS.cso
    
    [Error] shader compile FAILED: shaders/hlsl6/lensFlarePS.cso
    
    [Error] shader compile FAILED: shaders/hlsl6/envMapPS.cso
    
    [Error] shader compile FAILED: shaders/hlsl6/copytexture2D_float4CS.cso
    
    [Error] shader compile FAILED: shaders/hlsl6/generateMIPChain3DCS_float4.cso
    
    [Error] shader compile FAILED: shaders/hlsl6/skyAtmosphere_multiScatteredLuminanceLutCS.cso
    
    [Error] shader compile FAILED: shaders/hlsl6/skyPS_dynamic.cso
    
    [Error] shader compile FAILED: shaders/hlsl6/blur_gaussian_wide_unorm4CS.cso
    
    [Error] shader compile FAILED: shaders/hlsl6/blur_bilateral_wide_float3CS.cso
    
    [Error] shader compile FAILED: shaders/hlsl6/blur_gaussian_float4CS.cso
    
    [Error] shader compile FAILED: shaders/hlsl6/msao_preparedepthbuffers2CS.cso
    
    [Error] shader compile FAILED: shaders/hlsl6/ssr_tileMaxRoughness_horizontalCS.cso
    
    [Error] shader compile FAILED: shaders/hlsl6/forceFieldVisualizerPS.cso
    
    [Error] shader compile FAILED: shaders/hlsl6/ssr_resolveCS.cso
    
    [Error] shader compile FAILED: shaders/hlsl6/ddgi_debugPS.cso
    
    [Error] shader compile FAILED: shaders/hlsl6/depthoffield_kickjobsCS.cso
    
    [Error] shader compile FAILED: shaders/hlsl6/depthoffield_upsampleCS.cso
    
    [Error] shader compile FAILED: shaders/hlsl6/motionblurCS_cheap.cso
    
    [Error] shader compile FAILED: shaders/hlsl6/shadingRateClassificationCS_DEBUG.cso
    
    [Error] shader compile FAILED: shaders/hlsl6/fsr_sharpenCS.cso
    
    [Error] shader compile FAILED: shaders/hlsl6/volumetricCloud_shadow_filterCS.cso
    
    [Error] shader compile FAILED: shaders/hlsl6/ffx-fsr2/ffx_fsr2_accumulate_pass.cso
    
    [Error] shader compile FAILED: shaders/hlsl6/volumetricCloud_curlnoiseCS.cso
    
    [Error] shader compile FAILED: shaders/hlsl6/vxgi_offsetprevCS.cso
    
    [Error] shader compile FAILED: shaders/hlsl6/upsample_bilateral_uint4CS.cso
    
    [Error] shader compile FAILED: shaders/hlsl6/surfel_gridoffsetsCS.cso
    
    [Error] shader compile FAILED: shaders/hlsl6/skyAtmosphere_skyViewLutCS.cso
    
    [Error] shader compile FAILED: shaders/hlsl6/visibility_skyCS.cso
    
    [Error] shader compile FAILED: shaders/hlsl6/terrainVirtualTextureUpdateCS_surfacemap.cso
    
    [Error] shader compile FAILED: shaders/hlsl6/generateMIPChainCubeCS_unorm4.cso
    
    [Error] shader compile FAILED: shaders/hlsl6/copytexture2D_unorm4_borderexpandCS.cso
    
    [Error] shader compile FAILED: shaders/hlsl6/blur_gaussian_unorm1CS.cso
    
    [Error] shader compile FAILED: shaders/hlsl6/blur_bilateral_float1CS.cso
    
    [Error] shader compile FAILED: shaders/hlsl6/blur_bilateral_wide_float4CS.cso
    
    [Error] shader compile FAILED: shaders/hlsl6/msao_interleaveCS.cso
    
    [Error] shader compile FAILED: shaders/hlsl6/ssr_tileMaxRoughness_verticalCS.cso
    
    [Error] shader compile FAILED: shaders/hlsl6/ssr_temporalCS.cso
    
    [Error] shader compile FAILED: shaders/hlsl6/depthoffield_prepassCS.cso
    
    [Error] shader compile FAILED: shaders/hlsl6/motionblur_tileMaxVelocity_horizontalCS.cso
    
    [Error] shader compile FAILED: shaders/hlsl6/bloomseparateCS.cso
    
    [Error] shader compile FAILED: shaders/hlsl6/volumetricCloud_weathermapCS.cso
    
    [Error] shader compile FAILED: shaders/hlsl6/fxaaCS.cso
    
    [Error] shader compile FAILED: shaders/hlsl6/ffx-fsr2/ffx_fsr2_autogen_reactive_pass.cso
    
    [Error] shader compile FAILED: shaders/hlsl6/ffx-fsr2/ffx_fsr2_rcas_pass.cso
    
    [Error] shader compile FAILED: shaders/hlsl6/downsample4xCS.cso
    
    [Error] shader compile FAILED: shaders/hlsl6/surfel_binningCS.cso
    
    [Error] shader compile FAILED: shaders/hlsl6/visibility_velocityCS.cso
    
    [Error] shader compile FAILED: shaders/hlsl6/meshlet_prepareCS.cso
    
    [Error] shader compile FAILED: shaders/hlsl6/objectHS_prepass.cso
    
    [Error] shader compile FAILED: shaders/hlsl6/objectPS.cso
    
    [Error] shader compile FAILED: shaders/hlsl6/objectPS_SHEEN.cso
    
    [Error] shader compile FAILED: shaders/hlsl6/objectPS_WATER_TRANSPARENT.cso
    
    [Error] shader compile FAILED: shaders/hlsl6/visibility_surfaceCS_PLANARREFLECTION.cso
    
    [Error] shader compile FAILED: shaders/hlsl6/visibility_surfaceCS_CLEARCOAT.cso
    
    [Error] shader compile FAILED: shaders/hlsl6/visibility_surfaceCS_CARTOON_REDUCED.cso
    
    [Error] shader compile FAILED: shaders/hlsl6/objectHS.cso
    
    [Error] shader compile FAILED: shaders/hlsl6/visibility_shadeCS_PARALLAXOCCLUSIONMAPPING.cso
    
    [Error] shader compile FAILED: shaders/hlsl6/objectDS_simple.cso
    
    [Error] shader compile FAILED: shaders/hlsl6/objectPS_UNLIT.cso
    
    [Error] shader compile FAILED: shaders/hlsl6/objectPS_ANISOTROPIC_TRANSPARENT.cso
    
    [Error] shader compile FAILED: shaders/hlsl6/visibility_surfaceCS.cso
    
    [Error] shader compile FAILED: shaders/hlsl6/visibility_surfaceCS_SHEEN.cso
    
    [Error] shader compile FAILED: shaders/hlsl6/visibility_surfaceCS_WATER_REDUCED.cso
    
    [Error] shader compile FAILED: shaders/hlsl6/visibility_shadeCS_PLANARREFLECTION.cso
    
    [Error] shader compile FAILED: shaders/hlsl6/visibility_shadeCS_CLEARCOAT.cso
    
    [Error] shader compile FAILED: shaders/hlsl6/visibility_shadeCS_SHEEN_CLEARCOAT.cso
    
    Scene serialize took 0.000663 sec
    Exception thrown: read access violation.
    **this** was 0x28.

**Comment by turanszkij** [comment]
First make sure that the windows updates and graphics drivers are up to date. And the GPU must support shader model 6.0

**Comment by turanszkij** [comment]
Also, if you are building yourself then make sure you are running from correct working directory. The simplest way is to run from Visual Studio with F5 button.

**Comment by Enzojz** [comment]
> Also, if you are building yourself then make sure you are running from correct working directory. The simplest way is to run from Visual Studio with F5 button.

I think I'm correct at this point. Btw, how the engine knows which shader are to be loaded, it just at look into wi::renderer::GetShaderSourcePath() and load all?

**Comment by turanszkij** [comment]
It loads each shader separately with the wi::renderer::LoadShader function. That function takes tge shader filename as parameter.

**Comment by turanszkij** [comment]
Looking in this database, that GPU doesn't support shader model 6.0: https://www.techpowerup.com/gpu-specs/geforce-gt-620.c820
It also doesn't support Vulkan, so I think you are out of luck with that GPU.
