### ISSUE TITLE
What is the big idea?

### ISSUE THREAD

**Issue by dmitrykolesnikovich** [turanszkij/WickedEngine#659]
Do you want to reach feature parity with Unreal? Unity? What is the biggest idea achieving that you can say "my engine is DONE"?

**Comment by turanszkij** [comment]
Feature parity with Unreal or Unity is not planned. The biggest idea is making a full game someday.

**Comment by dmitrykolesnikovich** [comment]
Do you have one particular game in mind that perfectly examplify how to utilize graphics algorithms for high quality gameplay experience? Maybe World of Tanks?

**Comment by turanszkij** [comment]
There is no set genre in this engine, you can do any kind of game. Currently I have made a fighting game and a third person adventure game style demo that you can try in Content/scripts/ folder. They can be easily opened in the Editor.

**Comment by dmitrykolesnikovich** [comment]
Those games are working fine on PC.
