### ISSUE TITLE
How to import GLTF in the Editor?

### ISSUE THREAD

**Issue by dmitrykolesnikovich** [turanszkij/WickedEngine#660]
Do not see the option of importing models to the scene via Editor in "New:" drop-down list

![image](https://user-images.githubusercontent.com/6131040/230755082-bf703db8-769b-459f-b40c-def03399ff80.png)

**Comment by turanszkij** [comment]
With the open button in the top menu

**Comment by dmitrykolesnikovich** [comment]
Thanks will try that!

**Comment by dmitrykolesnikovich** [comment]
This works!
