### ISSUE TITLE
Increased editor custom scaling then set it back to 1.0, now can't get editor font antialiasing back

### ISSUE THREAD

**Issue by alfredbaudisch** [turanszkij/WickedEngine#662]
I wanted to increase the scaling of the editor, so in startup.lua I added the suggested `canvas.SetCustomScaling(1.1)`. But, now, even if I remove the custom scaling or set it back to `1.0`, my editor fonts do not have antialiasing anymore. I also doubled checked the config.ini and the resolution is correctly set to 1: `resolution_scale = 1.000000`.

![imagen](https://user-images.githubusercontent.com/248383/230967047-31e11637-485b-4b73-95aa-3ef3d3cf19fd.png)

It's very hard on the eyes:
![imagen](https://user-images.githubusercontent.com/248383/230969823-991c8b11-30e8-403c-ad73-4127eea02bc4.png)

How can I get rid of the text aliasing, and get fonts back to be similarly to [this János video](https://youtu.be/ia7wth7r2cg?t=2)?

![imagen](https://user-images.githubusercontent.com/248383/230968540-f801c30c-2978-4722-ab04-516db24a4d9a.png)

## Versions
- Windows 10
- DX12
- WickedEngine built from master

**Comment by turanszkij** [comment]
What if you delete the custom scaling script, does it go back to normal? I will look into the scaling issue later.

**Comment by alfredbaudisch** [comment]
> What if you delete the custom scaling script, does it go back to normal? I will look into the scaling issue later.

The scaling goes back to normal, but unfortunately the aliasing persists.

**Comment by alfredbaudisch** [comment]
Even if move to different folders, rebuild from source, etc, the text is now unreadable all over the place:

![imagen](https://user-images.githubusercontent.com/248383/231218984-4d1c0537-23a4-421d-842e-d8ceae7cf6d8.png)

**Comment by turanszkij** [comment]
This commit should improve the font rendering for low DPI display: https://github.com/turanszkij/WickedEngine/commit/492f78c6fd48ad3cdff83db9da26f86fdfeb649e

**Comment by alfredbaudisch** [comment]
Thanks, just tried, results comparing `upscaling`:

![imagen](https://user-images.githubusercontent.com/248383/231379600-94e9db5b-6dde-4c48-ba87-5286f4ea8b1e.png)

![imagen](https://user-images.githubusercontent.com/248383/231379973-ecd1ea6a-c38f-4878-ba72-7d489b1f2220.png)

**Comment by turanszkij** [comment]
I think this is an improvement, currently I don't know how to improve further easily.

**Comment by alfredbaudisch** [comment]
I improved it significantly better by setting: `static const float upscaling = 0.9f;`

And then in startup.lua:
```lua
local canvas = application.GetCanvas();
canvas.SetCustomScaling(1.2);
application.SetCanvas(canvas)
```

Not as smooth as @turanszkij videos and screenshots, but it's significantly better than before and readable.

![imagen](https://user-images.githubusercontent.com/248383/232290030-bb6a5d61-b723-465d-b4d1-12ddf39766c7.png)

![imagen](https://user-images.githubusercontent.com/248383/232290047-83ec3799-fdd8-4531-8d93-68e804ae5dcb.png)

@turanszkij thanks for your awesome work!
