### ISSUE TITLE
[BUG] An error occurs when creating a hair particle from the editor with the RTAO option enabled.

### ISSUE THREAD

**Issue by docstrang** [turanszkij/WickedEngine#663]
An error occurs when creating a hair particle from the editor with the RTAO option enabled.

**Comment by docstrang** [comment]
I have tried on another computer and the same thing happens, when you activate the RTAO in dx12 and add a hair particle the program is interrupted and a dx12 error appears.

**Comment by turanszkij** [comment]
Thanks for reporting, should be fixed now.
