### ISSUE TITLE
Editor - change font for better CJK character support

### ISSUE THREAD

**Issue by conradax** [turanszkij/WickedEngine#673]
Hi I suggest to change the font to provide better CJK character support.

I was trying to make a Chinese translation for Editor, but I found that the font is not happy with Chinese characters.  
I took sometime to read the code, load a new font, then Chinese is displayed correctly.  

``` C++
// file: Editor.cpp, line 620, function: EditorComponent::Start()
    ...
    //wi::font::AddFontStyle("yumin", yumin, yumin_size);
    wi::font::AddFontStyle("zh-cn.ttf");
    ...
```

In pic below, **left** is steam version, **right** is my custom build with modified code.

![image](https://github.com/turanszkij/WickedEngine/assets/20236946/6f9bb66e-f4af-405d-b786-c8375248c89c)

I see here is a huge file (30MiB) named `yumin.h`, and currently font is loaded from that header file, is there any advantages to do that?
(I'm a C++ newbie, And I only know a little about OpenGL)

**Comment by turanszkij** [comment]
Fonts are compiled into the exe from header files, to avoid loading from separate files. This way user only needs the exe and not other files to run the editor. We can add support for chinese font, can you post that font file here, so I can test it and create embedded header file from it?

**Comment by turanszkij** [comment]
> Maybe I should complete the translation so that you can test it with new font properly. What do you think? @turanszkij

You don't have to create full chinese localization, we can fix the chinese text support separately. But if you create localization, we can include it with the engine.

**Comment by turanszkij** [comment]
Thanks for the screenshots. I like the look of unifont at first glance. I will test it for myself a bit too.

**Comment by turanszkij** [comment]
This is solved in this commit: https://github.com/turanszkij/WickedEngine/commit/3fbb10b6b50910890d873fdaeb501828bff2f1ca
- Removed Yumin font
- Added Noto Sans CJK font to Editor/fonts
- Editor/fonts folder can contain other user fonts if new characters need to be supported, they will be loaded automatically at startup
- Default font in the Editor can be overridden in config.ini by specifying `font = filename.ttf` (see example in Editor/config.ini
