### ISSUE TITLE
Incorrect tooltip for FSR1 sharpening

### ISSUE THREAD

**Issue by Calinou** [turanszkij/WickedEngine#693]
**Wicked Engine version:** https://github.com/turanszkij/WickedEngine/commit/10ca8ccd1288554b5f291120a4c3f6f29b9743d5 (nightly build)
**OS:** Linux (Fedora 38)
**GPU:** GeForce RTX 4090 (NVIDIA 530.41.03)

When hovering the FSR1 sharpness slider with the mouse, I see the tooltip for FSR2 sharpness:

![Screenshot_20230614_192917](https://github.com/turanszkij/WickedEngine/assets/180032/01620604-d064-4bb3-9361-8b731f4392a3)

There's this line in the codebase, but it's not effective for some reason: https://github.com/turanszkij/WickedEngine/blob/10ca8ccd1288554b5f291120a4c3f6f29b9743d5/Editor/GraphicsWindow.cpp#L1303

**Comment by turanszkij** [comment]
This happened because localization, the gui elements that have same name map to the same localization entry if they are in the same section (window). The correct way is to have different names for them but same text. Fixed some other ones too that I notices were wrong. Thanks for reporting.
