### ISSUE TITLE
Divide by zero due to uint wrap-around in latest commit

### ISSUE THREAD

**Issue by AsgardXIV** [turanszkij/WickedEngine#708]
Looks like commit a75df7bdb21cd949c79631539b4bda119ff5710a has introduced a divide by zero issue in `wiRandom.h` because where the max argument is max uint32 or uint64, the +1 causes a wrap-around to 0.

This issue currently prevents importing VRMs (or any glTF I suspect), as that code path generates a random file with uint32 max.

Will also run into the issue if you specify -1 as a max for signed values.  I suspect it needs to be guarded against 0 no matter the circumstance, it's just really obvious now the wrap around always happens for max uint.

**Comment by turanszkij** [comment]
Thank you for reporting the issue!
