### ISSUE TITLE
ini parser does not handle final line if no line break before EOF

### ISSUE THREAD

**Issue by AsgardXIV** [turanszkij/WickedEngine#712]
If the final line in an `.ini` file does not have a linebreak, the parser fails to parse that line entirely. 

The easiest fix is to just always append a blank newline [here](https://github.com/turanszkij/WickedEngine/blob/master/WickedEngine/wiConfig.cpp#L102), but that feels a little hacky so you may have a better idea of a fix.

**Comment by turanszkij** [comment]
Thanks for reporting the issue. The commit linked above fixes it.
