### ISSUE TITLE
[Feature] path tracing depth-stencil for vulkan

### ISSUE THREAD

**Issue by Cop46** [turanszkij/WickedEngine#726]
If this is possible to develop the path tracing depth-stencil for vulkan that would be cool ?
Thanks for your great work !

**Comment by turanszkij** [comment]
Hi, unfortunately Vulkan doesn't support it at this time. This is an outstanding issue that can be tracked here: https://github.com/KhronosGroup/Vulkan-Docs/issues/2079

**Comment by turanszkij** [comment]
This is now fixed with a workaround method, depth stencil effects will work in Vulkan path tracing now.
