### ISSUE TITLE
Incorrect BRDF rendering of rough materials

### ISSUE THREAD

**Issue by Nolram12345** [turanszkij/WickedEngine#736]
There seems to be some incorrect rendering of rough materials in WickedEngine. Continuing from the discussions on the Discord, rough materials are still rendered with specularity, resulting in incorrect lighting them, which is noticeable especially when validating against other renderers. See footage below, where I compare rendering of [this tree 3D model](https://polyhaven.com/a/jacaranda_tree) in [this HDRI](https://polyhaven.com/a/table_mountain_2_puresky) in WI vs Blender (Cycles and Eevee), and also a comparison of a simple fully black cube. It's probably worth a further investigation.

https://github.com/turanszkij/WickedEngine/assets/37701550/71a915f6-0121-4de2-8672-392bab1cbeb2

https://github.com/turanszkij/WickedEngine/assets/37701550/c6ab8452-a18d-4ee6-824e-c2c3e68531fa

https://github.com/turanszkij/WickedEngine/assets/37701550/52581f49-f951-4dae-9b38-178f3adf5247

**Comment by Nolram12345** [comment]
Here is another white furnace example with the tree model illustrating the issue.
https://github.com/turanszkij/WickedEngine/assets/37701550/f8d5de59-0e4b-4ff6-919b-b5cf7857c24c

**Comment by turanszkij** [comment]
Right now it mostly matches Windows 3D Viewer result

Windows 10 3D Viewer:
![image](https://github.com/turanszkij/WickedEngine/assets/12954849/7a7e39f7-8ef1-4523-a2e6-ba03e9d09ed8)

Wicked Engine:
![sc_25-08-2023 06-58-59](https://github.com/turanszkij/WickedEngine/assets/12954849/c8978cb3-1170-4999-938d-eebd2720058c)

(I had to remove vertex colors from the model, otherwise it's mostly balck)

**Comment by turanszkij** [comment]
I'm having problems with Blender, I couldn't really find a way to adjust roughness easily. But I agree that Blender renders it differently, as if it doesn't have fresnel effect.

**Comment by turanszkij** [comment]
Gestaltor reference GLTF viewer:
![image](https://github.com/turanszkij/WickedEngine/assets/12954849/5d70030d-4728-472e-ac3a-87535a8f904b)

Wicked Engine:
![sc_25-08-2023 08-22-14](https://github.com/turanszkij/WickedEngine/assets/12954849/b0efb1cf-54b3-43b4-9771-99173a3da8cc)

I think it's pretty close.

**Comment by LVutner** [comment]
It looks like you're using a plain Schlick's fresnel for IBL reflection instead of DFG term.

**Comment by LVutner** [comment]
Seems like a plain Schlick is being used for IBL reflection, instead of DFG term.
https://github.com/turanszkij/WickedEngine/blob/19280fc45e868bebde31489684457e3e2266ecea/WickedEngine/shaders/surfaceHF.hlsli#L244

**Comment by Nolram12345** [comment]
> Right now it mostly matches Windows 3D Viewer result
> 
> Windows 10 3D Viewer: ![image](https://user-images.githubusercontent.com/12954849/263170460-7a7e39f7-8ef1-4523-a2e6-ba03e9d09ed8.png)
> 
> Wicked Engine: ![sc_25-08-2023 06-58-59](https://user-images.githubusercontent.com/12954849/263170477-c8978cb3-1170-4999-938d-eebd2720058c.png)
> 
> (I had to remove vertex colors from the model, otherwise it's mostly balck)

I see that, however the visual output here is definitely wrong. A bark material with those rough properties should have that metallic sheen. Therefore I would say that the PBR model in the windows 3D viewer is probably flawed as well (which isn't terribly surprising considering its a very basic viewer that isn't designed for accuracy or production rendering). 
I therefore think taking orientation against both other renderers who don't exude this behaviour and real-life reference is probably better.

LVutner may be onto something with the usage of Schlick for IBL reflection.

**Comment by brakhane** [comment]
> I'm having problems with Blender, I couldn't really find a way to adjust roughness easily. But I agree that Blender renders it differently, as if it doesn't have fresnel effect.

The model has a roughness map, if you go on the material settings, and click on the dot at roughness ("separate color") you can then choose "remove link" in the menu. After that you can modify the roughness value globally. Wicked and Blender are close for low values, but begin to differ after 0.4 or so.

**Comment by turanszkij** [comment]
> Seems like a plain Schlick is being used for IBL reflection, instead of DFG term.
> 
> https://github.com/turanszkij/WickedEngine/blob/19280fc45e868bebde31489684457e3e2266ecea/WickedEngine/shaders/surfaceHF.hlsli#L244
> 
> I suggest to bake DFG lookup table for IBL, or use approximations (ie. https://www.unrealengine.com/en-US/blog/physically-based-shading-on-mobile).

After replacing the Schlick with the `EnvBRDFApprox` in the article you linked:

Wicked Roughness 1:
![sc_25-08-2023 20-20-59](https://github.com/turanszkij/WickedEngine/assets/12954849/6c2e5184-6363-42f7-99c8-e61fbaf7b5d0)

Blender roughness 1:
![image](https://github.com/turanszkij/WickedEngine/assets/12954849/58018c2a-1016-4fb8-9113-cb8ce6566a17)

Wicked Rougness 0:
![sc_25-08-2023 20-20-53](https://github.com/turanszkij/WickedEngine/assets/12954849/7c4bbd78-fae5-4ea1-9a95-904337aa6ce2)

Blender roughness 0:
![image](https://github.com/turanszkij/WickedEngine/assets/12954849/791345da-0e32-4f65-9f29-5c93638b25e2)

**Comment by LVutner** [comment]
cool

**Comment by Nolram12345** [comment]
That looks a lot better! Can't wait to try it and see if it improves things :)

**Comment by turanszkij** [comment]
Some more notes on IBL DFG terms:
https://knarkowicz.wordpress.com/2014/12/27/analytical-dfg-term-for-ibl/
https://github.com/TheRealMJP/DXRPathTracer/blob/master/SampleFramework12/v1.02/Shaders/BRDF.hlsl#L209

**Comment by turanszkij** [comment]
Added this in the PR: https://github.com/turanszkij/WickedEngine/pull/737 
Let me know if this is matching expectations.

**Comment by turanszkij** [comment]
The following fixes were made since this issue was opened:
- applying Unreal Engine's Environment BRDF approximation for surface.F value in PBR shaders
- environment map prefiltering improvements: NdotL normalization, dynamic miplod determination
- environment map filtering only goes down to 16x16 mip level as recommended by some graphics people, also as in `EXT_lights_image_based` GLTF sample
