### ISSUE TITLE
UpdateRenderData()

### ISSUE THREAD

**Issue by nathants** [turanszkij/WickedEngine#738]
It would be nice to be able to update the vertex position and normals of a mesh without calling `DeleteRenderData()` and then `CreateRenderData()`. Perhaps some unnecessary allocations can be avoided by reusing existing memory and a new function `UpdateRenderData()`.

**Comment by turanszkij** [comment]
You don't need to call `DeleteRenderData()` to recreate, it is enough to call `CreateRenderData()`. It is possible to update part of GPU buffers by using `GraphicsDevice::AllocateGPU()` and `GraphicsDevice::CopyBuffer()` functions. Having a function called UpdateRenderData seems too vague for me. Instead I want to focus on providing best performance possible for `CreateRenderData()`.
