### ISSUE TITLE
build SPIRV got some error

### ISSUE THREAD

**Issue by BillyUSA** [turanszkij/WickedEngine#74]
build SPIRV got some error。the file  "cullingShaderHF.hlsli" is exist，but a fatal error reportted:  'cullingShaderHF.hlsli' file not found. 

[build_SPIRV_errors.log](https://github.com/turanszkij/WickedEngine/files/4010207/build_SPIRV_errors.log)

**Comment by turanszkij** [comment]
Hi, thanks for reporting this. Unfortunately I can't reproduce this issue on my side. I'll try in a different environment when I get the chance.

**Comment by turanszkij** [comment]
I still couldn't reproduce this issue. Could you post your build_SPIRV.bat file that was generated for you?

**Comment by BillyUSA** [comment]
use  visual studio open  "cullingShaderHF.hlsli" , save as--> save with encoding -->line encodigs( windows CR LF) , then no error reportted.

**Comment by turanszkij** [comment]
That's interesting, it seems it does have that line encoding set for me. If I save it again with setting it, the files are the same so won't let me commit any changes. Could it be that you somehow saved it with different line encoding? I didn't get this issue from anyone else. Thanks for the feedback!

**Comment by turanszkij** [comment]
Shader build system changed, this is not relevant anymore.
