### ISSUE TITLE
Jolt physics

### ISSUE THREAD

**Issue by VinnyVicious** [turanszkij/WickedEngine#747]
Very capable, and open-source, physics engine: https://github.com/jrouwe/JoltPhysics

Integrating with it would certainly allow time for other endeavors.

**Comment by SlavaArduino12345** [comment]
Does even this engine even has any good physics? If no, then I NEED IT RIGHT NOW

**Comment by turanszkij** [comment]
> Does even this engine even has any good physics? If no, then I NEED IT RIGHT NOW

There is Bullet physics in the engine

**Comment by VinnyVicious** [comment]
@SlavaArduino12345 the current physics engine is pretty solid, not sure what are you talking about.

It's just that Jolt is newer and shinier and was used in a AAA title. Probably less stable than Bullet.

**Comment by turanszkij** [comment]
Adding Jolt physics: https://github.com/turanszkij/WickedEngine/pull/867

**Comment by turanszkij** [comment]
Completed
