### ISSUE TITLE
Creating ocean and terrain from Editor

### ISSUE THREAD

**Issue by VinnyVicious** [turanszkij/WickedEngine#748]
I just saw this tweet: https://twitter.com/turanszkij/status/1519269342290001920

And I was wondering how such a scene can be created from the editor. Are there Ocean/Terrain/Sky components that can be added? If so, how?

**Comment by turanszkij** [comment]
You can add a terrain from Editor by simply adding a new terrain. A scene similar to that can be created if you switch to the "Island" terrain preset. Otherwise, you can configure the sky and ocean in the weather. Weather is added automatically for a terrain, or you can add your own.

**Comment by VinnyVicious** [comment]
My bad, I've missed the "New" button in the UI. Was able to create via code though.
