### ISSUE TITLE
Shadowmap resolution too low when viewing Cornell Box.

### ISSUE THREAD

**Issue by antonyjones67** [turanszkij/WickedEngine#75]
![ShadowResolution](https://user-images.githubusercontent.com/3905646/71629215-90698500-2bb9-11ea-9c28-c865a7349db6.jpg)

Is there a setting I need to tweak? I don't remember this being a problem before.

**Comment by turanszkij** [comment]
Hi, you can set a different shadow map resolution in Renderer window. There is a separate setting for 2D shadow maps (spot light, directional light), and Cube shadow maps (point light, area lights). From the look of it, you have a point light in this scene, which is 256x256x6 resolution by default

**Comment by turanszkij** [comment]
Feel free to reopen if you have anything to add.
