### ISSUE TITLE
RT Diffuse artifacts

### ISSUE THREAD

**Issue by Cop46** [turanszkij/WickedEngine#753]
Hi,
There is some render problem with ray traced diffuse enabled.
![RTDiffuseArtifact](https://github.com/turanszkij/WickedEngine/assets/32778861/9463bf89-ac79-4283-9118-ac330548c0f0)

**Comment by turanszkij** [comment]
Probably something specific to those models, it doesn't happen for the models I tested with. If you have any more info how I can repro it in my side or can share a model that exhibits this, then please share.

**Comment by Cop46** [comment]
I think this is not related to the model because I have this same effect on diferent scene.
This is much related to the material maybe with Alpha but I'm not sure for now.

**Comment by Cop46** [comment]
Hello, I can reproduce this bug in the editor.
Attached zip files contain wiscene and config.ini for editor.
[rtbug.zip](https://github.com/turanszkij/WickedEngine/files/13201028/rtbug.zip)
![WickedBugRTDiffuse](https://github.com/turanszkij/WickedEngine/assets/32778861/3c1380c5-2c64-4e0a-9b7c-8eb45bf0564e)

**Comment by turanszkij** [comment]
Thanks for attaching the repro case, unfortunately it is not happening for me:
![image](https://github.com/turanszkij/WickedEngine/assets/12954849/12b5b111-bad5-413d-8b0c-fc330b99ab0d)

**Comment by Cop46** [comment]
This bug appear to be fixed now.
