### ISSUE TITLE
Bad performance with terrain and surfel GI or DDGI

### ISSUE THREAD

**Issue by ivalylo** [turanszkij/WickedEngine#755]
Hello,
If you create the default terrain in the editor and use surfel GI or DDGI, after moving the camera around, the fps drops to single digit and even freezes. Tested both on Nvidia and Radeon.

**Comment by turanszkij** [comment]
It seems there is some issue with the grass particle system ray tracing. Also problem with other raytracing effects. When grass disabled, problem disappears.

**Comment by turanszkij** [comment]
The issue was that hair particle systems that were frustum culled on CPU but created and included in acceleration structure were not yet initialized were containing garbage data. When garbage is included in acceleration structure, strange things can happen. It is now fixed.
