### ISSUE TITLE
Transform component scale decreasing in editor with certain rotations.

### ISSUE THREAD

**Issue by MortimerSnerd** [turanszkij/WickedEngine#759]
I'm on commit bb519474cad797af78f53bbee622520efbb725f7 , Windows.

In the editor, if you rotate an object around the y-axis by 90 degrees, the X and Z scale displayed in the transform component box will slowly start to decrease.  I'm guessing it's some sort of numerical error that's happening when the transform is decomposed and recomposed for the panel display.  But I didn't look, I just ran into this fooling around on my lunch break.

To reproduce:

1) start editor
2) create a new Cube
3) Open transform panel for cube, put 90.0 as the Y rotation
4) X and Z of scale should start dropping.

**Comment by turanszkij** [comment]
Yes, I was aware of this, I also think this is some precision issue with matrix decompose. Haven't found a better way to do the editor transforms yet.
