### ISSUE TITLE
UE4

### ISSUE THREAD

**Issue by ANTEVETY** [turanszkij/WickedEngine#77]
Hello. I am impressed with your work and the fact that you support the project in solo. I have a request or suggestion for you... In the engine from Epic Games, I think there is a clear problem with the SSR, it is too noisy, gives grain and quality improvement does not give significant improvements, it only hurts performance. After downloading and watching your engine, I was surprised by the quality of the SSR, and indeed with all the lighting. Do you have the time and desire to create a UE4 fork and add your own SSR there? It would be great if this idea arouses your interest. I also drew attention to your VoxelGI, I don’t know if it also has cascades, like in the CryEngine, but it looks amazing. In UE4, they recently added SSGI as well, as the SSR is noisy, and at the maximum quality the FPS drops by half, the FPS also sags noticeably in your engine when the voxels are turned on, but the SSGI has much more artifacts than with the voxel technology. Epic games are too keen on ray tracing and it is still slow for games (plus only Nvidia cards), so we need alternatives so that the player ultimately chooses the lighting and reflection technology in the settings. If by your efforts these features appear in UE4, the inhabitants of the UE4 forum will be standing to applaud you)    I don’t know if you need the main shaders here:  https://github.com/EpicGames/UnrealEngine/tree/release/Engine/Shaders/Private

**Comment by turanszkij** [comment]
Hi, thanks. I doubt I'll write SSR for Unreal as I've never used it and don't have much desire to learn. I think Unreal's SSR is supposed to be the better one anyway, in how it handles roughness. My one is just using a simple gaussian blur which is fake that doesn't handle roughness in a correct way. I think Unreal's shouldn't be overly noisy but it's designed to be used alongside Temporal Antialiasing, did you try that?
As for voxel GI, my version doesn't use cascades and needs some optimizations probably.

**Comment by ANTEVETY** [comment]
SSR and Temporal Antialiasing... Yes, I know about it and it doesn’t help much. Thanks anyway. I am interested in your project and I will follow the updates. You need to assemble a team, I definitely will not help with this, since the artist is not a programmer)
