### ISSUE TITLE
Incorrect assertion in video parser

### ISSUE THREAD

**Issue by Michael-Manning** [turanszkij/WickedEngine#783]
Lines 122 of wiVideo.cpp contains the following assertion which cannot fail:

`assert(nal.type = h264::NAL_UNIT_TYPE_SPS);`

Do you prefer pull requests for minor issues like this?

**Comment by turanszkij** [comment]
I added this as a part of latest commit: https://github.com/turanszkij/WickedEngine/commit/8704e7e02c533c8fa0355236bdcd75a16243c4f8
It is ok to either report minor issues like this or open pull request immediately for them. Thank you for reporting.
