### ISSUE TITLE
Vulkan Synchronization Error

### ISSUE THREAD

**Issue by JonahGoldsmith** [turanszkij/WickedEngine#802]
Currently if you run Wicked Engine Editor or the Template Projects you will get spammed with validation errors if running VERBOSE and VULKAN. This is due to the imageAcquiredSemaphore associated with the Swapchain not finishing its wait operation before trying to present. After digging deep, it seems like we only wait on the fence associated with the imageAcquiredSemaphore AFTER presentation. Adding vkWaitForFences right before presentation does fix the problem but may not be the smartest solution...

To reproduce this error do these steps:
Clone repo. Build Solution. Set TemplateWindows as startup project. Build and Run.

Nothing happens yet.
Now in the commandline arguments: -vulkan and -gpu_verbose
Now you will see the validation errors.

**Comment by turanszkij** [comment]
I don't see these errors. What's the version of your validation layers / vulkan SDK?

**Comment by turanszkij** [comment]
Error comes up with latest Vulkan SDK, investigating...

**Comment by turanszkij** [comment]
I added buffering to acquire semaphores. I thought semaphore is supposed to be GPU only, but it looks like `vkAcquireNextImageKHR` uses it from the CPU too since otherwise we wouldn't get validation warning immediately at this call.
