### ISSUE TITLE
Minor typo in ssaoCS.hlsl

### ISSUE THREAD

**Issue by zZUBAa** [turanszkij/WickedEngine#803]
There's an issue in non-USE_LINEARDEPTH path:
ao += (ray_depth_sample > ray_depth_real) * depth_fix;
should be 
ao += (ray_depth_sample < ray_depth_real) * depth_fix;

thanks.

**Comment by turanszkij** [comment]
It's not a typo, have you tried what happens when you swap the comparison like you suggest? The result gets inverted.

**Comment by zZUBAa** [comment]
Ah I see, so hardware depth is inversed, thanks.
