### ISSUE TITLE
Bug in CloudShadowFilter?

### ISSUE THREAD

**Issue by IvayloCC** [turanszkij/WickedEngine#823]
Hi,

wiRenderer.cpp-> CloudShadowFilter() is binding TEXTYPE_2D_VOLUMETRICCLOUDS_SHADOW both as SRV and UAV. AFAIK, this is valid use case, but the shader should read and write to the same index. However, volumetricCloud_shadow_filterCS is doing a gather. Isn't that a bug?

**Comment by turanszkij** [comment]
Nice find, fixed.
