### ISSUE TITLE
UI/UX improvments

### ISSUE THREAD

**Issue by mddm1** [turanszkij/WickedEngine#830]
Is anyone interested in how a person from exterior that never used this engine sees it? How about a person that has released a couple of indie games and has a decent experience with game engines and programming? Throughout my life I have used Unreal, Unity and Godot. I have seen and started to follow the incredible work put into this engine and decided to use it. But the UI is, in my opinion, a massive problem as it makes actual developing a game very difficult. 
I understand that the author wants to create something unique. But that will not benefit his creation as people want something useful above all else. The author should consider common practices in UI design and establish them because in doing so, others will find it easier to _**adopt**_ his creation. 
Let's take for example UE.
![6](https://github.com/turanszkij/WickedEngine/assets/70328320/230515ba-35ec-4c59-8eb2-c3d51f9f2d7a)

It has a top bar with common actions and tools, all softwares have> File, Edit, Help, etc. As seen below Wicked has none if it. Not only that, Wicked has icons instead of text - a poor practice especially for those who try the engine for the first time. It feels like trying the decipher hieroglyphs. It would be imperative to add text.

<img width="944" alt="1" src="https://github.com/turanszkij/WickedEngine/assets/70328320/8e7d0198-4797-4c0e-9b46-3061c7f99186">

The other UI problem consists in the floating windows that are not really floating. They do not specify a certain space thus hiding away things that can happen in the 3D space. It would be imperative to have no ui elements hiding the 3D space. This should be contained in its own space.

Another flaw is what I call the salad. 

<img width="935" alt="2" src="https://github.com/turanszkij/WickedEngine/assets/70328320/7c775970-b399-4943-97d8-087f749b9cba">

Never combine together things that could go separate. This creates a salad - all the things inside one place and is confusing. The camera settings should be put inside the top bar somewhere for example. Paint tool could be a button in itself like inside UE (see number 2), same with the theme of the engine, the graphics, etc.

However.

<img width="1160" alt="3" src="https://github.com/turanszkij/WickedEngine/assets/70328320/3a12fdf7-968e-4f87-8387-69ce6b257e9f">

Some things can be combined - like the mesh properties and its material properties. One can use drop down menus for a better organization. Why click multiple times to search and find a property when you can click only once. Humans are lazy and prefer friction-less behavior. 

Going back to UE. My opinion is that ANY engine should have the corresponding elements (no matter how one chooses to name them) of:

top bar, 
tab system bar, 
3D space/2D space/Working space, 
the outliner, 
details/properties, 
file system/content. 

But how should those elements be aligned? 
One different example can be seen below.

<img width="1227" alt="5" src="https://github.com/turanszkij/WickedEngine/assets/70328320/0c49e199-4359-435a-b715-b7844ecd5ada">

Because I personally have a wide screen, it makes sense to have the file system + outliner in the far left (both list heavy) and inspector/properties in the far right. There is something of a tab system and a top bar. They all have a text describing what they do. The script editor **can** be detached and moved to another screen although I'd _personally_ preferred to be more wide screen friendly and have the ability to put it alongside the 3D space to the right. 

Anyway, I spent hours researching, trying the WickedEngine and writing this. I really hope my time and ideas will help - not you, but the engine in becoming easier to use and adopt by as many other developers as possible. It has nice features and the theme looks sleek. But it **must** become easier to use. What other purpose it could have? it is a tool therefore it must be used by as many people as possible. 
Good luck!

**Comment by VinnyVicious** [comment]
I feel that the engine is very powerful oriented towards experienced developers that will spend less time on the UI and more time coding. While I do think this would be a good improvement, I think it would be a waste of time to focus on UI. Every engine out there is trying to copy Unity/Unreal and loses focus. What's cool about Wicked is that it stands out by actually giving features that save time for indie devs.

**Comment by VinnyVicious** [comment]
Everyone focuses on being easy to easy, easy to adopt. Where do the power users go to?

**Comment by turanszkij** [comment]
#843 was merged, editor gui had a big overhaul.

**Comment by mddm1** [comment]
looks better can't wait to try it! thanks

**Comment by VinnyVicious** [comment]
that is fantastic
