### ISSUE TITLE
Double-clicking an object in Entities menu moves the to it

### ISSUE THREAD

**Issue by Nickykun** [turanszkij/WickedEngine#834]
Obviously, the Wicked Engine UI is unfriendly and needs a complete redesign. However, I won't talk about it. More details in #830 Let's start small. 

The F key doesn't work when the mouse is in the Entities menu. Double-clicking on an object in the menu scene to focus the camera on the object like it is in other engines (e.g. Unity or Godot) would quicker and easier the development process.

**Comment by turanszkij** [comment]
This is handled here #843

**Comment by turanszkij** [comment]
Completed
