### ISSUE TITLE
How to build template

### ISSUE THREAD

**Issue by MineStorm999** [turanszkij/WickedEngine#852]
I want to build the win_template but if I try to execute the .exe from the explorer it just stops immediately. What do I have to do, because it worked when I started it via visual studio (Like shown in the example vids).

**Comment by turanszkij** [comment]
Copy the exe to the working directory specified in Visual Studio project settings: 
<img width="1353" alt="image" src="https://github.com/turanszkij/WickedEngine/assets/12954849/83688466-5633-489a-93e5-bdd5bbde6bd8">
Or set the working directory through Windows shortcut
