### ISSUE TITLE
[Feature Request] Remappable Keys

### ISSUE THREAD

**Issue by VincentVancalbergh** [turanszkij/WickedEngine#860]
I use an AZERTY keyboard, so navigating the editor using WASD is strange (since for me, those buttons are in the AQSD locations). So please add remapping those keys.

**Comment by brakhane** [comment]
I agree that being able to change keys via eg. config.ini would be nice. For the moment, you can manually change them by modifying [these lines](https://github.com/turanszkij/WickedEngine/blob/6b41ec3b657da1fc4263bdb4f2d5a0a0ddb77c85/Editor/Editor.cpp#L1171-L1176)
