### ISSUE TITLE
DOF. Incorrect resource allocation

### ISSUE THREAD

**Issue by IceLuna** [turanszkij/WickedEngine#861]
Hi! I was going through DOF implementation and noticed a couple of issues during resource allocation inside `CreateDepthOfFieldResources()`.

1. `Height` of `horizontal` textures is wrongly set to `tile_desc.height = resolution.x;`. It should be `resolution.y` since the vertical size needs to be at "full"-scale.
2. Excessive memory allocation for "tile"-buffers. Currently, they have the size `bufferdesc.size = tile_desc.width * tile_desc.height * bufferdesc.stride`, where `tile_desc` contains dimensions of "horizontal" textures, which means `tile_desc.height` is unnecessary big for the buffers.

**Comment by IceLuna** [comment]
I think the second issue is also the same in motion blur

**Comment by IceLuna** [comment]
Also, `R16_FLOAT` is used for `texture_tilemin` and `texture_tilemin_horizontal` in Motion Blur. I think it should be `R16G16_FLOAT`

**Comment by turanszkij** [comment]
Thanks for reporting this, I fixed these issues.

**Comment by IceLuna** [comment]
@turanszkij Hi again!
I noticed you're not using the improved version of `SpreadCmp` function for motion blur, is it intentional?
Your version is from slide 63, but later (slide 82) they've made some changes to it to avoid sampling issues.

![image](https://github.com/turanszkij/WickedEngine/assets/48557794/51cfa34b-9442-4ceb-8f32-4144908bdb75)
![image](https://github.com/turanszkij/WickedEngine/assets/48557794/54c6633a-5653-4df8-a872-6970f41c967a)

**Comment by turanszkij** [comment]
I don't remember exactly, but right now I don't see an improvement, it's probably miniscule.
