### ISSUE TITLE
found something, not good

### ISSUE THREAD

**Issue by Acromatic** [turanszkij/WickedEngine#866]
character controller script, editor.. my own vs build, current github version... my pc has no issues
![Screenshot 2024-06-20 043526](https://github.com/turanszkij/WickedEngine/assets/8341068/6a812cfd-2902-4aab-9eb8-92c3ff5fda29)

**Comment by turanszkij** [comment]
Hi, unfortunately there is no easy way to tell what went wrong here. If you have any steps to easily reproduce the issue, please tell. But this could be also specific to a GPU, and maybe no way to repeat it on my end.

**Comment by Acromatic** [comment]
well it happened another time when I ran another script.. gpu is 1660ti...

**Comment by brakhane** [comment]
do you have the latest gpu drivers installed? If not, do that, if you have, as an experiment you could try installing the studio drivers instead. Those are generally more stable (at the cost of potentially a few FPS).

Does the crash also appear in other examples, or just this one?

**Comment by Acromatic** [comment]
only in the new scripts, 2 of them at least... personally I think it's either in the way the engine interacts with lua, or it's my aging GPU.. this thing can handle what a 2060GTX does, but it's missing some of the new architecture and ratings.... so you can look there, I'm generally unaffected at this time and it might just be a problem that grandfathers it's way out.
