### ISSUE TITLE
"editor gui anti aliasing" broke UI rendering on AMD cards

### ISSUE THREAD

**Issue by brakhane** [turanszkij/WickedEngine#872]
It seems like commit 4ceef0c283968f700db4d9a0fc83b1668de88065 broke rendering on (some?) AMD cards. It definitely doesn't work on RX 580. Drivers are up to date.

![bug](https://github.com/turanszkij/WickedEngine/assets/541637/c2a3f146-bab0-4810-88e3-c3a96aae4e2e)

I don't have an AMD card, but one user affected by that bug confirmed that reverting that particular commit makes the UI show up again.

**Comment by kariem2k** [comment]
It is happening in DX12 and Vulkan FYI

**Comment by turanszkij** [comment]
I can't repro this, tested on the graphics cards:
- AMD RX6650
- Nvidia 1070, 2060
- Intel 620
Vulkan, DX12 don't say any errors related to this.

**Comment by turanszkij** [comment]
A commit has been added that attempts to change some things around the MSAA that I suspect could be a thing AMD driver is handling incorrectly. Please try the latest version from Github.

**Comment by kariem2k** [comment]
[wickedengine.zip](https://github.com/user-attachments/files/16098283/wickedengine.zip)


This is a capture from RenderDoc 1.31

Thanks

**Comment by turanszkij** [comment]
Looks like the capture replays fine for me, this is most likely a driver issue. I'll try to report it to AMD.

**Comment by turanszkij** [comment]
I made an update, the gui anti aliasing can be turned off by adding a line to config.ini's root section of the Editor:
```
gui_antialiasing = 0
```
Valid values for this are 0, 1, 2, 4, 8 directly specifying sample count of multisampling. 0 and 1 will turn it off (single sampling)
