### ISSUE TITLE
[Feature request] Add icon flipping

### ISSUE THREAD

**Issue by AttackButton** [turanszkij/WickedEngine#888]
Hi, I needed to flip one of the icons horizontally for an editor button, and I noticed that there is no such version available on the Font Awesome website. If it's possible to add the ability to rotate icons within Wicked Engine, that would be great.

**Comment by turanszkij** [comment]
You can rotate text with wi::font::FontParams::rotation (each gui widget has a SpriteFont and that has the params that can be modified). Flipping is not supported but it can be added.

**Comment by AttackButton** [comment]
Thanks, man. The icon was the default play button (a simple triangle) and rotating it by pi was enough. I will close this issue/request later.

It seems that I found a bug, probably because I created two buttons with the same icon (one rotated and the default one) in the same editor window, and because of that, one tool tip overrides the one on the other button, both end up with the same tool tip. Could you check this?

**Comment by turanszkij** [comment]
The tool tip overwriting could be because localization in the editor. Try creating the two buttons with different names, then you can use SetText() on them to set the text they are drawing (your icon). I will add the flipping too, maybe it will be useful for other things.

**Comment by AttackButton** [comment]
Everything is working now. Thanks again.

**Comment by turanszkij** [comment]
Nice, I also added flipping to fonts, you can use font.params.enableFlipHorizontally() and enableFlipVertically(). I think this can be now closed.
