### ISSUE TITLE
[Question]  I wonder that some code out of UpdateTransform_Parented.

### ISSUE THREAD

**Issue by setimets** [turanszkij/WickedEngine#89]
First of all, I'm really appreciate your code.

I'm analyzing your [code](https://github.com/turanszkij/WickedEngine/blob/53f5a072cfc1e66311c2fa3dc78016c05708457f/WickedEngine/wiScene.cpp#L1459
) but I don't understand below some of the code.

```cpp
// Child updated immediately, to that it can be immediately attached to afterwards:
transform_child->UpdateTransform_Parented(*transform_parent, parentcomponent.world_parent_inverse_bind);
```

I think that **W_parent * inverseParentBindMatrix** becomes an identity matrix and when the parent.IsDirty() is not true then It'll be only stored the local matrix. And I think it should be the world matrix as your purpose but It can't in this case. 

I'd like to know why did you make it like this.

Thanks.

**Comment by turanszkij** [comment]
Hi, you might be right and maybe those are no longer needed. I don't remember exactly what is the reason I do those, but probably some workarounds. I will need to test thoroughly before saying for sure.

**Comment by turanszkij** [comment]
I removed these parts, thanks for looking into this! Hopefully won't break anything.
