### ISSUE TITLE
TextInputField Input Loss When Hovering Over Entities Tree

### ISSUE THREAD

**Issue by AttackButton** [turanszkij/WickedEngine#901]
Starting to type in a TextInputField and then hovering the mouse over the Entities Tree area (without clicking) causes the input to be canceled, resulting in the loss of the entered text.

I'm not sure if this issue occurs with other widgets.

![input_cancel](https://github.com/user-attachments/assets/40d3fd14-45cc-46c7-b229-2f41bc199131)

**Comment by turanszkij** [comment]
Thanks for reporting, it should be fixed.
