### ISSUE TITLE
Volumetric Lighting & Fog

### ISSUE THREAD

**Issue by antonyjones67** [turanszkij/WickedEngine#92]
I can see from your video that you have what looks like Volumetric Lighting. But I was interested in how you would implement Volumetric Fog using light probes to determine more realistic fog.

**Comment by antonyjones67** [comment]
From your videos I can see an approach. Is it using particles?

**Comment by turanszkij** [comment]
Hi, I'm afraid I don't know what you mean by volumetric lighting using probes. I implemnted volumetric lighting/fog using ray marching.

**Comment by antonyjones67** [comment]
I definitely can't pretend to understand all this stuff. I just watched this video and found it interesting.
Volumetric Fog and Lighting in Unreal Engine 4 | GDC 2018 | Unreal Engine
I will put the youtube link below. But if you are concerned about the link you can look up the above subject on YouTube.
https://www.youtube.com/watch?v=Xd7-rTzfmCo

**Comment by antonyjones67** [comment]
When I used the words "more realistic fog". I realize this could be misinterpreted as a comparison with the fog already in Wicked Engine. I wasn't comparing. When I meant more realistic, I was referring to the occlusion of fog from areas like underneath trees or in a houses. Would ray marching achieve this?

**Comment by antonyjones67** [comment]
Omgosh. Ray marching sounds awesome! Just ignore me and close this out. Thank You!

**Comment by turanszkij** [comment]
Ray marching is the default method to achieve volumetric lighting. You can also use lit particles to achieve some volumetric light effects.

**Comment by antonyjones67** [comment]
Cool. Ty
