### ISSUE TITLE
Switching output windows

### ISSUE THREAD

**Issue by Geniok** [turanszkij/WickedEngine#947]
Hi.
Is it possible to somehow implement switching between graphics output windows while the application is running?
I have 3 windows, each with its own hwnd. I want to be able to dynamically specify which window to output the render to at the moment.
Using Application::SetWindow(wi::platform::window_type window) does not help, the output still occurs in the window that was specified during the first call of the Application::SetWindow() function.

**Comment by turanszkij** [comment]
You will need 3 swap chains, one for each window, and then draw to the swapchain that you want. This is not implemented in the Application class, but there you can see how to create swap chains and how to draw to them.

**Comment by Geniok** [comment]
Yes, I added std::vector<wi::graphics::SwapChain> swapChains there.
Do I need to use std::vector<wi::platform::window_type> windows or can I get by with just wi::platform::window_type ?

My current idea is that for each wi::platform::window_type you need to have your own wi::graphics::SwapChain, your own wi::Canvas and your own wi::graphics::SwapChainDesc.

And in the OnRender() method for each SwapChain:

````
for (auto& swapChain : swapChains)
{
    CommandList cmd = m_graphicsDevice->BeginCommandList();
    wi::image::SetCanvas(canvas);
    wi::font::SetCanvas(canvas);
    Viewport viewport;
    viewport.width = (float)swapChain->desc.width;
    viewport.height = (float)swapChain->desc.height;
    m_graphicsDevice->BindViewports(1, &viewport, cmd);
    m_graphicsDevice->RenderPassBegin(swapChain.get(), cmd);
    m_graphicsDevice->RenderPassEnd(cmd);

    wi::input::ClearForNextFrame();
    wi::profiler::EndFrame(cmd);
    m_graphicsDevice->SubmitCommandLists();
}
````

But I'm not sure how correct it is.

**Comment by turanszkij** [comment]
You will need one window for each swap chain. These things in your snippet should be called only once per frame, not for every swapchain:
```
wi::input::ClearForNextFrame();
wi::profiler::EndFrame(cmd);
m_graphicsDevice->SubmitCommandLists();
```

**Comment by Geniok** [comment]
Thank you, everything worked out great!

Another question, is it possible to make each SwapChain display its own scene?

**Comment by turanszkij** [comment]
This is a matter of what you draw into it, so yes. Probably the easiest way would be to use a different scene for each and a different RenderPath3D for each, and drawing the each renderpath's result into the corresponding swapchain. You can set renderpath's scene member pointer to the scene you want to render.

**Comment by Geniok** [comment]
Thank you!

I'll try to implement it.
I think we can close the issue.
