### ISSUE TITLE
(DX12) Weird lighting artifacts around many objects in the first_person_13 scene

### ISSUE THREAD

**Issue by Rossakis** [turanszkij/WickedEngine#954]
For reference, I'm using a the DX12 version on 64-bit PC, with AMD Radeon RX 7900 XTX and Intel i9-14900K. I also have a 4k screen, if that helps.

![Screenshot 2024-10-03 233509](https://github.com/user-attachments/assets/7c1a9b2c-c01a-4ecd-a900-754b72fd5419)
![Screenshot 2024-10-03 233533](https://github.com/user-attachments/assets/c5cb6bc3-5cf5-471a-a88f-3a234c46884e)

EDIT: I checked, and this doesn't happen in the Vulkan version.

**Comment by turanszkij** [comment]
Thanks for reporting, unfortunately I can't repro this on AMD 6650 XT. I have made some safety updates in this commit: https://github.com/turanszkij/WickedEngine/commit/0d7a77abc52eebcd410b3814fb990b948c46ce65 you could try and see if it changes anything but this is just a shot in the dark.

**Comment by turanszkij** [comment]
I noticed a similar issue on Intel GPU, there is a fix: https://github.com/turanszkij/WickedEngine/commit/a90ffbfd4e269ecf369575f74295127674af411d
Because this didn't happen on AMD for me, I am not sure the same fix will apply for AMD.

**Comment by Rossakis** [comment]
It worked for me, for both DX12 and Vulkan versions, although I have AMD card, so thanks!

**Comment by Rossakis** [comment]
It worked for me, for both DX12 and Vulkan versions, although I have AMD card, so thanks!
