### ISSUE TITLE
Character appears messed when activating the humanoid -> ragdoll checkbox

### ISSUE THREAD

**Issue by Anthony-Gaudino** [turanszkij/WickedEngine#958]
When I open a character, if I select it and in the humanoid component I check the **ragdoll** option the character appears messed up.
![Screenshot 2024-10-06 190447](https://github.com/user-attachments/assets/30fc7357-4ac1-4bec-b6e6-727dcfc91f94)

Activating the physics simulation will fix the character and it will "ragdoll".

**Comment by turanszkij** [comment]
Thanks, should be fixed now.
