### ISSUE TITLE
Delete a terrain cannot be undone

### ISSUE THREAD

**Issue by Anthony-Gaudino** [turanszkij/WickedEngine#966]
In Windows 11, running a Debug build, if I add a terrain to an empty scene and delete the terrain from the entities panel, if I try to undo this operation (ctrl+z) it doesn't work. Also if I keep pressing (ctrl+z) the editor crashes with: 
```
Exception thrown at 0x00007FFC0C7BFE4C in Editor_Windows.exe: Microsoft C++ exception: std::length_error at memory location 0x000000A49FBB31E0.
Unhandled exception at 0x00007FFC0C7BFE4C in Editor_Windows.exe: Microsoft C++ exception: std::length_error at memory location 0x000000A49FBB31E0
```

Another thing to note is that deleting the terrain leaves trees billboards in the scene.

**Comment by turanszkij** [comment]
Thanks for reporting, it is now fixed.
