### ISSUE TITLE
VRoid VRM model hair become strange in latest version

### ISSUE THREAD

**Issue by D3ZAX** [turanszkij/WickedEngine#981]
version 0.71.613
![image](https://github.com/user-attachments/assets/3fe2ca84-9681-435b-ac4e-c646188137f0)

It is normal in version 0.71.585
![image](https://github.com/user-attachments/assets/3fd06b68-cfb8-4bfc-9e72-58f33438bab2)

Model is made by VRoid.

**Comment by turanszkij** [comment]
Hi, I can repro this with the latest Vroid Studio if I export as VRM 0.0 format. If you export in VRM 1.0 format it seems to work well. Here is how you can export as 1.0 from Vroid studio: 
![image](https://github.com/user-attachments/assets/2da354ac-9729-4d70-a4fc-dd4cbe888214)
I will investigate the issue with VRM 0.0 importing, but meanwhile you could use this workaround.

**Comment by turanszkij** [comment]
The commit above fixes it, thanks for reporting the issue.
