### ISSUE TITLE
LoadModel will never return invalid entity

### ISSUE THREAD

**Issue by CitroenGames** [turanszkij/WickedEngine#984]
if we load a model from wiscene there is no way to check if the loading went successful or not

```
	if (ent == wi::ecs::INVALID_ENTITY)
	{
		assert(true);
	}
```

or 
```
	if (ent.IsEmpty())
	{
		assert(true);
	}
```

would be a nice way to check if anything went wrong

**Comment by turanszkij** [comment]
That's not what the returned entity means, check the comment above function declaration. It is always returning a base parent entity that will be the parent of everything in the scene, if attached parameter is true. To check the scene loading errors, they will be posted on the backlog (and console output window).

**Comment by CitroenGames** [comment]
oh alright thanks
