### ISSUE TITLE
Transform constraints

### ISSUE THREAD

**Issue by turanszkij** [turanszkij/WickedEngine#99]
Most notably to improve inverse kinematics, need a way to limit procedural transform rotations.

**Comment by Tannz0rz** [comment]
Hello turanszkij, I have dealt with this exact problem with swing-twist decomposition. Please see the links below, you may find it of some use:
https://github.com/Tannz0rz/FABRIK/blob/master/Assets/FABRIK/FABRIKEffector.cs#L97
https://github.com/Tannz0rz/FABRIK/blob/master/Assets/FABRIK/QuaternionExtension.cs

**Comment by turanszkij** [comment]
@Tannz0rz Thanks a lot, I will take a look!

**Comment by turanszkij** [comment]
Was mainly interested in IK constraint, now it's implemented: https://github.com/turanszkij/WickedEngine/commit/d5d5eb613c92c8dd4348a124571795ee108e2039
