### ISSUE TITLE
Editor UI gets resized to twice the scale after opening the Wicked Shooter demo

### ISSUE THREAD

**Issue by Rossakis** [turanszkij/WickedEngine#992]
I'm not sure why, perhaps due to the game trying to adjust the resolution setting to 100% (I have a big 32-inch 4k monitor), but when I go back to the editor, all of the engine's UI gets doubled in size too. Is there a way to manually change the UI scaling of the Editor to default setting without having to resort to closing and opening the engine (which fixes it, until I open this project again) ?

![Screenshot 2024-12-21 011940](https://github.com/user-attachments/assets/dcdf1daa-0ff8-41f4-828b-e0eba94cd2c2)

![Screenshot 2024-12-21 012903](https://github.com/user-attachments/assets/63b8d291-55df-49f8-a3ab-3bbcf0c40507)

**Comment by turanszkij** [comment]
Yes, this is because this game overwrites the application's scaling (to always display the menu in the same for all resolutions). When `ReturnToEditor()` is called by the script, the script should also restore the original scaling factor. I will fix it for the next update of the game.

For the time being I leave it here how to change custom scaling factor of the application from script:

```lua
local canvas = application.GetCanvas()
canvas.SetCustomScaling(1.5)
application.SetCanvas(canvas)
```

The above would set the custom scaling to 1.5 = 150%

**Comment by Rossakis** [comment]
I see now. Imo, it'd also be a good option to have a special button in the Editor in the General Settings to set the UI scaling by hand, because maybe someone would even like the UI bigger or smaller , or in cases of a bug like the users would be able to easily fix it.

**Comment by turanszkij** [comment]
Yes, that would be good, I'll add it. I think if we have editor specific option for custom scaling, then ReturnToEditor() should be able to set that back too, so wouldn't need changes in the script.

**Comment by turanszkij** [comment]
I added a gui scaling combo box to the editor bottom left corner where you can now choose a scaling factor. This is an additional scaling factor on top of the operating system's setting for the monitor. The editor will always force this scaling, so returning from the script will re-apply the selected scaling, so I think this fixes your issue.
![image](https://github.com/user-attachments/assets/a15f0027-894e-4a9c-a7cf-0d43cc93ec68)
