### ISSUE TITLE
regression: #985 broke HDR display on NVidia

### ISSUE THREAD

**Issue by brakhane** [turanszkij/WickedEngine#994]
Looks like #985 broke rendering on my card.

*Update: it only happens in HDR, SDR is fine*

NVidia 3090Ti on driver version 565.90

I noticed a strange effect, it seems to what else is rendered (the washed out colors are not a problem, just an artifact of OBS not handling HDR)
![image](https://github.com/user-attachments/assets/a0db8098-e22c-4657-ba9a-cc20f7730043)

https://github.com/user-attachments/assets/35c41928-c946-41e6-bee6-91954ba4070b

I've bisected it to the fp16 optimization commit

```
commit 842e2a0478689fa5901dabb41c97e4e0e81e69de
Author: Turánszki János <turanszkij@users.noreply.github.com>
Date:   Sun Dec 8 17:45:28 2024 +0100

    fp16 optimizations (#985)
```

**Comment by turanszkij** [comment]
Thanks for reporting, it's fixed now.
